// Generates packages/api-contract/openapi.json from the zod schemas (architecture §6.4).
// Usage: node scripts/gen-openapi.mjs [--check]   (--check: exit 1 if the committed file differs)
import { mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { build } from 'esbuild'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const out = path.resolve(root, '../../packages/api-contract/openapi.json')
// Same document as a TS module for the runtime endpoint (JSON imports differ between tsx, webpack
// and esbuild; a TS const works in all three).
const outTs = path.join(root, 'src/api/v1/openapi.generated.ts')
const pkg = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'))

const tmp = mkdtempSync(path.join(os.tmpdir(), 'pk-openapi-'))
try {
  const bundle = path.join(tmp, 'openapi.mjs')
  await build({
    entryPoints: [path.join(root, 'src/api/v1/openapi.ts')],
    outfile: bundle,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node24',
    tsconfig: path.join(root, 'tsconfig.json'),
    logLevel: 'warning',
  })
  const { buildOpenApiDocument } = await import(pathToFileURL(bundle).href)
  const doc = `${JSON.stringify(buildOpenApiDocument(pkg.version), null, 2)}\n`
  const ts = `/* GENERATED by scripts/gen-openapi.mjs — do not edit. */\nexport const openapiDocument = ${doc.trimEnd()} as const\n`
  const targets = [
    [out, doc],
    [outTs, ts],
  ]
  if (process.argv.includes('--check')) {
    let drift = false
    for (const [file, content] of targets) {
      let current = ''
      try {
        current = readFileSync(file, 'utf8')
      } catch {
        current = ''
      }
      if (current !== content) {
        drift = true
        console.error(`openapi drift: ${path.relative(process.cwd(), file)} is not up to date — run npm run gen:openapi`)
      }
    }
    if (drift) process.exit(1)
    console.log('openapi documents up to date')
  } else {
    for (const [file, content] of targets) {
      mkdirSync(path.dirname(file), { recursive: true })
      writeFileSync(file, content)
      console.log(`wrote ${path.relative(process.cwd(), file)}`)
    }
  }
} finally {
  rmSync(tmp, { recursive: true, force: true })
}
