/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    employees: Employee;
    'employee-bank-accounts': EmployeeBankAccount;
    banks: Bank;
    clients: Client;
    vendors: Vendor;
    projects: Project;
    'project-stages': ProjectStage;
    'stage-templates': StageTemplate;
    'budget-lines': BudgetLine;
    'expense-categories': ExpenseCategory;
    'cash-in-sources': CashInSource;
    'cash-accounts': CashAccount;
    'team-assignments': TeamAssignment;
    'work-schedules': WorkSchedule;
    holidays: Holiday;
    'approval-rules': ApprovalRule;
    'notification-templates': NotificationTemplate;
    uoms: Uom;
    vehicles: Vehicle;
    'cost-centers': CostCenter;
    'document-sequences': DocumentSequence;
    'expense-requests': ExpenseRequest;
    'expense-line-snapshots': ExpenseLineSnapshot;
    approvals: Approval;
    receipts: Receipt;
    'receipt-flags': ReceiptFlag;
    transfers: Transfer;
    settlements: Settlement;
    'cash-entries': CashEntry;
    'period-closings': PeriodClosing;
    attendances: Attendance;
    'attendance-corrections': AttendanceCorrection;
    'progress-reports': ProgressReport;
    'budget-addenda': BudgetAddendum;
    notifications: Notification;
    devices: Device;
    'web-sessions': WebSession;
    'audit-logs': AuditLog;
    'media-receipts': MediaReceipt;
    'media-transfer-proofs': MediaTransferProof;
    'media-selfies': MediaSelfy;
    'media-progress-photos': MediaProgressPhoto;
    'media-signatures': MediaSignature;
    'media-company': MediaCompany;
    'media-attachments': MediaAttachment;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    employees: EmployeesSelect<false> | EmployeesSelect<true>;
    'employee-bank-accounts': EmployeeBankAccountsSelect<false> | EmployeeBankAccountsSelect<true>;
    banks: BanksSelect<false> | BanksSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-stages': ProjectStagesSelect<false> | ProjectStagesSelect<true>;
    'stage-templates': StageTemplatesSelect<false> | StageTemplatesSelect<true>;
    'budget-lines': BudgetLinesSelect<false> | BudgetLinesSelect<true>;
    'expense-categories': ExpenseCategoriesSelect<false> | ExpenseCategoriesSelect<true>;
    'cash-in-sources': CashInSourcesSelect<false> | CashInSourcesSelect<true>;
    'cash-accounts': CashAccountsSelect<false> | CashAccountsSelect<true>;
    'team-assignments': TeamAssignmentsSelect<false> | TeamAssignmentsSelect<true>;
    'work-schedules': WorkSchedulesSelect<false> | WorkSchedulesSelect<true>;
    holidays: HolidaysSelect<false> | HolidaysSelect<true>;
    'approval-rules': ApprovalRulesSelect<false> | ApprovalRulesSelect<true>;
    'notification-templates': NotificationTemplatesSelect<false> | NotificationTemplatesSelect<true>;
    uoms: UomsSelect<false> | UomsSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    'cost-centers': CostCentersSelect<false> | CostCentersSelect<true>;
    'document-sequences': DocumentSequencesSelect<false> | DocumentSequencesSelect<true>;
    'expense-requests': ExpenseRequestsSelect<false> | ExpenseRequestsSelect<true>;
    'expense-line-snapshots': ExpenseLineSnapshotsSelect<false> | ExpenseLineSnapshotsSelect<true>;
    approvals: ApprovalsSelect<false> | ApprovalsSelect<true>;
    receipts: ReceiptsSelect<false> | ReceiptsSelect<true>;
    'receipt-flags': ReceiptFlagsSelect<false> | ReceiptFlagsSelect<true>;
    transfers: TransfersSelect<false> | TransfersSelect<true>;
    settlements: SettlementsSelect<false> | SettlementsSelect<true>;
    'cash-entries': CashEntriesSelect<false> | CashEntriesSelect<true>;
    'period-closings': PeriodClosingsSelect<false> | PeriodClosingsSelect<true>;
    attendances: AttendancesSelect<false> | AttendancesSelect<true>;
    'attendance-corrections': AttendanceCorrectionsSelect<false> | AttendanceCorrectionsSelect<true>;
    'progress-reports': ProgressReportsSelect<false> | ProgressReportsSelect<true>;
    'budget-addenda': BudgetAddendaSelect<false> | BudgetAddendaSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    devices: DevicesSelect<false> | DevicesSelect<true>;
    'web-sessions': WebSessionsSelect<false> | WebSessionsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'media-receipts': MediaReceiptsSelect<false> | MediaReceiptsSelect<true>;
    'media-transfer-proofs': MediaTransferProofsSelect<false> | MediaTransferProofsSelect<true>;
    'media-selfies': MediaSelfiesSelect<false> | MediaSelfiesSelect<true>;
    'media-progress-photos': MediaProgressPhotosSelect<false> | MediaProgressPhotosSelect<true>;
    'media-signatures': MediaSignaturesSelect<false> | MediaSignaturesSelect<true>;
    'media-company': MediaCompanySelect<false> | MediaCompanySelect<true>;
    'media-attachments': MediaAttachmentsSelect<false> | MediaAttachmentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'company-settings': CompanySetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'company-settings': CompanySettingsSelect<false> | CompanySettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      auditDailyAnchor: TaskAuditDailyAnchor;
      sendEmail: TaskSendEmail;
      reimburseAutoClose: TaskReimburseAutoClose;
      selfieRetention: TaskSelfieRetention;
      dailyReminders: TaskDailyReminders;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  email: string;
  name?: string | null;
  /**
   * Disinkronkan ke realm role Keycloak.
   */
  roles?: ('pk-staff' | 'pk-pm' | 'pk-finance' | 'pk-owner' | 'pk-admin')[] | null;
  employee?: (number | null) | Employee;
  phone?: string | null;
  /**
   * PNG tanda tangan Anda (latar putih/transparan). Dipakai otomatis saat mengirim/menyetujui pengajuan (US-43). Klik "Buat Baru" untuk mengunggah, lalu Simpan.
   */
  signature?: (number | null) | MediaSignature;
  /**
   * Diisi otomatis dari Keycloak.
   */
  keycloakSub?: string | null;
  active?: boolean | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees".
 */
export interface Employee {
  id: number;
  code: string;
  name: string;
  nickname?: string | null;
  position?: string | null;
  phone?: string | null;
  workSchedule?: (number | null) | WorkSchedule;
  faceRefPhoto?: (number | null) | MediaSelfy;
  /**
   * Referensi Odoo (diisi saat mirror, ADR 0009).
   */
  odooEmployeeRef?: string | null;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-schedules".
 */
export interface WorkSchedule {
  id: number;
  name: string;
  startTime: string;
  endTime: string;
  lateToleranceMin?: number | null;
  workDays?: {
    mon?: boolean | null;
    tue?: boolean | null;
    wed?: boolean | null;
    thu?: boolean | null;
    fri?: boolean | null;
    sat?: boolean | null;
    sun?: boolean | null;
  };
  active?: boolean | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-selfies".
 */
export interface MediaSelfy {
  id: number;
  uploadedBy?: (number | null) | User;
  receivedAt?: string | null;
  ownerDocType?: string | null;
  ownerDocId?: string | null;
  sha256Original?: string | null;
  originalWidth?: number | null;
  originalHeight?: number | null;
  originalSize?: number | null;
  capturedAt?: string | null;
  removedAt?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-signatures".
 */
export interface MediaSignature {
  id: number;
  uploadedBy?: (number | null) | User;
  receivedAt?: string | null;
  ownerDocType?: string | null;
  ownerDocId?: string | null;
  sha256Original?: string | null;
  originalWidth?: number | null;
  originalHeight?: number | null;
  originalSize?: number | null;
  capturedAt?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-bank-accounts".
 */
export interface EmployeeBankAccount {
  id: number;
  employee: number | Employee;
  bank: number | Bank;
  accountNo: string;
  accountHolder: string;
  label?: string | null;
  isDefault?: boolean | null;
  verificationStatus: 'unverified' | 'verified';
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banks".
 */
export interface Bank {
  id: number;
  code: string;
  name: string;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  contact?: string | null;
  phone?: string | null;
  address?: string | null;
  /**
   * Referensi Odoo (diisi saat mirror, ADR 0009).
   */
  odooPartnerRef?: string | null;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: number;
  name: string;
  contact?: string | null;
  npwp?: string | null;
  address?: string | null;
  /**
   * Referensi Odoo (diisi saat mirror, ADR 0009).
   */
  odooPartnerRef?: string | null;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  code: string;
  name: string;
  client?: (number | null) | Client;
  address?: string | null;
  lat?: number | null;
  lng?: number | null;
  radiusM?: number | null;
  pm?: (number | null) | User;
  budget?: number | null;
  startDate?: string | null;
  targetDate?: string | null;
  status: 'perencanaan' | 'berjalan' | 'ditunda' | 'selesai' | 'arsip';
  /**
   * Dihitung dari bobot × progress tahapan (hanya lewat laporan progress).
   */
  progressPct?: number | null;
  /**
   * Referensi Odoo (diisi saat mirror, ADR 0009).
   */
  odooAnalyticRef?: string | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-stages".
 */
export interface ProjectStage {
  id: number;
  project: number | Project;
  name: string;
  weightPct?: number | null;
  sequence: number;
  progressPct?: number | null;
  /**
   * Nonaktif = tidak dihitung dalam bobot & progress project.
   */
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stage-templates".
 */
export interface StageTemplate {
  id: number;
  name: string;
  items?:
    | {
        name: string;
        weightPct: number;
        sequence: number;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget-lines".
 */
export interface BudgetLine {
  id: number;
  project: number | Project;
  category: number | ExpenseCategory;
  amount: number;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories".
 */
export interface ExpenseCategory {
  id: number;
  code: string;
  name: string;
  coaCode?: string | null;
  defaultUom?: (number | null) | Uom;
  allowedUoms?: (number | Uom)[] | null;
  requiresVehicle?: boolean | null;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uoms".
 */
export interface Uom {
  id: number;
  code: string;
  name: string;
  /**
   * mis. volume, waktu, akomodasi
   */
  category?: string | null;
  /**
   * Referensi Odoo (diisi saat mirror, ADR 0009).
   */
  odooUomRef?: string | null;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-in-sources".
 */
export interface CashInSource {
  id: number;
  code: string;
  name: string;
  coaCode?: string | null;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-accounts".
 */
export interface CashAccount {
  id: number;
  name: string;
  kind: 'cash' | 'bank';
  bank?: (number | null) | Bank;
  accountNo?: string | null;
  accountHolder?: string | null;
  openingBalance?: number | null;
  odooJournalCode?: string | null;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-assignments".
 */
export interface TeamAssignment {
  id: number;
  employee: number | Employee;
  project?: (number | null) | Project;
  costCenter?: (number | null) | CostCenter;
  roleInProject: 'pm' | 'staff' | 'mandor';
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-centers".
 */
export interface CostCenter {
  id: number;
  code: string;
  name: string;
  type: 'operational' | 'department';
  manager?: (number | null) | User;
  lat?: number | null;
  lng?: number | null;
  radiusM?: number | null;
  /**
   * Referensi Odoo (diisi saat mirror, ADR 0009).
   */
  odooAnalyticRef?: string | null;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holidays".
 */
export interface Holiday {
  id: number;
  date: string;
  name: string;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approval-rules".
 */
export interface ApprovalRule {
  id: number;
  name: string;
  docType: 'expense_request' | 'budget_addendum';
  requestType: 'any' | 'advance' | 'reimburse';
  minAmount: number;
  maxAmount?: number | null;
  category?: (number | null) | ExpenseCategory;
  project?: (number | null) | Project;
  costCenter?: (number | null) | CostCenter;
  /**
   * Angka kecil dievaluasi lebih dulu.
   */
  priority?: number | null;
  acknowledge: 'required' | 'optional' | 'none';
  acknowledgeBy: 'scope_manager' | 'role' | 'user';
  acknowledgeRole?: ('pk-staff' | 'pk-pm' | 'pk-finance' | 'pk-owner' | 'pk-admin') | null;
  acknowledgeUser?: (number | null) | User;
  signDiajukan: 'required' | 'optional' | 'none';
  signDibuat: 'required' | 'optional' | 'none';
  steps?:
    | {
        level: number;
        approverRole?: ('pk-staff' | 'pk-pm' | 'pk-finance' | 'pk-owner' | 'pk-admin') | null;
        approverUser?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-templates".
 */
export interface NotificationTemplate {
  id: number;
  event: string;
  title: string;
  body: string;
  channel: 'push' | 'inapp' | 'both';
  active?: boolean | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  plateNo: string;
  plateDisplay?: string | null;
  /**
   * mis. Hilux, Tronton
   */
  type: string;
  brandModel?: string | null;
  costCenter?: (number | null) | CostCenter;
  project?: (number | null) | Project;
  /**
   * Referensi Odoo (diisi saat mirror, ADR 0009).
   */
  odooFleetRef?: string | null;
  active?: boolean | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-sequences".
 */
export interface DocumentSequence {
  id: number;
  docType:
    | 'expense_request'
    | 'transfer'
    | 'settlement'
    | 'cash_in'
    | 'cash_out'
    | 'progress_report'
    | 'budget_addendum'
    | 'reversal';
  /**
   * Token {DOC}, mis. PB, TRF.
   */
  docCode: string;
  /**
   * Token: {seq} {DD} {MM} {MM_ROMAN} {YY} {YYYY} {COMPANY} {DOC}
   */
  pattern: string;
  resetPolicy: 'never' | 'yearly' | 'monthly';
  padding: number;
  startAt: number;
  timezone: string;
  active?: boolean | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-requests".
 */
export interface ExpenseRequest {
  id: number;
  docNo?: string | null;
  type: 'advance' | 'reimburse';
  status:
    | 'draft'
    | 'pending_ack'
    | 'pending_approval'
    | 'approved'
    | 'receipt_revision'
    | 'receipts_verified'
    | 'transferred'
    | 'receipts_complete'
    | 'lpj_submitted'
    | 'lpj_revision'
    | 'lpj_verified'
    | 'completed'
    | 'rejected'
    | 'cancelled';
  title: string;
  project?: (number | null) | Project;
  costCenter?: (number | null) | CostCenter;
  requestDate?: string | null;
  /**
   * Format YYYY-MM-DD (zona waktu perusahaan).
   */
  neededDate?: string | null;
  /**
   * Format YYYY-MM-DD (zona waktu perusahaan).
   */
  periodFrom?: string | null;
  /**
   * Format YYYY-MM-DD (zona waktu perusahaan).
   */
  periodTo?: string | null;
  notes?: string | null;
  requesters?: (number | Employee)[] | null;
  createdBy?: (number | null) | User;
  bankAccount?: (number | null) | EmployeeBankAccount;
  bankSnapshot?: {
    bankName?: string | null;
    accountNo?: string | null;
    accountHolder?: string | null;
  };
  /**
   * Tunggu sebentar setelah mengisi field sebelum menekan Tambah Baris.
   */
  lines?:
    | {
        description?: string | null;
        qty?: number | null;
        uom?: (number | null) | Uom;
        unitPrice?: number | null;
        total?: number | null;
        category?: (number | null) | ExpenseCategory;
        vehicle?: (number | null) | Vehicle;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  grandTotal?: number | null;
  approvedAmount?: number | null;
  transferredTotal?: number | null;
  verifiedReceiptsTotal?: number | null;
  attachments?: (number | MediaAttachment)[] | null;
  approvalRule?: (number | null) | ApprovalRule;
  approvalSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  approvalCycle?: number | null;
  currentLevel?: number | null;
  submittedAt?: string | null;
  contentHash?: string | null;
  resubmitOf?: (number | null) | ExpenseRequest;
  cancelReason?: string | null;
  rejectReason?: string | null;
  syncRev?: number | null;
  clientUuid?: string | null;
  source?: ('web' | 'apk' | 'system' | 'job') | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-attachments".
 */
export interface MediaAttachment {
  id: number;
  uploadedBy?: (number | null) | User;
  receivedAt?: string | null;
  ownerDocType?: string | null;
  ownerDocId?: string | null;
  sha256Original?: string | null;
  originalWidth?: number | null;
  originalHeight?: number | null;
  originalSize?: number | null;
  capturedAt?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-line-snapshots".
 */
export interface ExpenseLineSnapshot {
  id: number;
  request: number | ExpenseRequest;
  cycle: number;
  reason: 'submit' | 'approve' | 'receipts_resubmit';
  grandTotal: number;
  contentHash?: string | null;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  takenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approvals".
 */
export interface Approval {
  id: number;
  docType: 'expense_request' | 'budget_addendum';
  request?: (number | null) | ExpenseRequest;
  addendum?: (number | null) | BudgetAddendum;
  cycle: number;
  position: 'diajukan' | 'dibuat' | 'diketahui' | 'approval';
  level: number;
  actor?: (number | null) | User;
  employee?: (number | null) | Employee;
  actorName?: string | null;
  onBehalf?: boolean | null;
  decision: 'signed' | 'acknowledged' | 'approved' | 'rejected';
  reason?: string | null;
  decidedAt?: string | null;
  budgetPctBefore?: number | null;
  budgetPctAfter?: number | null;
  openFlags?: number | null;
  signature?: (number | null) | MediaSignature;
  signatureSha256?: string | null;
  signatureSource?: ('profile' | 'captured' | 'none') | null;
  deviceId?: string | null;
  source?: ('web' | 'apk' | 'system' | 'job') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Diajukan dan diputuskan lewat layar Addendum RAB (bukan dari form ini).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget-addenda".
 */
export interface BudgetAddendum {
  id: number;
  docNo?: string | null;
  project: number | Project;
  status: 'draft' | 'pending_ack' | 'pending_approval' | 'approved' | 'rejected' | 'cancelled';
  addition: number;
  reason: string;
  budgetAtSubmit?: number | null;
  /**
   * Dibaca ulang saat disetujui (terkunci).
   */
  oldBudget?: number | null;
  newBudget?: number | null;
  createdBy: number | User;
  submittedAt?: string | null;
  decidedAt?: string | null;
  approvalRule?: (number | null) | ApprovalRule;
  approvalSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  approvalCycle?: number | null;
  currentLevel?: number | null;
  rejectReason?: string | null;
  cancelReason?: string | null;
  source?: ('web' | 'apk') | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipts".
 */
export interface Receipt {
  id: number;
  request: number | ExpenseRequest;
  lineId: string;
  lineNo?: number | null;
  receiptNo?: string | null;
  receiptNoNorm?: string | null;
  vendor?: (number | null) | Vendor;
  vendorName: string;
  vendorNorm?: string | null;
  receiptDate: string;
  receiptTime?: string | null;
  amount: number;
  taxAmount?: number | null;
  image: number | MediaReceipt;
  imageSha256?: string | null;
  status: 'pending' | 'valid' | 'rejected' | 'removed';
  rejectReason?: string | null;
  removeReason?: string | null;
  verifiedBy?: (number | null) | User;
  verifiedAt?: string | null;
  entrySource?: ('manual' | 'ocr') | null;
  createdBy?: (number | null) | User;
  clientUuid?: string | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-receipts".
 */
export interface MediaReceipt {
  id: number;
  uploadedBy?: (number | null) | User;
  receivedAt?: string | null;
  ownerDocType?: string | null;
  ownerDocId?: string | null;
  sha256Original?: string | null;
  originalWidth?: number | null;
  originalHeight?: number | null;
  originalSize?: number | null;
  capturedAt?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipt-flags".
 */
export interface ReceiptFlag {
  id: number;
  request: number | ExpenseRequest;
  key: string;
  kind: 'amount_diff' | 'date_after_request' | 'date_too_old' | 'date_out_of_period' | 'uom_suspicious' | 'duplicate';
  level: 'info' | 'warning';
  lineId?: string | null;
  lineNo?: number | null;
  receipt?: (number | null) | Receipt;
  relatedRequest?: (number | null) | ExpenseRequest;
  message: string;
  detail?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'open' | 'reviewed' | 'resolved';
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  reviewNote?: string | null;
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfers".
 */
export interface Transfer {
  id: number;
  docNo?: string | null;
  request: number | ExpenseRequest;
  kind: 'advance' | 'reimburse' | 'lpj_shortfall';
  cashAccount: number | CashAccount;
  amount: number;
  destination?: {
    bankName?: string | null;
    accountNo?: string | null;
    accountHolder?: string | null;
  };
  bankRef: string;
  proof: number | MediaTransferProof;
  transferDate: string;
  postedBy?: (number | null) | User;
  status: 'posted' | 'void';
  cashEntry?: (number | null) | CashEntry;
  voidReason?: string | null;
  voidedBy?: (number | null) | User;
  voidedAt?: string | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-transfer-proofs".
 */
export interface MediaTransferProof {
  id: number;
  uploadedBy?: (number | null) | User;
  receivedAt?: string | null;
  ownerDocType?: string | null;
  ownerDocId?: string | null;
  sha256Original?: string | null;
  originalWidth?: number | null;
  originalHeight?: number | null;
  originalSize?: number | null;
  capturedAt?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-entries".
 */
export interface CashEntry {
  id: number;
  entryNo?: string | null;
  entryDate: string;
  period?: string | null;
  direction: 'in' | 'out';
  amount: number;
  cashAccount: number | CashAccount;
  category?: (number | null) | ExpenseCategory;
  cashInSource?: (number | null) | CashInSource;
  project?: (number | null) | Project;
  costCenter?: (number | null) | CostCenter;
  vehicle?: (number | null) | Vehicle;
  description?: string | null;
  proof?: (number | null) | MediaAttachment;
  sourceType: 'transfer' | 'settlement_refund' | 'manual' | 'reversal' | 'opening';
  expenseRequest?: (number | null) | ExpenseRequest;
  transfer?: (number | null) | Transfer;
  status: 'posted' | 'void';
  reversalOf?: (number | null) | CashEntry;
  reversedBy?: (number | null) | CashEntry;
  voidReason?: string | null;
  voidedBy?: (number | null) | User;
  voidedAt?: string | null;
  postedBy?: (number | null) | User;
  postedAt?: string | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settlements".
 */
export interface Settlement {
  id: number;
  docNo?: string | null;
  request: number | ExpenseRequest;
  status: 'draft' | 'submitted' | 'revision' | 'verified' | 'settled';
  usageNotes?: string | null;
  transferredTotal?: number | null;
  receiptsTotal?: number | null;
  verifiedReceiptsTotal?: number | null;
  difference?: number | null;
  settlementType?: ('none' | 'refund' | 'shortfall') | null;
  financeNotes?: string | null;
  submitCount?: number | null;
  submittedAt?: string | null;
  submittedBy?: (number | null) | User;
  verifiedAt?: string | null;
  verifiedBy?: (number | null) | User;
  settledAt?: string | null;
  settledBy?: (number | null) | User;
  refundCashEntry?: (number | null) | CashEntry;
  shortfallTransfer?: (number | null) | Transfer;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "period-closings".
 */
export interface PeriodClosing {
  id: number;
  period: string;
  status: 'closed' | 'reopened';
  note?: string | null;
  closedBy?: (number | null) | User;
  closedAt?: string | null;
  reopenedBy?: (number | null) | User;
  reopenedAt?: string | null;
  reopenReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendances".
 */
export interface Attendance {
  id: number;
  employee: number | Employee;
  user?: (number | null) | User;
  kind: 'check_in' | 'check_out';
  project?: (number | null) | Project;
  costCenter?: (number | null) | CostCenter;
  source: 'self' | 'pm';
  recordedBy?: (number | null) | User;
  onBehalfReason?: string | null;
  localDate: string;
  attendanceTime: string;
  receivedAt: string;
  deviceTime?: string | null;
  estimatedTime?: string | null;
  timeTrust: 'server' | 'estimated' | 'device_only';
  offline?: boolean | null;
  lat: number;
  lng: number;
  accuracyM?: number | null;
  distanceM: number;
  selfie: number | MediaSelfy;
  device?: (number | null) | Device;
  flags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  schedule?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  clientUuid: string;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices".
 */
export interface Device {
  id: number;
  deviceId: string;
  user: number | User;
  platform: 'android';
  model?: string | null;
  appVersion?: string | null;
  fcmToken?: string | null;
  keycloakSid?: string | null;
  status: 'active' | 'revoked' | 'lost';
  revokeReason?: string | null;
  /**
   * Root, emulator atau lokasi palsu terdeteksi pada pemeriksaan terakhir.
   */
  integrityRisk?: boolean | null;
  integrity?: {
    rooted?: boolean | null;
    emulator?: boolean | null;
    developerMode?: boolean | null;
    adbEnabled?: boolean | null;
    mockLocation?: boolean | null;
  };
  integrityCheckedAt?: string | null;
  registeredAt?: string | null;
  lastSeenAt?: string | null;
  revokedAt?: string | null;
  revokedBy?: (number | null) | User;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-corrections".
 */
export interface AttendanceCorrection {
  id: number;
  attendance: number | Attendance;
  employee: number | Employee;
  project?: (number | null) | Project;
  costCenter?: (number | null) | CostCenter;
  kind: 'check_in' | 'check_out';
  localDate: string;
  oldTime: string;
  newTime: string;
  reason: string;
  correctedBy: number | User;
  correctedAt: string;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Laporan dibuat dari aplikasi Android atau layar laporan progress (bukan dari form ini).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress-reports".
 */
export interface ProgressReport {
  id: number;
  docNo?: string | null;
  project: number | Project;
  stage: number | ProjectStage;
  reportDate: string;
  pctBefore: number;
  pctAfter: number;
  projectPctBefore?: number | null;
  projectPctAfter?: number | null;
  work: string;
  issues?: string | null;
  reporter: number | User;
  photoCount?: number | null;
  receivedAt?: string | null;
  editableUntil?: string | null;
  deviceTime?: string | null;
  timeTrust?: ('server' | 'estimated' | 'device_only') | null;
  offline?: boolean | null;
  source?: ('web' | 'apk') | null;
  flags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  syncRev?: number | null;
  clientUuid?: string | null;
  uuid?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  event: string;
  title: string;
  body: string;
  docType?: string | null;
  docId?: string | null;
  docNo?: string | null;
  readAt?: string | null;
  pushStatus: 'skipped' | 'pending' | 'sent' | 'failed';
  uuid?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-sessions".
 */
export interface WebSession {
  id: number;
  idHash: string;
  user: number | User;
  keycloakSid?: string | null;
  idTokenHint?: string | null;
  expiresAt: string;
  revokedAt?: string | null;
  revokeReason?: string | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  serverTime?: string | null;
  eventId: string;
  txId?: number | null;
  requestId?: string | null;
  docType: string;
  docId?: string | null;
  docNo?: string | null;
  action:
    | 'create'
    | 'update'
    | 'status_change'
    | 'deactivate'
    | 'reactivate'
    | 'delete_attempt'
    | 'void'
    | 'view_sensitive'
    | 'login'
    | 'logout'
    | 'login_failed'
    | 'session_revoked'
    | 'role_change'
    | 'role_sync'
    | 'device_register'
    | 'device_revoke'
    | 'number_issued'
    | 'export'
    | 'print'
    | 'sign'
    | 'acknowledge'
    | 'flag_raised'
    | 'flag_reviewed'
    | 'sync_odoo'
    | 'sync_offline'
    | 'period_close'
    | 'period_reopen'
    | 'schema_maintenance'
    | 'email_test'
    | 'approve'
    | 'reject'
    | 'verify'
    | 'acknowledge_delegated'
    | 'access_denied'
    | 'approval_skipped'
    | 'retention_purge';
  field?: string | null;
  lineNo?: number | null;
  oldValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  newValue?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  statusFrom?: string | null;
  statusTo?: string | null;
  reason?: string | null;
  userId?: number | null;
  userRoles?: string | null;
  source?: ('web' | 'apk' | 'system' | 'job') | null;
  appVersion?: string | null;
  ip?: string | null;
  deviceId?: string | null;
  lat?: number | null;
  lng?: number | null;
  deviceTime?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-progress-photos".
 */
export interface MediaProgressPhoto {
  id: number;
  uploadedBy?: (number | null) | User;
  receivedAt?: string | null;
  ownerDocType?: string | null;
  ownerDocId?: string | null;
  sha256Original?: string | null;
  originalWidth?: number | null;
  originalHeight?: number | null;
  originalSize?: number | null;
  capturedAt?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-company".
 */
export interface MediaCompany {
  id: number;
  uploadedBy?: (number | null) | User;
  receivedAt?: string | null;
  ownerDocType?: string | null;
  ownerDocId?: string | null;
  sha256Original?: string | null;
  originalWidth?: number | null;
  originalHeight?: number | null;
  originalSize?: number | null;
  capturedAt?: string | null;
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          'inline' | 'auditDailyAnchor' | 'sendEmail' | 'reimburseAutoClose' | 'selfieRetention' | 'dailyReminders';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    ('inline' | 'auditDailyAnchor' | 'sendEmail' | 'reimburseAutoClose' | 'selfieRetention' | 'dailyReminders') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'employees';
        value: number | Employee;
      } | null)
    | ({
        relationTo: 'employee-bank-accounts';
        value: number | EmployeeBankAccount;
      } | null)
    | ({
        relationTo: 'banks';
        value: number | Bank;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'vendors';
        value: number | Vendor;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'project-stages';
        value: number | ProjectStage;
      } | null)
    | ({
        relationTo: 'stage-templates';
        value: number | StageTemplate;
      } | null)
    | ({
        relationTo: 'budget-lines';
        value: number | BudgetLine;
      } | null)
    | ({
        relationTo: 'expense-categories';
        value: number | ExpenseCategory;
      } | null)
    | ({
        relationTo: 'cash-in-sources';
        value: number | CashInSource;
      } | null)
    | ({
        relationTo: 'cash-accounts';
        value: number | CashAccount;
      } | null)
    | ({
        relationTo: 'team-assignments';
        value: number | TeamAssignment;
      } | null)
    | ({
        relationTo: 'work-schedules';
        value: number | WorkSchedule;
      } | null)
    | ({
        relationTo: 'holidays';
        value: number | Holiday;
      } | null)
    | ({
        relationTo: 'approval-rules';
        value: number | ApprovalRule;
      } | null)
    | ({
        relationTo: 'notification-templates';
        value: number | NotificationTemplate;
      } | null)
    | ({
        relationTo: 'uoms';
        value: number | Uom;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'cost-centers';
        value: number | CostCenter;
      } | null)
    | ({
        relationTo: 'document-sequences';
        value: number | DocumentSequence;
      } | null)
    | ({
        relationTo: 'expense-requests';
        value: number | ExpenseRequest;
      } | null)
    | ({
        relationTo: 'receipts';
        value: number | Receipt;
      } | null)
    | ({
        relationTo: 'receipt-flags';
        value: number | ReceiptFlag;
      } | null)
    | ({
        relationTo: 'transfers';
        value: number | Transfer;
      } | null)
    | ({
        relationTo: 'settlements';
        value: number | Settlement;
      } | null)
    | ({
        relationTo: 'cash-entries';
        value: number | CashEntry;
      } | null)
    | ({
        relationTo: 'period-closings';
        value: number | PeriodClosing;
      } | null)
    | ({
        relationTo: 'attendances';
        value: number | Attendance;
      } | null)
    | ({
        relationTo: 'attendance-corrections';
        value: number | AttendanceCorrection;
      } | null)
    | ({
        relationTo: 'progress-reports';
        value: number | ProgressReport;
      } | null)
    | ({
        relationTo: 'budget-addenda';
        value: number | BudgetAddendum;
      } | null)
    | ({
        relationTo: 'devices';
        value: number | Device;
      } | null)
    | ({
        relationTo: 'media-receipts';
        value: number | MediaReceipt;
      } | null)
    | ({
        relationTo: 'media-transfer-proofs';
        value: number | MediaTransferProof;
      } | null)
    | ({
        relationTo: 'media-selfies';
        value: number | MediaSelfy;
      } | null)
    | ({
        relationTo: 'media-progress-photos';
        value: number | MediaProgressPhoto;
      } | null)
    | ({
        relationTo: 'media-signatures';
        value: number | MediaSignature;
      } | null)
    | ({
        relationTo: 'media-company';
        value: number | MediaCompany;
      } | null)
    | ({
        relationTo: 'media-attachments';
        value: number | MediaAttachment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  roles?: T;
  employee?: T;
  phone?: T;
  signature?: T;
  keycloakSub?: T;
  active?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees_select".
 */
export interface EmployeesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  nickname?: T;
  position?: T;
  phone?: T;
  workSchedule?: T;
  faceRefPhoto?: T;
  odooEmployeeRef?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employee-bank-accounts_select".
 */
export interface EmployeeBankAccountsSelect<T extends boolean = true> {
  employee?: T;
  bank?: T;
  accountNo?: T;
  accountHolder?: T;
  label?: T;
  isDefault?: T;
  verificationStatus?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banks_select".
 */
export interface BanksSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  phone?: T;
  address?: T;
  odooPartnerRef?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  npwp?: T;
  address?: T;
  odooPartnerRef?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  client?: T;
  address?: T;
  lat?: T;
  lng?: T;
  radiusM?: T;
  pm?: T;
  budget?: T;
  startDate?: T;
  targetDate?: T;
  status?: T;
  progressPct?: T;
  odooAnalyticRef?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-stages_select".
 */
export interface ProjectStagesSelect<T extends boolean = true> {
  project?: T;
  name?: T;
  weightPct?: T;
  sequence?: T;
  progressPct?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stage-templates_select".
 */
export interface StageTemplatesSelect<T extends boolean = true> {
  name?: T;
  items?:
    | T
    | {
        name?: T;
        weightPct?: T;
        sequence?: T;
        id?: T;
      };
  active?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget-lines_select".
 */
export interface BudgetLinesSelect<T extends boolean = true> {
  project?: T;
  category?: T;
  amount?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories_select".
 */
export interface ExpenseCategoriesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  coaCode?: T;
  defaultUom?: T;
  allowedUoms?: T;
  requiresVehicle?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-in-sources_select".
 */
export interface CashInSourcesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  coaCode?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-accounts_select".
 */
export interface CashAccountsSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  bank?: T;
  accountNo?: T;
  accountHolder?: T;
  openingBalance?: T;
  odooJournalCode?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-assignments_select".
 */
export interface TeamAssignmentsSelect<T extends boolean = true> {
  employee?: T;
  project?: T;
  costCenter?: T;
  roleInProject?: T;
  startDate?: T;
  endDate?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-schedules_select".
 */
export interface WorkSchedulesSelect<T extends boolean = true> {
  name?: T;
  startTime?: T;
  endTime?: T;
  lateToleranceMin?: T;
  workDays?:
    | T
    | {
        mon?: T;
        tue?: T;
        wed?: T;
        thu?: T;
        fri?: T;
        sat?: T;
        sun?: T;
      };
  active?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "holidays_select".
 */
export interface HolidaysSelect<T extends boolean = true> {
  date?: T;
  name?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approval-rules_select".
 */
export interface ApprovalRulesSelect<T extends boolean = true> {
  name?: T;
  docType?: T;
  requestType?: T;
  minAmount?: T;
  maxAmount?: T;
  category?: T;
  project?: T;
  costCenter?: T;
  priority?: T;
  acknowledge?: T;
  acknowledgeBy?: T;
  acknowledgeRole?: T;
  acknowledgeUser?: T;
  signDiajukan?: T;
  signDibuat?: T;
  steps?:
    | T
    | {
        level?: T;
        approverRole?: T;
        approverUser?: T;
        id?: T;
      };
  active?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-templates_select".
 */
export interface NotificationTemplatesSelect<T extends boolean = true> {
  event?: T;
  title?: T;
  body?: T;
  channel?: T;
  active?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uoms_select".
 */
export interface UomsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  category?: T;
  odooUomRef?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  plateNo?: T;
  plateDisplay?: T;
  type?: T;
  brandModel?: T;
  costCenter?: T;
  project?: T;
  odooFleetRef?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cost-centers_select".
 */
export interface CostCentersSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  type?: T;
  manager?: T;
  lat?: T;
  lng?: T;
  radiusM?: T;
  odooAnalyticRef?: T;
  active?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-sequences_select".
 */
export interface DocumentSequencesSelect<T extends boolean = true> {
  docType?: T;
  docCode?: T;
  pattern?: T;
  resetPolicy?: T;
  padding?: T;
  startAt?: T;
  timezone?: T;
  active?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-requests_select".
 */
export interface ExpenseRequestsSelect<T extends boolean = true> {
  docNo?: T;
  type?: T;
  status?: T;
  title?: T;
  project?: T;
  costCenter?: T;
  requestDate?: T;
  neededDate?: T;
  periodFrom?: T;
  periodTo?: T;
  notes?: T;
  requesters?: T;
  createdBy?: T;
  bankAccount?: T;
  bankSnapshot?:
    | T
    | {
        bankName?: T;
        accountNo?: T;
        accountHolder?: T;
      };
  lines?:
    | T
    | {
        description?: T;
        qty?: T;
        uom?: T;
        unitPrice?: T;
        total?: T;
        category?: T;
        vehicle?: T;
        notes?: T;
        id?: T;
      };
  grandTotal?: T;
  approvedAmount?: T;
  transferredTotal?: T;
  verifiedReceiptsTotal?: T;
  attachments?: T;
  approvalRule?: T;
  approvalSnapshot?: T;
  approvalCycle?: T;
  currentLevel?: T;
  submittedAt?: T;
  contentHash?: T;
  resubmitOf?: T;
  cancelReason?: T;
  rejectReason?: T;
  syncRev?: T;
  clientUuid?: T;
  source?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-line-snapshots_select".
 */
export interface ExpenseLineSnapshotsSelect<T extends boolean = true> {
  request?: T;
  cycle?: T;
  reason?: T;
  grandTotal?: T;
  contentHash?: T;
  data?: T;
  takenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "approvals_select".
 */
export interface ApprovalsSelect<T extends boolean = true> {
  docType?: T;
  request?: T;
  addendum?: T;
  cycle?: T;
  position?: T;
  level?: T;
  actor?: T;
  employee?: T;
  actorName?: T;
  onBehalf?: T;
  decision?: T;
  reason?: T;
  decidedAt?: T;
  budgetPctBefore?: T;
  budgetPctAfter?: T;
  openFlags?: T;
  signature?: T;
  signatureSha256?: T;
  signatureSource?: T;
  deviceId?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipts_select".
 */
export interface ReceiptsSelect<T extends boolean = true> {
  request?: T;
  lineId?: T;
  lineNo?: T;
  receiptNo?: T;
  receiptNoNorm?: T;
  vendor?: T;
  vendorName?: T;
  vendorNorm?: T;
  receiptDate?: T;
  receiptTime?: T;
  amount?: T;
  taxAmount?: T;
  image?: T;
  imageSha256?: T;
  status?: T;
  rejectReason?: T;
  removeReason?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  entrySource?: T;
  createdBy?: T;
  clientUuid?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "receipt-flags_select".
 */
export interface ReceiptFlagsSelect<T extends boolean = true> {
  request?: T;
  key?: T;
  kind?: T;
  level?: T;
  lineId?: T;
  lineNo?: T;
  receipt?: T;
  relatedRequest?: T;
  message?: T;
  detail?: T;
  status?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  reviewNote?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transfers_select".
 */
export interface TransfersSelect<T extends boolean = true> {
  docNo?: T;
  request?: T;
  kind?: T;
  cashAccount?: T;
  amount?: T;
  destination?:
    | T
    | {
        bankName?: T;
        accountNo?: T;
        accountHolder?: T;
      };
  bankRef?: T;
  proof?: T;
  transferDate?: T;
  postedBy?: T;
  status?: T;
  cashEntry?: T;
  voidReason?: T;
  voidedBy?: T;
  voidedAt?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settlements_select".
 */
export interface SettlementsSelect<T extends boolean = true> {
  docNo?: T;
  request?: T;
  status?: T;
  usageNotes?: T;
  transferredTotal?: T;
  receiptsTotal?: T;
  verifiedReceiptsTotal?: T;
  difference?: T;
  settlementType?: T;
  financeNotes?: T;
  submitCount?: T;
  submittedAt?: T;
  submittedBy?: T;
  verifiedAt?: T;
  verifiedBy?: T;
  settledAt?: T;
  settledBy?: T;
  refundCashEntry?: T;
  shortfallTransfer?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cash-entries_select".
 */
export interface CashEntriesSelect<T extends boolean = true> {
  entryNo?: T;
  entryDate?: T;
  period?: T;
  direction?: T;
  amount?: T;
  cashAccount?: T;
  category?: T;
  cashInSource?: T;
  project?: T;
  costCenter?: T;
  vehicle?: T;
  description?: T;
  proof?: T;
  sourceType?: T;
  expenseRequest?: T;
  transfer?: T;
  status?: T;
  reversalOf?: T;
  reversedBy?: T;
  voidReason?: T;
  voidedBy?: T;
  voidedAt?: T;
  postedBy?: T;
  postedAt?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "period-closings_select".
 */
export interface PeriodClosingsSelect<T extends boolean = true> {
  period?: T;
  status?: T;
  note?: T;
  closedBy?: T;
  closedAt?: T;
  reopenedBy?: T;
  reopenedAt?: T;
  reopenReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendances_select".
 */
export interface AttendancesSelect<T extends boolean = true> {
  employee?: T;
  user?: T;
  kind?: T;
  project?: T;
  costCenter?: T;
  source?: T;
  recordedBy?: T;
  onBehalfReason?: T;
  localDate?: T;
  attendanceTime?: T;
  receivedAt?: T;
  deviceTime?: T;
  estimatedTime?: T;
  timeTrust?: T;
  offline?: T;
  lat?: T;
  lng?: T;
  accuracyM?: T;
  distanceM?: T;
  selfie?: T;
  device?: T;
  flags?: T;
  schedule?: T;
  clientUuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-corrections_select".
 */
export interface AttendanceCorrectionsSelect<T extends boolean = true> {
  attendance?: T;
  employee?: T;
  project?: T;
  costCenter?: T;
  kind?: T;
  localDate?: T;
  oldTime?: T;
  newTime?: T;
  reason?: T;
  correctedBy?: T;
  correctedAt?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress-reports_select".
 */
export interface ProgressReportsSelect<T extends boolean = true> {
  docNo?: T;
  project?: T;
  stage?: T;
  reportDate?: T;
  pctBefore?: T;
  pctAfter?: T;
  projectPctBefore?: T;
  projectPctAfter?: T;
  work?: T;
  issues?: T;
  reporter?: T;
  photoCount?: T;
  receivedAt?: T;
  editableUntil?: T;
  deviceTime?: T;
  timeTrust?: T;
  offline?: T;
  source?: T;
  flags?: T;
  syncRev?: T;
  clientUuid?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "budget-addenda_select".
 */
export interface BudgetAddendaSelect<T extends boolean = true> {
  docNo?: T;
  project?: T;
  status?: T;
  addition?: T;
  reason?: T;
  budgetAtSubmit?: T;
  oldBudget?: T;
  newBudget?: T;
  createdBy?: T;
  submittedAt?: T;
  decidedAt?: T;
  approvalRule?: T;
  approvalSnapshot?: T;
  approvalCycle?: T;
  currentLevel?: T;
  rejectReason?: T;
  cancelReason?: T;
  source?: T;
  uuid?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  event?: T;
  title?: T;
  body?: T;
  docType?: T;
  docId?: T;
  docNo?: T;
  readAt?: T;
  pushStatus?: T;
  uuid?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "devices_select".
 */
export interface DevicesSelect<T extends boolean = true> {
  deviceId?: T;
  user?: T;
  platform?: T;
  model?: T;
  appVersion?: T;
  fcmToken?: T;
  keycloakSid?: T;
  status?: T;
  revokeReason?: T;
  integrityRisk?: T;
  integrity?:
    | T
    | {
        rooted?: T;
        emulator?: T;
        developerMode?: T;
        adbEnabled?: T;
        mockLocation?: T;
      };
  integrityCheckedAt?: T;
  registeredAt?: T;
  lastSeenAt?: T;
  revokedAt?: T;
  revokedBy?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "web-sessions_select".
 */
export interface WebSessionsSelect<T extends boolean = true> {
  idHash?: T;
  user?: T;
  keycloakSid?: T;
  idTokenHint?: T;
  expiresAt?: T;
  revokedAt?: T;
  revokeReason?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  serverTime?: T;
  eventId?: T;
  txId?: T;
  requestId?: T;
  docType?: T;
  docId?: T;
  docNo?: T;
  action?: T;
  field?: T;
  lineNo?: T;
  oldValue?: T;
  newValue?: T;
  statusFrom?: T;
  statusTo?: T;
  reason?: T;
  userId?: T;
  userRoles?: T;
  source?: T;
  appVersion?: T;
  ip?: T;
  deviceId?: T;
  lat?: T;
  lng?: T;
  deviceTime?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-receipts_select".
 */
export interface MediaReceiptsSelect<T extends boolean = true> {
  uploadedBy?: T;
  receivedAt?: T;
  ownerDocType?: T;
  ownerDocId?: T;
  sha256Original?: T;
  originalWidth?: T;
  originalHeight?: T;
  originalSize?: T;
  capturedAt?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-transfer-proofs_select".
 */
export interface MediaTransferProofsSelect<T extends boolean = true> {
  uploadedBy?: T;
  receivedAt?: T;
  ownerDocType?: T;
  ownerDocId?: T;
  sha256Original?: T;
  originalWidth?: T;
  originalHeight?: T;
  originalSize?: T;
  capturedAt?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-selfies_select".
 */
export interface MediaSelfiesSelect<T extends boolean = true> {
  uploadedBy?: T;
  receivedAt?: T;
  ownerDocType?: T;
  ownerDocId?: T;
  sha256Original?: T;
  originalWidth?: T;
  originalHeight?: T;
  originalSize?: T;
  capturedAt?: T;
  removedAt?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-progress-photos_select".
 */
export interface MediaProgressPhotosSelect<T extends boolean = true> {
  uploadedBy?: T;
  receivedAt?: T;
  ownerDocType?: T;
  ownerDocId?: T;
  sha256Original?: T;
  originalWidth?: T;
  originalHeight?: T;
  originalSize?: T;
  capturedAt?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-signatures_select".
 */
export interface MediaSignaturesSelect<T extends boolean = true> {
  uploadedBy?: T;
  receivedAt?: T;
  ownerDocType?: T;
  ownerDocId?: T;
  sha256Original?: T;
  originalWidth?: T;
  originalHeight?: T;
  originalSize?: T;
  capturedAt?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-company_select".
 */
export interface MediaCompanySelect<T extends boolean = true> {
  uploadedBy?: T;
  receivedAt?: T;
  ownerDocType?: T;
  ownerDocId?: T;
  sha256Original?: T;
  originalWidth?: T;
  originalHeight?: T;
  originalSize?: T;
  capturedAt?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-attachments_select".
 */
export interface MediaAttachmentsSelect<T extends boolean = true> {
  uploadedBy?: T;
  receivedAt?: T;
  ownerDocType?: T;
  ownerDocId?: T;
  sha256Original?: T;
  originalWidth?: T;
  originalHeight?: T;
  originalSize?: T;
  capturedAt?: T;
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings".
 */
export interface CompanySetting {
  id: number;
  name: string;
  shortCode: string;
  logo?: (number | null) | MediaCompany;
  pdfHeader?: string | null;
  address?: string | null;
  phone?: string | null;
  /**
   * Proses server memakai env TZ (cron, tanggal bisnis); ubah keduanya bersamaan.
   */
  timezone: string;
  defaultGeofenceRadiusM: number;
  lateReportDays: number;
  budgetWarnPct: number;
  budgetOverPct: number;
  progressWarnGapPct: number;
  progressBadGapPct: number;
  receiptRoundingTolerance: number;
  receiptMaxAgeDays: number;
  reimburseAutoCloseDays: number;
  /**
   * Uang muka tanpa LPJ lebih lama dari ini tampil sebagai "LPJ terlambat" di dashboard/laporan.
   */
  lpjDueDays: number;
  minAppVersion?: string | null;
  latestAppVersion?: string | null;
  /**
   * https://… (APK side-load). Kosong = aplikasi menampilkan "hubungi admin".
   */
  appDownloadUrl?: string | null;
  /**
   * Nonaktif → item offline ditolak FEATURE_DISABLED (ADR 0010 rollback).
   */
  syncExpenseDraftsEnabled?: boolean | null;
  /**
   * Absen masuk/pulang sendiri di project/pusat biaya yang ditugaskan (geofence, selfie, lokasi palsu ditolak) dan "diabsenkan PM". Nonaktif → item absensi ditolak FEATURE_DISABLED. Nyalakan di prod setelah checklist go-live.
   */
  syncAttendanceEnabled?: boolean | null;
  /**
   * Dipakai untuk karyawan tanpa jadwal sendiri. Kosong = keterlambatan tidak dihitung.
   */
  defaultWorkSchedule?: (number | null) | WorkSchedule;
  /**
   * Selfie lebih tua dari ini dihapus dari penyimpanan saat penghapusan otomatis aktif (data absensi tetap). Default 12 bulan; menunggu keputusan klien (Q-33).
   */
  selfieRetentionMonths: number;
  /**
   * Nonaktif = job hanya menghitung (dry run). Aktif = file selfie dihapus permanen setiap malam (02:30), tercatat di audit log.
   */
  selfieRetentionDeleteEnabled?: boolean | null;
  selfieRetentionBatch: number;
  /**
   * E4: laporan progress harian + foto dari APK. Nonaktif → item laporan ditolak FEATURE_DISABLED (rollback).
   */
  syncProgressReportsEnabled?: boolean | null;
  /**
   * Nonaktif = job pengingat tidak mengirim apa pun (rollback).
   */
  remindersEnabled?: boolean | null;
  reminderHour: number;
  /**
   * Selain notifikasi in-app. Batas SMTP 30 email/jam per mailbox — aktifkan setelah alamat email pengguna benar.
   */
  reminderEmailEnabled?: boolean | null;
  /**
   * Batas hari = "Batas hari laporan progress terlambat".
   */
  reminderLateProgressEnabled?: boolean | null;
  /**
   * Batas hari = "Batas LPJ uang muka".
   */
  reminderLpjOverdueEnabled?: boolean | null;
  reminderRevisionEnabled?: boolean | null;
  reminderRevisionDays: number;
  /**
   * Ambang = "Ambang anggaran kuning" dan "merah" di atas; sekali per ambang per project.
   */
  reminderBudgetEnabled?: boolean | null;
  offlineMaxAgeDays: number;
  imageTargets: {
    receiptsMaxPx: number;
    selfiesMaxPx: number;
    transferProofsMaxPx: number;
    progressPhotosMaxPx: number;
    jpegQuality: number;
  };
  /**
   * Wajib saat menonaktifkan data atau mengubah data yang dilindungi. Dicatat di audit log.
   */
  changeReason?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-settings_select".
 */
export interface CompanySettingsSelect<T extends boolean = true> {
  name?: T;
  shortCode?: T;
  logo?: T;
  pdfHeader?: T;
  address?: T;
  phone?: T;
  timezone?: T;
  defaultGeofenceRadiusM?: T;
  lateReportDays?: T;
  budgetWarnPct?: T;
  budgetOverPct?: T;
  progressWarnGapPct?: T;
  progressBadGapPct?: T;
  receiptRoundingTolerance?: T;
  receiptMaxAgeDays?: T;
  reimburseAutoCloseDays?: T;
  lpjDueDays?: T;
  minAppVersion?: T;
  latestAppVersion?: T;
  appDownloadUrl?: T;
  syncExpenseDraftsEnabled?: T;
  syncAttendanceEnabled?: T;
  defaultWorkSchedule?: T;
  selfieRetentionMonths?: T;
  selfieRetentionDeleteEnabled?: T;
  selfieRetentionBatch?: T;
  syncProgressReportsEnabled?: T;
  remindersEnabled?: T;
  reminderHour?: T;
  reminderEmailEnabled?: T;
  reminderLateProgressEnabled?: T;
  reminderLpjOverdueEnabled?: T;
  reminderRevisionEnabled?: T;
  reminderRevisionDays?: T;
  reminderBudgetEnabled?: T;
  offlineMaxAgeDays?: T;
  imageTargets?:
    | T
    | {
        receiptsMaxPx?: T;
        selfiesMaxPx?: T;
        transferProofsMaxPx?: T;
        progressPhotosMaxPx?: T;
        jpegQuality?: T;
      };
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAuditDailyAnchor".
 */
export interface TaskAuditDailyAnchor {
  input?: unknown;
  output: {
    day: string;
    rows: number;
    maxId: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendEmail".
 */
export interface TaskSendEmail {
  input: {
    userId: number;
    subject: string;
    text: string;
  };
  output: {
    messageId?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskReimburseAutoClose".
 */
export interface TaskReimburseAutoClose {
  input?: unknown;
  output: {
    closed: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSelfieRetention".
 */
export interface TaskSelfieRetention {
  input?: unknown;
  output: {
    months: number;
    cutoff: string;
    candidates: number;
    deleted: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDailyReminders".
 */
export interface TaskDailyReminders {
  input?: unknown;
  output: {
    status: string;
    date: string;
    notified: number;
    emails: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}