import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/**
 * S3 track A — E9 hardening (plan fase1-golive §E9): settlement reversal.
 * Generated by `payload migrate:create s3a_e9_hardening` (reviewed) + hand-written guard changes
 * (one migration, run as <prefix>_owner). ADDITIVE / staging-safe: four new columns on `settlements`
 * (`reversal_count` default 0, nullable `last_reversed_at`, `last_reversed_by_id`, `last_reversal_reason`),
 * no existing row rewritten.
 *
 * Guards (defence in depth behind domain/expense/lpj.ts reverseSettlement):
 * 1. `pk_settlements_guard` (CREATE OR REPLACE, F2b body extended): a settled LPJ stays immutable
 *    EXCEPT the reversal settled → verified, allowed only when the settlement moved money (refund /
 *    shortfall), after its KM / transfer is void, clearing settled_at/by and the refund/shortfall link,
 *    with reversal_count + 1, actor, time and reason (≥ 3 chars). New rows start with no reversal data;
 *    the reversal columns change only in that transition.
 * 2. `settlements_protect` is re-created WITHOUT `refund_cash_entry_id` / `shortfall_transfer_id`
 *    (a reversal must clear them); the guard now enforces "set once per settlement cycle"
 *    (verified → settled only from NULL links). `doc_no`, `request_id`, `uuid` stay immutable.
 * Period close: unchanged DB rule — the reversal row of the KM/KK is an INSERT into cash_entries and
 * the closed-period insert guard applies; the service refuses earlier with a clear 409.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    DO $pk$
    BEGIN
      IF current_user !~ '_owner$' THEN
        RAISE EXCEPTION 'migrations must run as the <prefix>_owner role (current_user=%)', current_user;
      END IF;
    END
    $pk$;

   ALTER TABLE "settlements" ADD COLUMN "reversal_count" numeric DEFAULT 0;
  ALTER TABLE "settlements" ADD COLUMN "last_reversed_at" timestamp(3) with time zone;
  ALTER TABLE "settlements" ADD COLUMN "last_reversed_by_id" integer;
  ALTER TABLE "settlements" ADD COLUMN "last_reversal_reason" varchar;
  ALTER TABLE "settlements" ADD CONSTRAINT "settlements_last_reversed_by_id_users_id_fk" FOREIGN KEY ("last_reversed_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "settlements_last_reversed_by_idx" ON "settlements" USING btree ("last_reversed_by_id");

    CREATE OR REPLACE FUNCTION pk_settlements_guard() RETURNS trigger LANGUAGE plpgsql AS $fn$
    DECLARE
      r record;
      o jsonb;
      n jsonb;
      submit_cols text[] := ARRAY['usage_notes', 'transferred_total', 'receipts_total', 'difference', 'submit_count',
                                  'submitted_at', 'submitted_by_id', 'doc_no'];
      verify_cols text[] := ARRAY['transferred_total', 'verified_receipts_total', 'difference', 'settlement_type',
                                  'verified_at', 'verified_by_id'];
      settle_cols text[] := ARRAY['settled_at', 'settled_by_id', 'refund_cash_entry_id', 'shortfall_transfer_id'];
      reverse_cols text[] := ARRAY['reversal_count', 'last_reversed_at', 'last_reversed_by_id', 'last_reversal_reason'];
      always text[] := ARRAY['status', 'updated_at'];
      allowed text[];
      reversing boolean;
      ce record;
      tr record;
    BEGIN
      SELECT type::text AS type, status::text AS status INTO r FROM expense_requests WHERE id = NEW.request_id;
      IF TG_OP = 'INSERT' THEN
        IF r.type IS DISTINCT FROM 'advance' THEN
          RAISE EXCEPTION 'settlements: LPJ exists only for Uang Muka (request %)', NEW.request_id USING ERRCODE = '42501';
        END IF;
        IF NEW.status <> 'draft' OR NEW.doc_no IS NOT NULL OR NEW.settled_at IS NOT NULL OR NEW.verified_at IS NOT NULL
           OR NEW.refund_cash_entry_id IS NOT NULL OR NEW.shortfall_transfer_id IS NOT NULL
           OR coalesce(NEW.reversal_count, 0) <> 0 OR NEW.last_reversed_at IS NOT NULL OR NEW.last_reversed_by_id IS NOT NULL
           OR NEW.last_reversal_reason IS NOT NULL THEN
          RAISE EXCEPTION 'settlements: new LPJ rows are drafts' USING ERRCODE = '42501';
        END IF;
        RETURN NEW;
      END IF;

      o := to_jsonb(OLD);
      n := to_jsonb(NEW);
      -- E9: the ONLY change of a settled row is the reversal settled → verified (Finance, reason).
      reversing := OLD.status = 'settled' AND NEW.status = 'verified';
      IF OLD.status = 'settled' AND NOT reversing AND (o - 'updated_at') IS DISTINCT FROM (n - 'updated_at') THEN
        RAISE EXCEPTION 'settlements %: settled LPJ is immutable', OLD.id USING ERRCODE = '42501';
      END IF;
      IF NEW.status IS DISTINCT FROM OLD.status AND NOT (
           (OLD.status = 'draft' AND NEW.status = 'submitted') OR (OLD.status = 'submitted' AND NEW.status IN ('revision', 'verified'))
           OR (OLD.status = 'revision' AND NEW.status = 'submitted') OR (OLD.status = 'verified' AND NEW.status = 'settled')
           OR reversing) THEN
        RAISE EXCEPTION 'settlements %: status % → % not allowed', OLD.id, OLD.status, NEW.status USING ERRCODE = '42501';
      END IF;
      allowed := always;
      IF NEW.status = 'submitted' AND OLD.status IN ('draft', 'revision') THEN allowed := allowed || submit_cols; END IF;
      IF NEW.status = 'revision' AND OLD.status = 'submitted' THEN allowed := allowed || ARRAY['finance_notes']; END IF;
      IF NEW.status = 'verified' AND OLD.status = 'submitted' THEN allowed := allowed || verify_cols; END IF;
      IF NEW.status = 'settled' AND OLD.status = 'verified' THEN allowed := allowed || settle_cols; END IF;
      IF reversing THEN allowed := allowed || settle_cols || reverse_cols; END IF;
      IF (o - allowed) IS DISTINCT FROM (n - allowed) THEN
        RAISE EXCEPTION 'settlements %: columns outside the % transition cannot change', OLD.id, NEW.status USING ERRCODE = '42501';
      END IF;

      IF NEW.status = 'verified' AND OLD.status = 'submitted' THEN
        IF NEW.verified_receipts_total IS NULL OR NEW.transferred_total IS NULL
           OR NEW.difference IS DISTINCT FROM NEW.transferred_total - NEW.verified_receipts_total
           OR NEW.settlement_type IS DISTINCT FROM (CASE WHEN NEW.difference > 0 THEN 'refund' WHEN NEW.difference < 0 THEN 'shortfall' ELSE 'none' END)::enum_settlements_settlement_type THEN
          RAISE EXCEPTION 'settlements %: verified totals are inconsistent', OLD.id USING ERRCODE = '23514';
        END IF;
      END IF;

      IF NEW.status = 'settled' AND OLD.status = 'verified' THEN
        -- links are set once per settlement cycle (a reversal clears them; replaces pk_protect_columns)
        IF OLD.refund_cash_entry_id IS NOT NULL OR OLD.shortfall_transfer_id IS NOT NULL THEN
          RAISE EXCEPTION 'settlements %: settlement links are set once per settlement', OLD.id USING ERRCODE = '42501';
        END IF;
        IF NEW.settlement_type = 'none' THEN
          IF NEW.difference <> 0 OR NEW.refund_cash_entry_id IS NOT NULL OR NEW.shortfall_transfer_id IS NOT NULL THEN
            RAISE EXCEPTION 'settlements %: nothing to settle expected', OLD.id USING ERRCODE = '23514';
          END IF;
        ELSIF NEW.settlement_type = 'refund' THEN
          SELECT direction::text AS direction, amount, source_type::text AS source_type, expense_request_id, status::text AS status
            INTO ce FROM cash_entries WHERE id = NEW.refund_cash_entry_id;
          IF NOT FOUND OR NEW.shortfall_transfer_id IS NOT NULL OR ce.direction <> 'in' OR ce.source_type <> 'settlement_refund'
             OR ce.status <> 'posted' OR ce.expense_request_id IS DISTINCT FROM NEW.request_id OR ce.amount <> NEW.difference THEN
            RAISE EXCEPTION 'settlements %: refund must be a posted KM of exactly the surplus', OLD.id USING ERRCODE = '23514';
          END IF;
        ELSE
          SELECT kind::text AS kind, amount, request_id, status::text AS status INTO tr FROM transfers WHERE id = NEW.shortfall_transfer_id;
          IF NOT FOUND OR NEW.refund_cash_entry_id IS NOT NULL OR tr.kind <> 'lpj_shortfall' OR tr.status <> 'posted'
             OR tr.request_id IS DISTINCT FROM NEW.request_id OR tr.amount <> -NEW.difference THEN
            RAISE EXCEPTION 'settlements %: shortfall must be a posted transfer of exactly the shortfall', OLD.id USING ERRCODE = '23514';
          END IF;
        END IF;
      END IF;

      IF reversing THEN
        -- E9: only a settlement that moved money; its KM / transfer must already be void; links and
        -- settle stamps cleared; reversal counter +1 with actor, time and reason.
        IF OLD.settlement_type NOT IN ('refund', 'shortfall') THEN
          RAISE EXCEPTION 'settlements %: nothing to reverse (settlement type %)', OLD.id, OLD.settlement_type USING ERRCODE = '42501';
        END IF;
        IF NEW.settled_at IS NOT NULL OR NEW.settled_by_id IS NOT NULL OR NEW.refund_cash_entry_id IS NOT NULL OR NEW.shortfall_transfer_id IS NOT NULL
           OR NEW.reversal_count IS DISTINCT FROM coalesce(OLD.reversal_count, 0) + 1 OR NEW.last_reversed_at IS NULL
           OR NEW.last_reversed_by_id IS NULL OR length(coalesce(NEW.last_reversal_reason, '')) < 3 THEN
          RAISE EXCEPTION 'settlements %: reversal must clear the settlement and record count, actor and reason', OLD.id USING ERRCODE = '23514';
        END IF;
        IF OLD.settlement_type = 'refund' AND NOT EXISTS (SELECT 1 FROM cash_entries WHERE id = OLD.refund_cash_entry_id AND status = 'void') THEN
          RAISE EXCEPTION 'settlements %: reverse only after the refund KM is void', OLD.id USING ERRCODE = '23514';
        END IF;
        IF OLD.settlement_type = 'shortfall' AND NOT EXISTS (SELECT 1 FROM transfers WHERE id = OLD.shortfall_transfer_id AND status = 'void') THEN
          RAISE EXCEPTION 'settlements %: reverse only after the shortfall transfer is void', OLD.id USING ERRCODE = '23514';
        END IF;
      END IF;
      RETURN NEW;
    END
    $fn$;

    DROP TRIGGER IF EXISTS settlements_protect ON settlements;
    CREATE TRIGGER settlements_protect BEFORE UPDATE ON settlements
      FOR EACH ROW EXECUTE FUNCTION pk_protect_columns('doc_no', 'request_id', 'uuid');
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  // Restores the F2b guard (copied verbatim from 20260923_161854_f2b_security.ts) and the protect
  // trigger, then drops the columns. Refused while a reversed LPJ exists (history would be lost).
  await db.execute(sql`
    DO $pk$
    BEGIN
      IF EXISTS (SELECT 1 FROM settlements WHERE coalesce(reversal_count, 0) > 0) THEN
        RAISE EXCEPTION 's3a_e9_hardening down: reversed settlements exist; not rolling back';
      END IF;
    END
    $pk$;
    CREATE OR REPLACE FUNCTION pk_settlements_guard() RETURNS trigger LANGUAGE plpgsql AS $fn$
    DECLARE
      r record;
      o jsonb;
      n jsonb;
      submit_cols text[] := ARRAY['usage_notes', 'transferred_total', 'receipts_total', 'difference', 'submit_count',
                                  'submitted_at', 'submitted_by_id', 'doc_no'];
      verify_cols text[] := ARRAY['transferred_total', 'verified_receipts_total', 'difference', 'settlement_type',
                                  'verified_at', 'verified_by_id'];
      settle_cols text[] := ARRAY['settled_at', 'settled_by_id', 'refund_cash_entry_id', 'shortfall_transfer_id'];
      always text[] := ARRAY['status', 'updated_at'];
      allowed text[];
      ce record;
      tr record;
    BEGIN
      SELECT type::text AS type, status::text AS status INTO r FROM expense_requests WHERE id = NEW.request_id;
      IF TG_OP = 'INSERT' THEN
        IF r.type IS DISTINCT FROM 'advance' THEN
          RAISE EXCEPTION 'settlements: LPJ exists only for Uang Muka (request %)', NEW.request_id USING ERRCODE = '42501';
        END IF;
        IF NEW.status <> 'draft' OR NEW.doc_no IS NOT NULL OR NEW.settled_at IS NOT NULL OR NEW.verified_at IS NOT NULL
           OR NEW.refund_cash_entry_id IS NOT NULL OR NEW.shortfall_transfer_id IS NOT NULL THEN
          RAISE EXCEPTION 'settlements: new LPJ rows are drafts' USING ERRCODE = '42501';
        END IF;
        RETURN NEW;
      END IF;

      o := to_jsonb(OLD);
      n := to_jsonb(NEW);
      IF OLD.status = 'settled' AND (o - 'updated_at') IS DISTINCT FROM (n - 'updated_at') THEN
        RAISE EXCEPTION 'settlements %: settled LPJ is immutable', OLD.id USING ERRCODE = '42501';
      END IF;
      IF NEW.status IS DISTINCT FROM OLD.status AND NOT (
           (OLD.status = 'draft' AND NEW.status = 'submitted') OR (OLD.status = 'submitted' AND NEW.status IN ('revision', 'verified'))
           OR (OLD.status = 'revision' AND NEW.status = 'submitted') OR (OLD.status = 'verified' AND NEW.status = 'settled')) THEN
        RAISE EXCEPTION 'settlements %: status % → % not allowed', OLD.id, OLD.status, NEW.status USING ERRCODE = '42501';
      END IF;
      allowed := always;
      IF NEW.status = 'submitted' AND OLD.status IN ('draft', 'revision') THEN allowed := allowed || submit_cols; END IF;
      IF NEW.status = 'revision' AND OLD.status = 'submitted' THEN allowed := allowed || ARRAY['finance_notes']; END IF;
      IF NEW.status = 'verified' AND OLD.status = 'submitted' THEN allowed := allowed || verify_cols; END IF;
      IF NEW.status = 'settled' AND OLD.status = 'verified' THEN allowed := allowed || settle_cols; END IF;
      IF (o - allowed) IS DISTINCT FROM (n - allowed) THEN
        RAISE EXCEPTION 'settlements %: columns outside the % transition cannot change', OLD.id, NEW.status USING ERRCODE = '42501';
      END IF;

      IF NEW.status = 'verified' AND OLD.status = 'submitted' THEN
        IF NEW.verified_receipts_total IS NULL OR NEW.transferred_total IS NULL
           OR NEW.difference IS DISTINCT FROM NEW.transferred_total - NEW.verified_receipts_total
           OR NEW.settlement_type IS DISTINCT FROM (CASE WHEN NEW.difference > 0 THEN 'refund' WHEN NEW.difference < 0 THEN 'shortfall' ELSE 'none' END)::enum_settlements_settlement_type THEN
          RAISE EXCEPTION 'settlements %: verified totals are inconsistent', OLD.id USING ERRCODE = '23514';
        END IF;
      END IF;

      IF NEW.status = 'settled' AND OLD.status = 'verified' THEN
        IF NEW.settlement_type = 'none' THEN
          IF NEW.difference <> 0 OR NEW.refund_cash_entry_id IS NOT NULL OR NEW.shortfall_transfer_id IS NOT NULL THEN
            RAISE EXCEPTION 'settlements %: nothing to settle expected', OLD.id USING ERRCODE = '23514';
          END IF;
        ELSIF NEW.settlement_type = 'refund' THEN
          SELECT direction::text AS direction, amount, source_type::text AS source_type, expense_request_id, status::text AS status
            INTO ce FROM cash_entries WHERE id = NEW.refund_cash_entry_id;
          IF NOT FOUND OR NEW.shortfall_transfer_id IS NOT NULL OR ce.direction <> 'in' OR ce.source_type <> 'settlement_refund'
             OR ce.status <> 'posted' OR ce.expense_request_id IS DISTINCT FROM NEW.request_id OR ce.amount <> NEW.difference THEN
            RAISE EXCEPTION 'settlements %: refund must be a posted KM of exactly the surplus', OLD.id USING ERRCODE = '23514';
          END IF;
        ELSE
          SELECT kind::text AS kind, amount, request_id, status::text AS status INTO tr FROM transfers WHERE id = NEW.shortfall_transfer_id;
          IF NOT FOUND OR NEW.refund_cash_entry_id IS NOT NULL OR tr.kind <> 'lpj_shortfall' OR tr.status <> 'posted'
             OR tr.request_id IS DISTINCT FROM NEW.request_id OR tr.amount <> -NEW.difference THEN
            RAISE EXCEPTION 'settlements %: shortfall must be a posted transfer of exactly the shortfall', OLD.id USING ERRCODE = '23514';
          END IF;
        END IF;
      END IF;
      RETURN NEW;
    END
    $fn$;
    DROP TRIGGER IF EXISTS settlements_protect ON settlements;
    CREATE TRIGGER settlements_protect BEFORE UPDATE ON settlements
      FOR EACH ROW EXECUTE FUNCTION pk_protect_columns('doc_no', 'request_id', 'uuid', 'refund_cash_entry_id', 'shortfall_transfer_id');

   ALTER TABLE "settlements" DROP CONSTRAINT "settlements_last_reversed_by_id_users_id_fk";
  
  DROP INDEX "settlements_last_reversed_by_idx";
  ALTER TABLE "settlements" DROP COLUMN "reversal_count";
  ALTER TABLE "settlements" DROP COLUMN "last_reversed_at";
  ALTER TABLE "settlements" DROP COLUMN "last_reversed_by_id";
  ALTER TABLE "settlements" DROP COLUMN "last_reversal_reason";
  `)
}
