import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/**
 * S3 track B (plan fase1-golive E11 — data go-live). Generated by
 * `payload migrate:create s3b_data_import` (reviewed) + hand-written guards (second statement), run
 * as <prefix>_owner. ADDITIVE / staging-safe: one enum value, one nullable column, one CHECK that
 * every existing row satisfies (NULL), two triggers that only act on rows with the new column set.
 *
 * - audit_logs.action += 'import' (go-live import: one row per changed master + one summary per run).
 * - cash_accounts.opening_balance_date (YYYY-MM-DD, NULL = account without a go-live date):
 *   · pk_cash_accounts_opening_lock: opening_balance / opening_balance_date immutable once a period
 *     on or after the opening month is closed (ADR 0005 "As implemented (S3b)"; correction = manual
 *     KM/KK entry). Mirrored in the collection hook for a readable 409.
 *   · pk_cash_entries_opening_guard: no cash entry dated before its account's opening date (the
 *     opening balance already contains everything before go-live).
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_audit_logs_action" ADD VALUE IF NOT EXISTS 'import';
  ALTER TABLE "cash_accounts" ADD COLUMN "opening_balance_date" varchar;`)

  await db.execute(sql`
    DO $pk$
    BEGIN
      IF current_user !~ '_owner$' THEN
        RAISE EXCEPTION 'migrations must run as the <prefix>_owner role (current_user=%)', current_user;
      END IF;
    END
    $pk$;

    ALTER TABLE cash_accounts ADD CONSTRAINT cash_accounts_opening_balance_date
      CHECK (opening_balance_date IS NULL OR opening_balance_date ~ '^\\d{4}-\\d{2}-\\d{2}$');

    CREATE OR REPLACE FUNCTION pk_cash_accounts_opening_lock() RETURNS trigger LANGUAGE plpgsql AS $fn$
    DECLARE
      p text;
    BEGIN
      IF OLD.opening_balance_date IS NOT NULL
         AND (NEW.opening_balance IS DISTINCT FROM OLD.opening_balance
              OR NEW.opening_balance_date IS DISTINCT FROM OLD.opening_balance_date) THEN
        SELECT min(period) INTO p FROM period_closings
          WHERE status = 'closed' AND period >= substr(OLD.opening_balance_date, 1, 7);
        IF p IS NOT NULL THEN
          RAISE EXCEPTION 'cash_accounts %: opening balance is locked (period % is closed)', OLD.id, p USING ERRCODE = '42501';
        END IF;
      END IF;
      RETURN NEW;
    END
    $fn$;
    CREATE TRIGGER cash_accounts_opening_lock BEFORE UPDATE ON cash_accounts FOR EACH ROW EXECUTE FUNCTION pk_cash_accounts_opening_lock();

    CREATE OR REPLACE FUNCTION pk_cash_entries_opening_guard() RETURNS trigger LANGUAGE plpgsql AS $fn$
    DECLARE
      d text;
    BEGIN
      SELECT opening_balance_date INTO d FROM cash_accounts WHERE id = NEW.cash_account_id;
      IF d IS NOT NULL AND NEW.entry_date < d THEN
        RAISE EXCEPTION 'cash_entries: entry date % is before the opening balance date % of account %', NEW.entry_date, d, NEW.cash_account_id USING ERRCODE = '42501';
      END IF;
      RETURN NEW;
    END
    $fn$;
    CREATE TRIGGER cash_entries_opening_guard BEFORE INSERT ON cash_entries FOR EACH ROW EXECUTE FUNCTION pk_cash_entries_opening_guard();
  `)
}

/**
 * Rollback (dry-run tested on the throwaway DB). Refused once an `import` audit row exists
 * (audit_logs is append-only, the enum value cannot be removed): restore the pre-migration dump
 * instead (plan fase1-golive §11). Dropping the column loses the go-live dates of the accounts.
 */
export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TRIGGER IF EXISTS cash_entries_opening_guard ON cash_entries;
  DROP FUNCTION IF EXISTS pk_cash_entries_opening_guard();
  DROP TRIGGER IF EXISTS cash_accounts_opening_lock ON cash_accounts;
  DROP FUNCTION IF EXISTS pk_cash_accounts_opening_lock();
  ALTER TABLE cash_accounts DROP CONSTRAINT IF EXISTS cash_accounts_opening_balance_date;
   ALTER TABLE "audit_logs" ALTER COLUMN "action" SET DATA TYPE text;
  DROP TYPE "public"."enum_audit_logs_action";
  CREATE TYPE "public"."enum_audit_logs_action" AS ENUM('create', 'update', 'status_change', 'deactivate', 'reactivate', 'delete_attempt', 'void', 'view_sensitive', 'login', 'logout', 'login_failed', 'session_revoked', 'role_change', 'role_sync', 'device_register', 'device_revoke', 'number_issued', 'export', 'print', 'sign', 'acknowledge', 'flag_raised', 'flag_reviewed', 'sync_odoo', 'sync_offline', 'period_close', 'period_reopen', 'schema_maintenance', 'email_test', 'approve', 'reject', 'verify', 'acknowledge_delegated', 'access_denied', 'approval_skipped', 'retention_purge');
  ALTER TABLE "audit_logs" ALTER COLUMN "action" SET DATA TYPE "public"."enum_audit_logs_action" USING "action"::"public"."enum_audit_logs_action";
  ALTER TABLE "cash_accounts" DROP COLUMN "opening_balance_date";`)
}
