import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/**
 * F2a schema (generated by `payload migrate:create f2a_flow`, reviewed): new tables for T1–T4,
 * T6–T8 and period closing, new approval-rule columns (with defaults → safe for existing rows),
 * audit action enum values. Additive only. DB guards: 20260923_133050_f2a_security.
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_approval_rules_acknowledge_by" AS ENUM('scope_manager', 'role', 'user');
  CREATE TYPE "public"."enum_approval_rules_sign_diajukan" AS ENUM('required', 'optional', 'none');
  CREATE TYPE "public"."enum_approval_rules_sign_dibuat" AS ENUM('required', 'optional', 'none');
  CREATE TYPE "public"."enum_expense_requests_type" AS ENUM('advance', 'reimburse');
  CREATE TYPE "public"."enum_expense_requests_status" AS ENUM('draft', 'pending_ack', 'pending_approval', 'approved', 'receipt_revision', 'receipts_verified', 'transferred', 'receipts_complete', 'lpj_submitted', 'lpj_revision', 'lpj_verified', 'completed', 'rejected', 'cancelled');
  CREATE TYPE "public"."enum_expense_requests_source" AS ENUM('web', 'apk', 'system', 'job');
  CREATE TYPE "public"."enum_expense_line_snapshots_reason" AS ENUM('submit', 'approve', 'receipts_resubmit');
  CREATE TYPE "public"."enum_approvals_doc_type" AS ENUM('expense_request', 'budget_addendum');
  CREATE TYPE "public"."enum_approvals_position" AS ENUM('diajukan', 'dibuat', 'diketahui', 'approval');
  CREATE TYPE "public"."enum_approvals_decision" AS ENUM('signed', 'acknowledged', 'approved', 'rejected');
  CREATE TYPE "public"."enum_approvals_signature_source" AS ENUM('profile', 'captured', 'none');
  CREATE TYPE "public"."enum_approvals_source" AS ENUM('web', 'apk', 'system', 'job');
  CREATE TYPE "public"."enum_receipts_status" AS ENUM('pending', 'valid', 'rejected', 'removed');
  CREATE TYPE "public"."enum_receipts_entry_source" AS ENUM('manual', 'ocr');
  CREATE TYPE "public"."enum_receipt_flags_kind" AS ENUM('amount_diff', 'date_after_request', 'date_too_old', 'date_out_of_period', 'uom_suspicious', 'duplicate');
  CREATE TYPE "public"."enum_receipt_flags_level" AS ENUM('info', 'warning');
  CREATE TYPE "public"."enum_receipt_flags_status" AS ENUM('open', 'reviewed', 'resolved');
  CREATE TYPE "public"."enum_transfers_kind" AS ENUM('advance', 'reimburse', 'lpj_shortfall');
  CREATE TYPE "public"."enum_transfers_status" AS ENUM('posted', 'void');
  CREATE TYPE "public"."enum_cash_entries_direction" AS ENUM('in', 'out');
  CREATE TYPE "public"."enum_cash_entries_source_type" AS ENUM('transfer', 'settlement_refund', 'manual', 'reversal', 'opening');
  CREATE TYPE "public"."enum_cash_entries_status" AS ENUM('posted', 'void');
  CREATE TYPE "public"."enum_period_closings_status" AS ENUM('closed', 'reopened');
  ALTER TYPE "public"."enum_audit_logs_action" ADD VALUE 'approve';
  ALTER TYPE "public"."enum_audit_logs_action" ADD VALUE 'reject';
  ALTER TYPE "public"."enum_audit_logs_action" ADD VALUE 'verify';
  CREATE TABLE "expense_requests_lines" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"description" varchar,
  	"qty" numeric,
  	"uom_id" integer,
  	"unit_price" numeric,
  	"total" numeric,
  	"category_id" integer,
  	"vehicle_id" integer,
  	"notes" varchar
  );
  
  CREATE TABLE "expense_requests" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"doc_no" varchar,
  	"type" "enum_expense_requests_type" NOT NULL,
  	"status" "enum_expense_requests_status" DEFAULT 'draft' NOT NULL,
  	"title" varchar NOT NULL,
  	"project_id" integer,
  	"cost_center_id" integer,
  	"request_date" varchar,
  	"needed_date" varchar,
  	"period_from" varchar,
  	"period_to" varchar,
  	"notes" varchar,
  	"created_by_id" integer,
  	"bank_account_id" integer,
  	"bank_snapshot_bank_name" varchar,
  	"bank_snapshot_account_no" varchar,
  	"bank_snapshot_account_holder" varchar,
  	"grand_total" numeric,
  	"approved_amount" numeric,
  	"transferred_total" numeric,
  	"approval_rule_id" integer,
  	"approval_snapshot" jsonb,
  	"approval_cycle" numeric DEFAULT 0,
  	"current_level" numeric,
  	"submitted_at" timestamp(3) with time zone,
  	"content_hash" varchar,
  	"resubmit_of_id" integer,
  	"cancel_reason" varchar,
  	"reject_reason" varchar,
  	"client_uuid" varchar,
  	"source" "enum_expense_requests_source",
  	"uuid" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "expense_requests_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"employees_id" integer,
  	"media_attachments_id" integer
  );
  
  CREATE TABLE "expense_line_snapshots" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"request_id" integer NOT NULL,
  	"cycle" numeric NOT NULL,
  	"reason" "enum_expense_line_snapshots_reason" NOT NULL,
  	"grand_total" numeric NOT NULL,
  	"content_hash" varchar,
  	"data" jsonb NOT NULL,
  	"taken_at" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "approvals" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"doc_type" "enum_approvals_doc_type" DEFAULT 'expense_request' NOT NULL,
  	"request_id" integer NOT NULL,
  	"cycle" numeric NOT NULL,
  	"position" "enum_approvals_position" NOT NULL,
  	"level" numeric DEFAULT 0 NOT NULL,
  	"actor_id" integer,
  	"employee_id" integer,
  	"actor_name" varchar,
  	"on_behalf" boolean DEFAULT false,
  	"decision" "enum_approvals_decision" NOT NULL,
  	"reason" varchar,
  	"decided_at" timestamp(3) with time zone,
  	"budget_pct_before" numeric,
  	"budget_pct_after" numeric,
  	"open_flags" numeric,
  	"signature_id" integer,
  	"signature_sha256" varchar,
  	"signature_source" "enum_approvals_signature_source",
  	"device_id" varchar,
  	"source" "enum_approvals_source",
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "receipts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"request_id" integer NOT NULL,
  	"line_id" varchar NOT NULL,
  	"line_no" numeric,
  	"receipt_no" varchar,
  	"receipt_no_norm" varchar,
  	"vendor_id" integer,
  	"vendor_name" varchar NOT NULL,
  	"vendor_norm" varchar,
  	"receipt_date" varchar NOT NULL,
  	"receipt_time" varchar,
  	"amount" numeric NOT NULL,
  	"tax_amount" numeric,
  	"image_id" integer NOT NULL,
  	"image_sha256" varchar,
  	"status" "enum_receipts_status" DEFAULT 'pending' NOT NULL,
  	"reject_reason" varchar,
  	"remove_reason" varchar,
  	"verified_by_id" integer,
  	"verified_at" timestamp(3) with time zone,
  	"entry_source" "enum_receipts_entry_source" DEFAULT 'manual',
  	"created_by_id" integer,
  	"uuid" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "receipt_flags" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"request_id" integer NOT NULL,
  	"key" varchar NOT NULL,
  	"kind" "enum_receipt_flags_kind" NOT NULL,
  	"level" "enum_receipt_flags_level" NOT NULL,
  	"line_id" varchar,
  	"line_no" numeric,
  	"receipt_id" integer,
  	"related_request_id" integer,
  	"message" varchar NOT NULL,
  	"detail" jsonb,
  	"status" "enum_receipt_flags_status" DEFAULT 'open' NOT NULL,
  	"reviewed_by_id" integer,
  	"reviewed_at" timestamp(3) with time zone,
  	"review_note" varchar,
  	"resolved_at" timestamp(3) with time zone,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "transfers" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"doc_no" varchar,
  	"request_id" integer NOT NULL,
  	"kind" "enum_transfers_kind" NOT NULL,
  	"cash_account_id" integer NOT NULL,
  	"amount" numeric NOT NULL,
  	"destination_bank_name" varchar,
  	"destination_account_no" varchar,
  	"destination_account_holder" varchar,
  	"bank_ref" varchar NOT NULL,
  	"proof_id" integer NOT NULL,
  	"transfer_date" varchar NOT NULL,
  	"posted_by_id" integer,
  	"status" "enum_transfers_status" DEFAULT 'posted' NOT NULL,
  	"cash_entry_id" integer,
  	"void_reason" varchar,
  	"voided_by_id" integer,
  	"voided_at" timestamp(3) with time zone,
  	"uuid" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "cash_entries" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"entry_no" varchar,
  	"entry_date" varchar NOT NULL,
  	"period" varchar,
  	"direction" "enum_cash_entries_direction" NOT NULL,
  	"amount" numeric NOT NULL,
  	"cash_account_id" integer NOT NULL,
  	"category_id" integer,
  	"cash_in_source_id" integer,
  	"project_id" integer,
  	"cost_center_id" integer,
  	"vehicle_id" integer,
  	"description" varchar,
  	"proof_id" integer,
  	"source_type" "enum_cash_entries_source_type" NOT NULL,
  	"expense_request_id" integer,
  	"transfer_id" integer,
  	"status" "enum_cash_entries_status" DEFAULT 'posted' NOT NULL,
  	"reversal_of_id" integer,
  	"reversed_by_id" integer,
  	"void_reason" varchar,
  	"voided_by_id" integer,
  	"voided_at" timestamp(3) with time zone,
  	"posted_by_id" integer,
  	"posted_at" timestamp(3) with time zone,
  	"uuid" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "period_closings" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"period" varchar NOT NULL,
  	"status" "enum_period_closings_status" DEFAULT 'closed' NOT NULL,
  	"note" varchar,
  	"closed_by_id" integer,
  	"closed_at" timestamp(3) with time zone,
  	"reopened_by_id" integer,
  	"reopened_at" timestamp(3) with time zone,
  	"reopen_reason" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "approval_rules" ADD COLUMN "acknowledge_by" "enum_approval_rules_acknowledge_by" DEFAULT 'scope_manager' NOT NULL;
  ALTER TABLE "approval_rules" ADD COLUMN "acknowledge_user_id" integer;
  ALTER TABLE "approval_rules" ADD COLUMN "sign_diajukan" "enum_approval_rules_sign_diajukan" DEFAULT 'required' NOT NULL;
  ALTER TABLE "approval_rules" ADD COLUMN "sign_dibuat" "enum_approval_rules_sign_dibuat" DEFAULT 'required' NOT NULL;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "expense_requests_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "receipts_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "receipt_flags_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "transfers_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "cash_entries_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "period_closings_id" integer;
  ALTER TABLE "expense_requests_lines" ADD CONSTRAINT "expense_requests_lines_uom_id_uoms_id_fk" FOREIGN KEY ("uom_id") REFERENCES "public"."uoms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expense_requests_lines" ADD CONSTRAINT "expense_requests_lines_category_id_expense_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."expense_categories"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expense_requests_lines" ADD CONSTRAINT "expense_requests_lines_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expense_requests_lines" ADD CONSTRAINT "expense_requests_lines_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."expense_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "expense_requests" ADD CONSTRAINT "expense_requests_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expense_requests" ADD CONSTRAINT "expense_requests_cost_center_id_cost_centers_id_fk" FOREIGN KEY ("cost_center_id") REFERENCES "public"."cost_centers"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expense_requests" ADD CONSTRAINT "expense_requests_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expense_requests" ADD CONSTRAINT "expense_requests_bank_account_id_employee_bank_accounts_id_fk" FOREIGN KEY ("bank_account_id") REFERENCES "public"."employee_bank_accounts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expense_requests" ADD CONSTRAINT "expense_requests_approval_rule_id_approval_rules_id_fk" FOREIGN KEY ("approval_rule_id") REFERENCES "public"."approval_rules"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expense_requests" ADD CONSTRAINT "expense_requests_resubmit_of_id_expense_requests_id_fk" FOREIGN KEY ("resubmit_of_id") REFERENCES "public"."expense_requests"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "expense_requests_rels" ADD CONSTRAINT "expense_requests_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."expense_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "expense_requests_rels" ADD CONSTRAINT "expense_requests_rels_employees_fk" FOREIGN KEY ("employees_id") REFERENCES "public"."employees"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "expense_requests_rels" ADD CONSTRAINT "expense_requests_rels_media_attachments_fk" FOREIGN KEY ("media_attachments_id") REFERENCES "public"."media_attachments"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "expense_line_snapshots" ADD CONSTRAINT "expense_line_snapshots_request_id_expense_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."expense_requests"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "approvals" ADD CONSTRAINT "approvals_request_id_expense_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."expense_requests"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "approvals" ADD CONSTRAINT "approvals_actor_id_users_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "approvals" ADD CONSTRAINT "approvals_employee_id_employees_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "approvals" ADD CONSTRAINT "approvals_signature_id_media_signatures_id_fk" FOREIGN KEY ("signature_id") REFERENCES "public"."media_signatures"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "receipts" ADD CONSTRAINT "receipts_request_id_expense_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."expense_requests"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "receipts" ADD CONSTRAINT "receipts_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "receipts" ADD CONSTRAINT "receipts_image_id_media_receipts_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media_receipts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "receipts" ADD CONSTRAINT "receipts_verified_by_id_users_id_fk" FOREIGN KEY ("verified_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "receipts" ADD CONSTRAINT "receipts_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "receipt_flags" ADD CONSTRAINT "receipt_flags_request_id_expense_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."expense_requests"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "receipt_flags" ADD CONSTRAINT "receipt_flags_receipt_id_receipts_id_fk" FOREIGN KEY ("receipt_id") REFERENCES "public"."receipts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "receipt_flags" ADD CONSTRAINT "receipt_flags_related_request_id_expense_requests_id_fk" FOREIGN KEY ("related_request_id") REFERENCES "public"."expense_requests"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "receipt_flags" ADD CONSTRAINT "receipt_flags_reviewed_by_id_users_id_fk" FOREIGN KEY ("reviewed_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "transfers" ADD CONSTRAINT "transfers_request_id_expense_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."expense_requests"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "transfers" ADD CONSTRAINT "transfers_cash_account_id_cash_accounts_id_fk" FOREIGN KEY ("cash_account_id") REFERENCES "public"."cash_accounts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "transfers" ADD CONSTRAINT "transfers_proof_id_media_transfer_proofs_id_fk" FOREIGN KEY ("proof_id") REFERENCES "public"."media_transfer_proofs"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "transfers" ADD CONSTRAINT "transfers_posted_by_id_users_id_fk" FOREIGN KEY ("posted_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "transfers" ADD CONSTRAINT "transfers_cash_entry_id_cash_entries_id_fk" FOREIGN KEY ("cash_entry_id") REFERENCES "public"."cash_entries"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "transfers" ADD CONSTRAINT "transfers_voided_by_id_users_id_fk" FOREIGN KEY ("voided_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_cash_account_id_cash_accounts_id_fk" FOREIGN KEY ("cash_account_id") REFERENCES "public"."cash_accounts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_category_id_expense_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."expense_categories"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_cash_in_source_id_cash_in_sources_id_fk" FOREIGN KEY ("cash_in_source_id") REFERENCES "public"."cash_in_sources"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_cost_center_id_cost_centers_id_fk" FOREIGN KEY ("cost_center_id") REFERENCES "public"."cost_centers"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_proof_id_media_attachments_id_fk" FOREIGN KEY ("proof_id") REFERENCES "public"."media_attachments"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_expense_request_id_expense_requests_id_fk" FOREIGN KEY ("expense_request_id") REFERENCES "public"."expense_requests"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_transfer_id_transfers_id_fk" FOREIGN KEY ("transfer_id") REFERENCES "public"."transfers"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_reversal_of_id_cash_entries_id_fk" FOREIGN KEY ("reversal_of_id") REFERENCES "public"."cash_entries"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_reversed_by_id_cash_entries_id_fk" FOREIGN KEY ("reversed_by_id") REFERENCES "public"."cash_entries"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_voided_by_id_users_id_fk" FOREIGN KEY ("voided_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "cash_entries" ADD CONSTRAINT "cash_entries_posted_by_id_users_id_fk" FOREIGN KEY ("posted_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "period_closings" ADD CONSTRAINT "period_closings_closed_by_id_users_id_fk" FOREIGN KEY ("closed_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "period_closings" ADD CONSTRAINT "period_closings_reopened_by_id_users_id_fk" FOREIGN KEY ("reopened_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "expense_requests_lines_order_idx" ON "expense_requests_lines" USING btree ("_order");
  CREATE INDEX "expense_requests_lines_parent_id_idx" ON "expense_requests_lines" USING btree ("_parent_id");
  CREATE INDEX "expense_requests_lines_uom_idx" ON "expense_requests_lines" USING btree ("uom_id");
  CREATE INDEX "expense_requests_lines_category_idx" ON "expense_requests_lines" USING btree ("category_id");
  CREATE INDEX "expense_requests_lines_vehicle_idx" ON "expense_requests_lines" USING btree ("vehicle_id");
  CREATE UNIQUE INDEX "expense_requests_doc_no_idx" ON "expense_requests" USING btree ("doc_no");
  CREATE INDEX "expense_requests_status_idx" ON "expense_requests" USING btree ("status");
  CREATE INDEX "expense_requests_project_idx" ON "expense_requests" USING btree ("project_id");
  CREATE INDEX "expense_requests_cost_center_idx" ON "expense_requests" USING btree ("cost_center_id");
  CREATE INDEX "expense_requests_created_by_idx" ON "expense_requests" USING btree ("created_by_id");
  CREATE INDEX "expense_requests_bank_account_idx" ON "expense_requests" USING btree ("bank_account_id");
  CREATE INDEX "expense_requests_approval_rule_idx" ON "expense_requests" USING btree ("approval_rule_id");
  CREATE INDEX "expense_requests_resubmit_of_idx" ON "expense_requests" USING btree ("resubmit_of_id");
  CREATE UNIQUE INDEX "expense_requests_client_uuid_idx" ON "expense_requests" USING btree ("client_uuid");
  CREATE UNIQUE INDEX "expense_requests_uuid_idx" ON "expense_requests" USING btree ("uuid");
  CREATE INDEX "expense_requests_updated_at_idx" ON "expense_requests" USING btree ("updated_at");
  CREATE INDEX "expense_requests_created_at_idx" ON "expense_requests" USING btree ("created_at");
  CREATE INDEX "expense_requests_rels_order_idx" ON "expense_requests_rels" USING btree ("order");
  CREATE INDEX "expense_requests_rels_parent_idx" ON "expense_requests_rels" USING btree ("parent_id");
  CREATE INDEX "expense_requests_rels_path_idx" ON "expense_requests_rels" USING btree ("path");
  CREATE INDEX "expense_requests_rels_employees_id_idx" ON "expense_requests_rels" USING btree ("employees_id");
  CREATE INDEX "expense_requests_rels_media_attachments_id_idx" ON "expense_requests_rels" USING btree ("media_attachments_id");
  CREATE INDEX "expense_line_snapshots_request_idx" ON "expense_line_snapshots" USING btree ("request_id");
  CREATE INDEX "expense_line_snapshots_updated_at_idx" ON "expense_line_snapshots" USING btree ("updated_at");
  CREATE INDEX "expense_line_snapshots_created_at_idx" ON "expense_line_snapshots" USING btree ("created_at");
  CREATE INDEX "approvals_request_idx" ON "approvals" USING btree ("request_id");
  CREATE INDEX "approvals_actor_idx" ON "approvals" USING btree ("actor_id");
  CREATE INDEX "approvals_employee_idx" ON "approvals" USING btree ("employee_id");
  CREATE INDEX "approvals_signature_idx" ON "approvals" USING btree ("signature_id");
  CREATE INDEX "approvals_updated_at_idx" ON "approvals" USING btree ("updated_at");
  CREATE INDEX "approvals_created_at_idx" ON "approvals" USING btree ("created_at");
  CREATE INDEX "receipts_request_idx" ON "receipts" USING btree ("request_id");
  CREATE INDEX "receipts_line_id_idx" ON "receipts" USING btree ("line_id");
  CREATE INDEX "receipts_receipt_no_norm_idx" ON "receipts" USING btree ("receipt_no_norm");
  CREATE INDEX "receipts_vendor_idx" ON "receipts" USING btree ("vendor_id");
  CREATE INDEX "receipts_vendor_norm_idx" ON "receipts" USING btree ("vendor_norm");
  CREATE INDEX "receipts_image_idx" ON "receipts" USING btree ("image_id");
  CREATE INDEX "receipts_image_sha256_idx" ON "receipts" USING btree ("image_sha256");
  CREATE INDEX "receipts_status_idx" ON "receipts" USING btree ("status");
  CREATE INDEX "receipts_verified_by_idx" ON "receipts" USING btree ("verified_by_id");
  CREATE INDEX "receipts_created_by_idx" ON "receipts" USING btree ("created_by_id");
  CREATE UNIQUE INDEX "receipts_uuid_idx" ON "receipts" USING btree ("uuid");
  CREATE INDEX "receipts_updated_at_idx" ON "receipts" USING btree ("updated_at");
  CREATE INDEX "receipts_created_at_idx" ON "receipts" USING btree ("created_at");
  CREATE INDEX "receipt_flags_request_idx" ON "receipt_flags" USING btree ("request_id");
  CREATE INDEX "receipt_flags_key_idx" ON "receipt_flags" USING btree ("key");
  CREATE INDEX "receipt_flags_receipt_idx" ON "receipt_flags" USING btree ("receipt_id");
  CREATE INDEX "receipt_flags_related_request_idx" ON "receipt_flags" USING btree ("related_request_id");
  CREATE INDEX "receipt_flags_status_idx" ON "receipt_flags" USING btree ("status");
  CREATE INDEX "receipt_flags_reviewed_by_idx" ON "receipt_flags" USING btree ("reviewed_by_id");
  CREATE INDEX "receipt_flags_updated_at_idx" ON "receipt_flags" USING btree ("updated_at");
  CREATE INDEX "receipt_flags_created_at_idx" ON "receipt_flags" USING btree ("created_at");
  CREATE UNIQUE INDEX "transfers_doc_no_idx" ON "transfers" USING btree ("doc_no");
  CREATE INDEX "transfers_request_idx" ON "transfers" USING btree ("request_id");
  CREATE INDEX "transfers_cash_account_idx" ON "transfers" USING btree ("cash_account_id");
  CREATE INDEX "transfers_proof_idx" ON "transfers" USING btree ("proof_id");
  CREATE INDEX "transfers_posted_by_idx" ON "transfers" USING btree ("posted_by_id");
  CREATE INDEX "transfers_status_idx" ON "transfers" USING btree ("status");
  CREATE INDEX "transfers_cash_entry_idx" ON "transfers" USING btree ("cash_entry_id");
  CREATE INDEX "transfers_voided_by_idx" ON "transfers" USING btree ("voided_by_id");
  CREATE UNIQUE INDEX "transfers_uuid_idx" ON "transfers" USING btree ("uuid");
  CREATE INDEX "transfers_updated_at_idx" ON "transfers" USING btree ("updated_at");
  CREATE INDEX "transfers_created_at_idx" ON "transfers" USING btree ("created_at");
  CREATE UNIQUE INDEX "cash_entries_entry_no_idx" ON "cash_entries" USING btree ("entry_no");
  CREATE INDEX "cash_entries_entry_date_idx" ON "cash_entries" USING btree ("entry_date");
  CREATE INDEX "cash_entries_period_idx" ON "cash_entries" USING btree ("period");
  CREATE INDEX "cash_entries_cash_account_idx" ON "cash_entries" USING btree ("cash_account_id");
  CREATE INDEX "cash_entries_category_idx" ON "cash_entries" USING btree ("category_id");
  CREATE INDEX "cash_entries_cash_in_source_idx" ON "cash_entries" USING btree ("cash_in_source_id");
  CREATE INDEX "cash_entries_project_idx" ON "cash_entries" USING btree ("project_id");
  CREATE INDEX "cash_entries_cost_center_idx" ON "cash_entries" USING btree ("cost_center_id");
  CREATE INDEX "cash_entries_vehicle_idx" ON "cash_entries" USING btree ("vehicle_id");
  CREATE INDEX "cash_entries_proof_idx" ON "cash_entries" USING btree ("proof_id");
  CREATE INDEX "cash_entries_expense_request_idx" ON "cash_entries" USING btree ("expense_request_id");
  CREATE INDEX "cash_entries_transfer_idx" ON "cash_entries" USING btree ("transfer_id");
  CREATE INDEX "cash_entries_status_idx" ON "cash_entries" USING btree ("status");
  CREATE INDEX "cash_entries_reversal_of_idx" ON "cash_entries" USING btree ("reversal_of_id");
  CREATE INDEX "cash_entries_reversed_by_idx" ON "cash_entries" USING btree ("reversed_by_id");
  CREATE INDEX "cash_entries_voided_by_idx" ON "cash_entries" USING btree ("voided_by_id");
  CREATE INDEX "cash_entries_posted_by_idx" ON "cash_entries" USING btree ("posted_by_id");
  CREATE UNIQUE INDEX "cash_entries_uuid_idx" ON "cash_entries" USING btree ("uuid");
  CREATE INDEX "cash_entries_updated_at_idx" ON "cash_entries" USING btree ("updated_at");
  CREATE INDEX "cash_entries_created_at_idx" ON "cash_entries" USING btree ("created_at");
  CREATE INDEX "period_closings_period_idx" ON "period_closings" USING btree ("period");
  CREATE INDEX "period_closings_closed_by_idx" ON "period_closings" USING btree ("closed_by_id");
  CREATE INDEX "period_closings_reopened_by_idx" ON "period_closings" USING btree ("reopened_by_id");
  CREATE INDEX "period_closings_updated_at_idx" ON "period_closings" USING btree ("updated_at");
  CREATE INDEX "period_closings_created_at_idx" ON "period_closings" USING btree ("created_at");
  ALTER TABLE "approval_rules" ADD CONSTRAINT "approval_rules_acknowledge_user_id_users_id_fk" FOREIGN KEY ("acknowledge_user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_expense_requests_fk" FOREIGN KEY ("expense_requests_id") REFERENCES "public"."expense_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_receipts_fk" FOREIGN KEY ("receipts_id") REFERENCES "public"."receipts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_receipt_flags_fk" FOREIGN KEY ("receipt_flags_id") REFERENCES "public"."receipt_flags"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_transfers_fk" FOREIGN KEY ("transfers_id") REFERENCES "public"."transfers"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_cash_entries_fk" FOREIGN KEY ("cash_entries_id") REFERENCES "public"."cash_entries"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_period_closings_fk" FOREIGN KEY ("period_closings_id") REFERENCES "public"."period_closings"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "approval_rules_acknowledge_user_idx" ON "approval_rules" USING btree ("acknowledge_user_id");
  CREATE INDEX "payload_locked_documents_rels_expense_requests_id_idx" ON "payload_locked_documents_rels" USING btree ("expense_requests_id");
  CREATE INDEX "payload_locked_documents_rels_receipts_id_idx" ON "payload_locked_documents_rels" USING btree ("receipts_id");
  CREATE INDEX "payload_locked_documents_rels_receipt_flags_id_idx" ON "payload_locked_documents_rels" USING btree ("receipt_flags_id");
  CREATE INDEX "payload_locked_documents_rels_transfers_id_idx" ON "payload_locked_documents_rels" USING btree ("transfers_id");
  CREATE INDEX "payload_locked_documents_rels_cash_entries_id_idx" ON "payload_locked_documents_rels" USING btree ("cash_entries_id");
  CREATE INDEX "payload_locked_documents_rels_period_closings_id_idx" ON "payload_locked_documents_rels" USING btree ("period_closings_id");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "expense_requests_lines" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "expense_requests" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "expense_requests_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "expense_line_snapshots" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "approvals" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "receipts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "receipt_flags" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "transfers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "cash_entries" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "period_closings" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "expense_requests_lines" CASCADE;
  DROP TABLE "expense_requests" CASCADE;
  DROP TABLE "expense_requests_rels" CASCADE;
  DROP TABLE "expense_line_snapshots" CASCADE;
  DROP TABLE "approvals" CASCADE;
  DROP TABLE "receipts" CASCADE;
  DROP TABLE "receipt_flags" CASCADE;
  DROP TABLE "transfers" CASCADE;
  DROP TABLE "cash_entries" CASCADE;
  DROP TABLE "period_closings" CASCADE;
  ALTER TABLE "approval_rules" DROP CONSTRAINT "approval_rules_acknowledge_user_id_users_id_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_expense_requests_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_receipts_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_receipt_flags_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_transfers_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_cash_entries_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_period_closings_fk";
  
  ALTER TABLE "audit_logs" ALTER COLUMN "action" SET DATA TYPE text;
  DROP TYPE "public"."enum_audit_logs_action";
  CREATE TYPE "public"."enum_audit_logs_action" AS ENUM('create', 'update', 'status_change', 'deactivate', 'reactivate', 'delete_attempt', 'void', 'view_sensitive', 'login', 'logout', 'login_failed', 'session_revoked', 'role_change', 'role_sync', 'device_register', 'device_revoke', 'number_issued', 'export', 'print', 'sign', 'acknowledge', 'flag_raised', 'flag_reviewed', 'sync_odoo', 'sync_offline', 'period_close', 'period_reopen', 'schema_maintenance', 'email_test');
  ALTER TABLE "audit_logs" ALTER COLUMN "action" SET DATA TYPE "public"."enum_audit_logs_action" USING "action"::"public"."enum_audit_logs_action";
  DROP INDEX "approval_rules_acknowledge_user_idx";
  DROP INDEX "payload_locked_documents_rels_expense_requests_id_idx";
  DROP INDEX "payload_locked_documents_rels_receipts_id_idx";
  DROP INDEX "payload_locked_documents_rels_receipt_flags_id_idx";
  DROP INDEX "payload_locked_documents_rels_transfers_id_idx";
  DROP INDEX "payload_locked_documents_rels_cash_entries_id_idx";
  DROP INDEX "payload_locked_documents_rels_period_closings_id_idx";
  ALTER TABLE "approval_rules" DROP COLUMN "acknowledge_by";
  ALTER TABLE "approval_rules" DROP COLUMN "acknowledge_user_id";
  ALTER TABLE "approval_rules" DROP COLUMN "sign_diajukan";
  ALTER TABLE "approval_rules" DROP COLUMN "sign_dibuat";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "expense_requests_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "receipts_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "receipt_flags_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "transfers_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "cash_entries_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "period_closings_id";
  DROP TYPE "public"."enum_approval_rules_acknowledge_by";
  DROP TYPE "public"."enum_approval_rules_sign_diajukan";
  DROP TYPE "public"."enum_approval_rules_sign_dibuat";
  DROP TYPE "public"."enum_expense_requests_type";
  DROP TYPE "public"."enum_expense_requests_status";
  DROP TYPE "public"."enum_expense_requests_source";
  DROP TYPE "public"."enum_expense_line_snapshots_reason";
  DROP TYPE "public"."enum_approvals_doc_type";
  DROP TYPE "public"."enum_approvals_position";
  DROP TYPE "public"."enum_approvals_decision";
  DROP TYPE "public"."enum_approvals_signature_source";
  DROP TYPE "public"."enum_approvals_source";
  DROP TYPE "public"."enum_receipts_status";
  DROP TYPE "public"."enum_receipts_entry_source";
  DROP TYPE "public"."enum_receipt_flags_kind";
  DROP TYPE "public"."enum_receipt_flags_level";
  DROP TYPE "public"."enum_receipt_flags_status";
  DROP TYPE "public"."enum_transfers_kind";
  DROP TYPE "public"."enum_transfers_status";
  DROP TYPE "public"."enum_cash_entries_direction";
  DROP TYPE "public"."enum_cash_entries_source_type";
  DROP TYPE "public"."enum_cash_entries_status";
  DROP TYPE "public"."enum_period_closings_status";`)
}
