import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/**
 * S3 track E — Fase 1 UAT gap fixes (docs/proyekkas/uat/fase1/README.md S-04, S-24).
 * Generated by `payload migrate:create s3e_uat_gap_fixes` (reviewed) + a data step; run as <prefix>_owner.
 * ADDITIVE / staging-safe, company_settings only:
 * 1. `notify_requester_status_enabled` (default TRUE): in-app notification to the requesters / creator
 *    when a request is submitted, withdrawn or created on their behalf (US-05, US-41).
 * 2. `approval_email_enabled` (default FALSE): email to the Direktur / Finance when a request waits for
 *    their decision (sendEmail queue, same SMTP guard as the E7 reminders). The EXISTING row copies
 *    `reminder_email_enabled` (email stays off where the reminder email is off; on where it was
 *    switched on deliberately).
 * 3. `image_targets_receipts_max_px` default 2000 → 1600 (US-57, requirements §9) — the device-side
 *    target served to the APK by /api/v1/me. The existing row is changed only when it still holds the
 *    old default 2000 (a deliberately customised value stays).
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    DO $pk$
    BEGIN
      IF current_user !~ '_owner$' THEN
        RAISE EXCEPTION 'migrations must run as the <prefix>_owner role (current_user=%)', current_user;
      END IF;
    END
    $pk$;

  ALTER TABLE "company_settings" ALTER COLUMN "image_targets_receipts_max_px" SET DEFAULT 1600;
  ALTER TABLE "company_settings" ADD COLUMN "notify_requester_status_enabled" boolean DEFAULT true;
  ALTER TABLE "company_settings" ADD COLUMN "approval_email_enabled" boolean DEFAULT false;

  UPDATE "company_settings" SET "approval_email_enabled" = coalesce("reminder_email_enabled", false), "notify_requester_status_enabled" = true;
  UPDATE "company_settings" SET "image_targets_receipts_max_px" = 1600 WHERE "image_targets_receipts_max_px" = 2000;`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  UPDATE "company_settings" SET "image_targets_receipts_max_px" = 2000 WHERE "image_targets_receipts_max_px" = 1600;
  ALTER TABLE "company_settings" ALTER COLUMN "image_targets_receipts_max_px" SET DEFAULT 2000;
  ALTER TABLE "company_settings" DROP COLUMN "notify_requester_status_enabled";
  ALTER TABLE "company_settings" DROP COLUMN "approval_email_enabled";`)
}
