import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/**
 * E4 — project stages + progress reports (T11, US-10/11/12/29/31, plan fase1-golive §E4).
 * Generated by `payload migrate:create e4_progress_reports` (reviewed) + hand-written guards (one
 * migration, run as <prefix>_owner). ADDITIVE / staging-safe: one new table, four new defaulted or
 * nullable columns (projects.progress_pct 0, project_stages.active true,
 * company_settings.sync_progress_reports_enabled true, payload_locked_documents_rels.progress_reports_id);
 * no existing row is rewritten, no column/enum is dropped.
 *
 * Guards (ADR 0006 style, defence in depth behind the domain service):
 * 1. `projects.progress_pct` / `project_stages.progress_pct` change ONLY while the transaction-local
 *    setting `pk.progress_write` = 'on' (set by domain/progress/recalc.ts around its own writes);
 *    anything else → 42501 (requirements §1 #7 "progress hanya lewat laporan"). Range 0..100 CHECKs.
 * 2. `progress_reports`: no DELETE/TRUNCATE for the app role; `received_at` = DB clock and
 *    `editable_until` = received_at + 24 h (requirements §8 T11), no UPDATE after the window;
 *    identity columns immutable; stage must belong to the project; % 0..100 and after ≥ before;
 *    report_date is a business date; photo_count 0..5.
 * 3. `media_progress_photos`: owner link immutable once set; at most 5 photos per report.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_progress_reports_time_trust" AS ENUM('server', 'estimated', 'device_only');
  CREATE TYPE "public"."enum_progress_reports_source" AS ENUM('web', 'apk');
  CREATE TABLE "progress_reports" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"doc_no" varchar,
  	"project_id" integer NOT NULL,
  	"stage_id" integer NOT NULL,
  	"report_date" varchar NOT NULL,
  	"pct_before" numeric NOT NULL,
  	"pct_after" numeric NOT NULL,
  	"project_pct_before" numeric,
  	"project_pct_after" numeric,
  	"work" varchar NOT NULL,
  	"issues" varchar,
  	"reporter_id" integer NOT NULL,
  	"photo_count" numeric DEFAULT 0,
  	"received_at" timestamp(3) with time zone,
  	"editable_until" timestamp(3) with time zone,
  	"device_time" timestamp(3) with time zone,
  	"time_trust" "enum_progress_reports_time_trust",
  	"offline" boolean DEFAULT false,
  	"source" "enum_progress_reports_source",
  	"flags" jsonb,
  	"sync_rev" numeric DEFAULT 1,
  	"client_uuid" varchar,
  	"uuid" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "projects" ADD COLUMN "progress_pct" numeric DEFAULT 0;
  ALTER TABLE "project_stages" ADD COLUMN "active" boolean DEFAULT true;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "progress_reports_id" integer;
  ALTER TABLE "company_settings" ADD COLUMN "sync_progress_reports_enabled" boolean DEFAULT true;
  ALTER TABLE "progress_reports" ADD CONSTRAINT "progress_reports_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "progress_reports" ADD CONSTRAINT "progress_reports_stage_id_project_stages_id_fk" FOREIGN KEY ("stage_id") REFERENCES "public"."project_stages"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "progress_reports" ADD CONSTRAINT "progress_reports_reporter_id_users_id_fk" FOREIGN KEY ("reporter_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  CREATE UNIQUE INDEX "progress_reports_doc_no_idx" ON "progress_reports" USING btree ("doc_no");
  CREATE INDEX "progress_reports_project_idx" ON "progress_reports" USING btree ("project_id");
  CREATE INDEX "progress_reports_stage_idx" ON "progress_reports" USING btree ("stage_id");
  CREATE INDEX "progress_reports_report_date_idx" ON "progress_reports" USING btree ("report_date");
  CREATE INDEX "progress_reports_reporter_idx" ON "progress_reports" USING btree ("reporter_id");
  CREATE INDEX "progress_reports_offline_idx" ON "progress_reports" USING btree ("offline");
  CREATE UNIQUE INDEX "progress_reports_client_uuid_idx" ON "progress_reports" USING btree ("client_uuid");
  CREATE UNIQUE INDEX "progress_reports_uuid_idx" ON "progress_reports" USING btree ("uuid");
  CREATE INDEX "progress_reports_updated_at_idx" ON "progress_reports" USING btree ("updated_at");
  CREATE INDEX "progress_reports_created_at_idx" ON "progress_reports" USING btree ("created_at");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_progress_reports_fk" FOREIGN KEY ("progress_reports_id") REFERENCES "public"."progress_reports"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "project_stages_active_idx" ON "project_stages" USING btree ("active");
  CREATE INDEX "payload_locked_documents_rels_progress_reports_id_idx" ON "payload_locked_documents_rels" USING btree ("progress_reports_id");`)

  await db.execute(sql`
    DO $pk$
    BEGIN
      IF current_user !~ '_owner$' THEN
        RAISE EXCEPTION 'migrations must run as the <prefix>_owner role (current_user=%)', current_user;
      END IF;
    END
    $pk$;

    -- 1. progress_pct only through the recalculation service
    CREATE OR REPLACE FUNCTION pk_progress_guard() RETURNS trigger LANGUAGE plpgsql AS $fn$
    BEGIN
      IF coalesce(current_setting('pk.progress_write', true), '') = 'on' THEN
        RETURN NEW;
      END IF;
      IF TG_OP = 'INSERT' THEN
        IF coalesce(NEW.progress_pct, 0) <> 0 THEN
          RAISE EXCEPTION '%.progress_pct only changes through progress reports', TG_TABLE_NAME USING ERRCODE = '42501';
        END IF;
      ELSIF NEW.progress_pct IS DISTINCT FROM OLD.progress_pct THEN
        RAISE EXCEPTION '%.progress_pct only changes through progress reports', TG_TABLE_NAME USING ERRCODE = '42501';
      END IF;
      RETURN NEW;
    END
    $fn$;
    CREATE TRIGGER projects_progress_guard BEFORE INSERT OR UPDATE ON projects FOR EACH ROW EXECUTE FUNCTION pk_progress_guard();
    CREATE TRIGGER project_stages_progress_guard BEFORE INSERT OR UPDATE ON project_stages FOR EACH ROW EXECUTE FUNCTION pk_progress_guard();
    ALTER TABLE projects ADD CONSTRAINT projects_progress_pct_range CHECK (progress_pct IS NULL OR (progress_pct >= 0 AND progress_pct <= 100));
    ALTER TABLE project_stages ADD CONSTRAINT project_stages_progress_pct_range CHECK (progress_pct IS NULL OR (progress_pct >= 0 AND progress_pct <= 100));

    -- 2. progress_reports
    ALTER TABLE progress_reports
      ADD CONSTRAINT progress_reports_pct CHECK (pct_before >= 0 AND pct_before <= 100 AND pct_after >= 0 AND pct_after <= 100 AND pct_after >= pct_before),
      ADD CONSTRAINT progress_reports_report_date CHECK (report_date ~ '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$'),
      ADD CONSTRAINT progress_reports_photo_count CHECK (photo_count IS NULL OR (photo_count >= 0 AND photo_count <= 5));

    CREATE OR REPLACE FUNCTION pk_progress_report_insert() RETURNS trigger LANGUAGE plpgsql AS $fn$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM project_stages s WHERE s.id = NEW.stage_id AND s.project_id = NEW.project_id) THEN
        RAISE EXCEPTION 'progress_reports: stage % is not a stage of project %', NEW.stage_id, NEW.project_id USING ERRCODE = '23514';
      END IF;
      NEW.received_at := clock_timestamp();
      NEW.editable_until := NEW.received_at + interval '24 hours';
      RETURN NEW;
    END
    $fn$;
    CREATE TRIGGER progress_reports_insert BEFORE INSERT ON progress_reports FOR EACH ROW EXECUTE FUNCTION pk_progress_report_insert();

    CREATE OR REPLACE FUNCTION pk_progress_report_window() RETURNS trigger LANGUAGE plpgsql AS $fn$
    BEGIN
      IF OLD.editable_until IS NOT NULL AND clock_timestamp() > OLD.editable_until THEN
        RAISE EXCEPTION 'progress_reports: edit window (24 h) closed' USING ERRCODE = '42501';
      END IF;
      RETURN NEW;
    END
    $fn$;
    CREATE TRIGGER progress_reports_window BEFORE UPDATE ON progress_reports FOR EACH ROW EXECUTE FUNCTION pk_progress_report_window();
    CREATE TRIGGER progress_reports_no_delete BEFORE DELETE ON progress_reports FOR EACH ROW EXECUTE FUNCTION pk_reject_mutation();
    CREATE TRIGGER progress_reports_no_truncate BEFORE TRUNCATE ON progress_reports FOR EACH STATEMENT EXECUTE FUNCTION pk_reject_mutation();
    CREATE TRIGGER progress_reports_protect BEFORE UPDATE ON progress_reports FOR EACH ROW EXECUTE FUNCTION pk_protect_columns(
      'doc_no', 'project_id', 'stage_id', 'reporter_id', 'report_date', 'pct_before', 'project_pct_before',
      'received_at', 'editable_until', 'device_time', 'time_trust', 'offline', 'source', 'client_uuid', 'uuid');

    -- 3. photos of a report
    CREATE TRIGGER media_progress_photos_owner_protect BEFORE UPDATE ON media_progress_photos FOR EACH ROW EXECUTE FUNCTION pk_protect_columns('owner_doc_type', 'owner_doc_id');
    CREATE OR REPLACE FUNCTION pk_progress_photo_limit() RETURNS trigger LANGUAGE plpgsql AS $fn$
    BEGIN
      IF NEW.owner_doc_type = 'progress_report' AND NEW.owner_doc_id IS NOT NULL AND NEW.owner_doc_id IS DISTINCT FROM OLD.owner_doc_id THEN
        PERFORM pg_advisory_xact_lock(hashtextextended('pk-progress-photos:' || NEW.owner_doc_id, 0));
        IF (SELECT count(*) FROM media_progress_photos m
             WHERE m.owner_doc_type = 'progress_report' AND m.owner_doc_id = NEW.owner_doc_id AND m.id <> NEW.id) >= 5 THEN
          RAISE EXCEPTION 'progress report % already has 5 photos', NEW.owner_doc_id USING ERRCODE = '23514';
        END IF;
      END IF;
      RETURN NEW;
    END
    $fn$;
    CREATE TRIGGER media_progress_photos_limit BEFORE UPDATE ON media_progress_photos FOR EACH ROW EXECUTE FUNCTION pk_progress_photo_limit();

    DO $pk$
    DECLARE
      app_role text := regexp_replace(current_user, '_owner$', '_app');
    BEGIN
      EXECUTE format('REVOKE DELETE, TRUNCATE ON progress_reports FROM %I', app_role);
    END
    $pk$;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    DROP TRIGGER IF EXISTS media_progress_photos_limit ON media_progress_photos;
    DROP TRIGGER IF EXISTS media_progress_photos_owner_protect ON media_progress_photos;
    DROP FUNCTION IF EXISTS pk_progress_photo_limit();
    DROP TRIGGER IF EXISTS projects_progress_guard ON projects;
    DROP TRIGGER IF EXISTS project_stages_progress_guard ON project_stages;
    ALTER TABLE projects DROP CONSTRAINT IF EXISTS projects_progress_pct_range;
    ALTER TABLE project_stages DROP CONSTRAINT IF EXISTS project_stages_progress_pct_range;
  `)
  await db.execute(sql`
   ALTER TABLE "progress_reports" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "progress_reports" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_progress_reports_fk";
  
  DROP INDEX "project_stages_active_idx";
  DROP INDEX "payload_locked_documents_rels_progress_reports_id_idx";
  ALTER TABLE "projects" DROP COLUMN "progress_pct";
  ALTER TABLE "project_stages" DROP COLUMN "active";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "progress_reports_id";
  ALTER TABLE "company_settings" DROP COLUMN "sync_progress_reports_enabled";
  DROP TYPE "public"."enum_progress_reports_time_trust";
  DROP TYPE "public"."enum_progress_reports_source";`)
  await db.execute(sql`
    DROP FUNCTION IF EXISTS pk_progress_guard();
    DROP FUNCTION IF EXISTS pk_progress_report_insert();
    DROP FUNCTION IF EXISTS pk_progress_report_window();
  `)
}
