import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/**
 * S2 web B (plan fase1-golive E6 retensi selfie + E7 pengingat terjadwal). Generated by
 * `payload migrate:create s2b_attendance_reminders` (reviewed) + hand-written guards (second
 * statement), run as <prefix>_owner. ADDITIVE / staging-safe: nullable or defaulted columns, two new
 * non-collection tables, enum values for the new audit action and job. No existing row is rewritten.
 *
 * - media_selfies.removed_at: tombstone of the retention job (file deleted); immutable once set.
 * - company_settings: selfie deletion switch (default OFF) + batch; reminder settings.
 * - reminder_deliveries: de-duplication of the E7 reminders (one row per rule/subject/period/user);
 *   append-only for the app role (INSERT/SELECT only).
 * - reminder_runs: one row per business day the reminder job completed (summary counts).
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_audit_logs_action" ADD VALUE IF NOT EXISTS 'retention_purge';
  ALTER TYPE "public"."enum_payload_jobs_log_task_slug" ADD VALUE IF NOT EXISTS 'dailyReminders';
  ALTER TYPE "public"."enum_payload_jobs_task_slug" ADD VALUE IF NOT EXISTS 'dailyReminders';
  ALTER TABLE "media_selfies" ADD COLUMN "removed_at" timestamp(3) with time zone;
  ALTER TABLE "company_settings" ADD COLUMN "selfie_retention_delete_enabled" boolean DEFAULT false;
  ALTER TABLE "company_settings" ADD COLUMN "selfie_retention_batch" numeric DEFAULT 200 NOT NULL;
  ALTER TABLE "company_settings" ADD COLUMN "reminders_enabled" boolean DEFAULT true;
  ALTER TABLE "company_settings" ADD COLUMN "reminder_hour" numeric DEFAULT 7 NOT NULL;
  ALTER TABLE "company_settings" ADD COLUMN "reminder_email_enabled" boolean DEFAULT false;
  ALTER TABLE "company_settings" ADD COLUMN "reminder_late_progress_enabled" boolean DEFAULT true;
  ALTER TABLE "company_settings" ADD COLUMN "reminder_lpj_overdue_enabled" boolean DEFAULT true;
  ALTER TABLE "company_settings" ADD COLUMN "reminder_revision_enabled" boolean DEFAULT true;
  ALTER TABLE "company_settings" ADD COLUMN "reminder_revision_days" numeric DEFAULT 3 NOT NULL;
  ALTER TABLE "company_settings" ADD COLUMN "reminder_budget_enabled" boolean DEFAULT true;
  CREATE INDEX "media_selfies_removed_at_idx" ON "media_selfies" USING btree ("removed_at");`)

  await db.execute(sql`
    DO $pk$
    BEGIN
      IF current_user !~ '_owner$' THEN
        RAISE EXCEPTION 'migrations must run as the <prefix>_owner role (current_user=%)', current_user;
      END IF;
    END
    $pk$;

    CREATE TRIGGER media_selfies_removed_protect BEFORE UPDATE ON media_selfies FOR EACH ROW EXECUTE FUNCTION pk_protect_columns('removed_at');

    ALTER TABLE company_settings ADD CONSTRAINT company_settings_selfie_retention_batch CHECK (selfie_retention_batch BETWEEN 10 AND 2000);
    ALTER TABLE company_settings ADD CONSTRAINT company_settings_reminder_hour CHECK (reminder_hour BETWEEN 0 AND 23);
    ALTER TABLE company_settings ADD CONSTRAINT company_settings_reminder_revision_days CHECK (reminder_revision_days BETWEEN 1 AND 60);

    CREATE TABLE reminder_deliveries (
      rule         text        NOT NULL CHECK (rule IN ('late_progress', 'lpj_overdue', 'revision_pending', 'budget_threshold')),
      subject_key  text        NOT NULL CHECK (length(subject_key) BETWEEN 1 AND 64),
      period_key   text        NOT NULL CHECK (length(period_key) BETWEEN 1 AND 32),
      user_id      integer     NOT NULL REFERENCES users(id),
      created_at   timestamptz NOT NULL DEFAULT clock_timestamp(),
      PRIMARY KEY (rule, subject_key, period_key, user_id)
    );
    CREATE INDEX reminder_deliveries_created_idx ON reminder_deliveries (created_at);
    CREATE TRIGGER reminder_deliveries_no_update BEFORE UPDATE ON reminder_deliveries FOR EACH ROW EXECUTE FUNCTION pk_reject_mutation();

    CREATE TABLE reminder_runs (
      run_date    text        PRIMARY KEY CHECK (run_date ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'),
      finished_at timestamptz NOT NULL DEFAULT clock_timestamp(),
      summary     jsonb       NOT NULL DEFAULT '{}'::jsonb
    );

    DO $pk$
    DECLARE
      app_role text := regexp_replace(current_user, '_owner$', '_app');
    BEGIN
      EXECUTE format('REVOKE UPDATE, DELETE, TRUNCATE ON reminder_deliveries FROM %I', app_role);
      EXECUTE format('REVOKE DELETE, TRUNCATE ON reminder_runs FROM %I', app_role);
    END
    $pk$;
  `)
}

/**
 * Rollback (dry-run tested on the throwaway DB). Refused once a `retention_purge` audit row exists
 * (audit_logs is append-only, the enum value cannot be removed): restore the pre-migration dump
 * instead (plan fase1-golive §11).
 */
export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE IF EXISTS reminder_runs;
  DROP TABLE IF EXISTS reminder_deliveries;
  DROP TRIGGER IF EXISTS media_selfies_removed_protect ON media_selfies;
  ALTER TABLE company_settings DROP CONSTRAINT IF EXISTS company_settings_selfie_retention_batch;
  ALTER TABLE company_settings DROP CONSTRAINT IF EXISTS company_settings_reminder_hour;
  ALTER TABLE company_settings DROP CONSTRAINT IF EXISTS company_settings_reminder_revision_days;
   ALTER TABLE "audit_logs" ALTER COLUMN "action" SET DATA TYPE text;
  DROP TYPE "public"."enum_audit_logs_action";
  CREATE TYPE "public"."enum_audit_logs_action" AS ENUM('create', 'update', 'status_change', 'deactivate', 'reactivate', 'delete_attempt', 'void', 'view_sensitive', 'login', 'logout', 'login_failed', 'session_revoked', 'role_change', 'role_sync', 'device_register', 'device_revoke', 'number_issued', 'export', 'print', 'sign', 'acknowledge', 'flag_raised', 'flag_reviewed', 'sync_odoo', 'sync_offline', 'period_close', 'period_reopen', 'schema_maintenance', 'email_test', 'approve', 'reject', 'verify', 'acknowledge_delegated', 'access_denied', 'approval_skipped');
  ALTER TABLE "audit_logs" ALTER COLUMN "action" SET DATA TYPE "public"."enum_audit_logs_action" USING "action"::"public"."enum_audit_logs_action";
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug" SET DATA TYPE text;
  DROP TYPE "public"."enum_payload_jobs_log_task_slug";
  CREATE TYPE "public"."enum_payload_jobs_log_task_slug" AS ENUM('inline', 'auditDailyAnchor', 'sendEmail', 'reimburseAutoClose', 'selfieRetention');
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug" SET DATA TYPE "public"."enum_payload_jobs_log_task_slug" USING "task_slug"::"public"."enum_payload_jobs_log_task_slug";
  ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug" SET DATA TYPE text;
  DROP TYPE "public"."enum_payload_jobs_task_slug";
  CREATE TYPE "public"."enum_payload_jobs_task_slug" AS ENUM('inline', 'auditDailyAnchor', 'sendEmail', 'reimburseAutoClose', 'selfieRetention');
  ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug" SET DATA TYPE "public"."enum_payload_jobs_task_slug" USING "task_slug"::"public"."enum_payload_jobs_task_slug";
  DROP INDEX "media_selfies_removed_at_idx";
  ALTER TABLE "media_selfies" DROP COLUMN "removed_at";
  ALTER TABLE "company_settings" DROP COLUMN "selfie_retention_delete_enabled";
  ALTER TABLE "company_settings" DROP COLUMN "selfie_retention_batch";
  ALTER TABLE "company_settings" DROP COLUMN "reminders_enabled";
  ALTER TABLE "company_settings" DROP COLUMN "reminder_hour";
  ALTER TABLE "company_settings" DROP COLUMN "reminder_email_enabled";
  ALTER TABLE "company_settings" DROP COLUMN "reminder_late_progress_enabled";
  ALTER TABLE "company_settings" DROP COLUMN "reminder_lpj_overdue_enabled";
  ALTER TABLE "company_settings" DROP COLUMN "reminder_revision_enabled";
  ALTER TABLE "company_settings" DROP COLUMN "reminder_revision_days";
  ALTER TABLE "company_settings" DROP COLUMN "reminder_budget_enabled";`)
}
