import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/** Same name as seed/data.ts ADDENDUM_DEFAULT_RULE_NAME (unit test keeps them equal). */
export const ADDENDUM_DEFAULT_RULE_NAME = 'Default Addendum RAB — Direktur lalu Finance'

/**
 * E5 — Addendum RAB (T12, US-18/US-30, plan fase1-golive §E5, architecture §4.3/§5.4).
 * Generated by `payload migrate:create e5_budget_addenda` (reviewed) + hand-written guards and data
 * (one migration, run as <prefix>_owner). ADDITIVE / staging-safe: one new table, two new nullable
 * columns (approvals.addendum_id, payload_locked_documents_rels.budget_addenda_id), approvals.request_id
 * becomes nullable (every existing row keeps its request; a CHECK now requires exactly one owner per
 * docType), one approval rule row inserted when missing. No existing row is rewritten.
 *
 * Guards (defence in depth behind domain/addendum/service.ts):
 * 1. approvals: owner CHECK per docType; the G1 trigger also refuses a decision by the addendum's
 *    creator; one decision per (addendum, cycle, position, level); one position per person.
 * 2. budget_addenda: rows are inserted as Draft only; status transitions whitelisted; addition /
 *    reason frozen after Draft; terminal rows (approved/rejected/cancelled) immutable; project,
 *    creator, number and uuid immutable once set; approved ⇔ new_budget = old_budget + addition;
 *    addition integer > 0; no DELETE/TRUNCATE for the app role.
 * 3. Data: default rule "Default Addendum RAB — Direktur lalu Finance" (docType budget_addendum, Direktur "Diketahui"
 *    → Finance level 1) when no rule of that name exists, with an audit row (source system).
 */
const REASON = 'E5 Addendum RAB — aturan default Direktur lalu Finance (Sprint S2, ADR 0013 O-3)'
const lit = (v: string): string => `'${v.replace(/'/g, "''")}'`

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_budget_addenda_status" AS ENUM('draft', 'pending_ack', 'pending_approval', 'approved', 'rejected', 'cancelled');
  CREATE TYPE "public"."enum_budget_addenda_source" AS ENUM('web', 'apk');
  CREATE TABLE "budget_addenda" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"doc_no" varchar,
  	"project_id" integer NOT NULL,
  	"status" "enum_budget_addenda_status" DEFAULT 'draft' NOT NULL,
  	"addition" numeric NOT NULL,
  	"reason" varchar NOT NULL,
  	"budget_at_submit" numeric,
  	"old_budget" numeric,
  	"new_budget" numeric,
  	"created_by_id" integer NOT NULL,
  	"submitted_at" timestamp(3) with time zone,
  	"decided_at" timestamp(3) with time zone,
  	"approval_rule_id" integer,
  	"approval_snapshot" jsonb,
  	"approval_cycle" numeric DEFAULT 0,
  	"current_level" numeric,
  	"reject_reason" varchar,
  	"cancel_reason" varchar,
  	"source" "enum_budget_addenda_source",
  	"uuid" varchar,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "approvals" ALTER COLUMN "request_id" DROP NOT NULL;
  ALTER TABLE "approvals" ADD COLUMN "addendum_id" integer;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "budget_addenda_id" integer;
  ALTER TABLE "budget_addenda" ADD CONSTRAINT "budget_addenda_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "budget_addenda" ADD CONSTRAINT "budget_addenda_created_by_id_users_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "budget_addenda" ADD CONSTRAINT "budget_addenda_approval_rule_id_approval_rules_id_fk" FOREIGN KEY ("approval_rule_id") REFERENCES "public"."approval_rules"("id") ON DELETE set null ON UPDATE no action;
  CREATE UNIQUE INDEX "budget_addenda_doc_no_idx" ON "budget_addenda" USING btree ("doc_no");
  CREATE INDEX "budget_addenda_project_idx" ON "budget_addenda" USING btree ("project_id");
  CREATE INDEX "budget_addenda_status_idx" ON "budget_addenda" USING btree ("status");
  CREATE INDEX "budget_addenda_created_by_idx" ON "budget_addenda" USING btree ("created_by_id");
  CREATE INDEX "budget_addenda_approval_rule_idx" ON "budget_addenda" USING btree ("approval_rule_id");
  CREATE UNIQUE INDEX "budget_addenda_uuid_idx" ON "budget_addenda" USING btree ("uuid");
  CREATE INDEX "budget_addenda_updated_at_idx" ON "budget_addenda" USING btree ("updated_at");
  CREATE INDEX "budget_addenda_created_at_idx" ON "budget_addenda" USING btree ("created_at");
  ALTER TABLE "approvals" ADD CONSTRAINT "approvals_addendum_id_budget_addenda_id_fk" FOREIGN KEY ("addendum_id") REFERENCES "public"."budget_addenda"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_budget_addenda_fk" FOREIGN KEY ("budget_addenda_id") REFERENCES "public"."budget_addenda"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "approvals_addendum_idx" ON "approvals" USING btree ("addendum_id");
  CREATE INDEX "payload_locked_documents_rels_budget_addenda_id_idx" ON "payload_locked_documents_rels" USING btree ("budget_addenda_id");`)

  await db.execute(sql`
    DO $pk$
    BEGIN
      IF current_user !~ '_owner$' THEN
        RAISE EXCEPTION 'migrations must run as the <prefix>_owner role (current_user=%)', current_user;
      END IF;
    END
    $pk$;

    -- 1. approvals: one owner per docType, G1 for addenda, uniqueness like expense requests
    ALTER TABLE approvals ADD CONSTRAINT approvals_owner_doc CHECK (
      (doc_type = 'expense_request' AND request_id IS NOT NULL AND addendum_id IS NULL)
      OR (doc_type = 'budget_addendum' AND addendum_id IS NOT NULL AND request_id IS NULL));
    CREATE OR REPLACE FUNCTION pk_approvals_before_insert() RETURNS trigger LANGUAGE plpgsql AS $fn$
    DECLARE
      creator integer;
    BEGIN
      NEW.decided_at := clock_timestamp();
      IF NEW.position IN ('diketahui', 'approval') THEN
        IF NEW.doc_type = 'budget_addendum' THEN
          SELECT created_by_id INTO creator FROM budget_addenda WHERE id = NEW.addendum_id;
          IF NEW.actor_id IS NULL OR creator IS NULL OR NEW.actor_id = creator THEN
            RAISE EXCEPTION 'approvals: the addendum creator cannot hold a decision position (G1)' USING ERRCODE = '42501';
          END IF;
          RETURN NEW;
        END IF;
        SELECT created_by_id INTO creator FROM expense_requests WHERE id = NEW.request_id;
        IF NEW.actor_id IS NULL OR NEW.actor_id = creator OR EXISTS (
             SELECT 1 FROM expense_requests_rels r JOIN users u ON u.employee_id = r.employees_id
             WHERE r.parent_id = NEW.request_id AND r.path = 'requesters' AND u.id = NEW.actor_id) THEN
          RAISE EXCEPTION 'approvals: requester/creator cannot hold a decision position (G1)' USING ERRCODE = '42501';
        END IF;
      END IF;
      RETURN NEW;
    END
    $fn$;
    CREATE UNIQUE INDEX approvals_addendum_one_decision_per_level ON approvals (addendum_id, cycle, position, level)
      WHERE addendum_id IS NOT NULL AND decision IN ('acknowledged', 'approved', 'rejected');
    CREATE UNIQUE INDEX approvals_addendum_one_position_per_person ON approvals (addendum_id, cycle, actor_id)
      WHERE addendum_id IS NOT NULL AND position IN ('diketahui', 'approval');

    -- 2. budget_addenda
    ALTER TABLE budget_addenda
      ADD CONSTRAINT budget_addenda_addition CHECK (addition > 0 AND addition = trunc(addition)),
      ADD CONSTRAINT budget_addenda_budgets CHECK (
        (budget_at_submit IS NULL OR (budget_at_submit >= 0 AND budget_at_submit = trunc(budget_at_submit)))
        AND (old_budget IS NULL OR (old_budget >= 0 AND old_budget = trunc(old_budget)))),
      ADD CONSTRAINT budget_addenda_approved CHECK (
        (status = 'approved' AND old_budget IS NOT NULL AND new_budget = old_budget + addition)
        OR (status <> 'approved' AND old_budget IS NULL AND new_budget IS NULL)),
      ADD CONSTRAINT budget_addenda_numbered CHECK (status IN ('draft', 'cancelled') OR doc_no IS NOT NULL);

    CREATE OR REPLACE FUNCTION pk_budget_addenda_guard() RETURNS trigger LANGUAGE plpgsql AS $fn$
    DECLARE
      allowed text[];
    BEGIN
      IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'draft' THEN
          RAISE EXCEPTION 'budget_addenda: new rows start as draft' USING ERRCODE = '42501';
        END IF;
        RETURN NEW;
      END IF;
      IF OLD.status IN ('approved', 'rejected', 'cancelled') THEN
        IF (to_jsonb(NEW) - 'updated_at') IS DISTINCT FROM (to_jsonb(OLD) - 'updated_at') THEN
          RAISE EXCEPTION 'budget_addenda: % is final', OLD.status USING ERRCODE = '42501';
        END IF;
        RETURN NEW;
      END IF;
      IF NEW.status IS DISTINCT FROM OLD.status THEN
        allowed := CASE OLD.status::text
          WHEN 'draft' THEN ARRAY['pending_ack', 'pending_approval', 'cancelled']
          WHEN 'pending_ack' THEN ARRAY['pending_approval', 'approved', 'rejected', 'cancelled']
          WHEN 'pending_approval' THEN ARRAY['approved', 'rejected', 'cancelled']
          ELSE ARRAY[]::text[] END;
        IF NOT (NEW.status::text = ANY (allowed)) THEN
          RAISE EXCEPTION 'budget_addenda: transition % -> % not allowed', OLD.status, NEW.status USING ERRCODE = '42501';
        END IF;
      END IF;
      IF OLD.status <> 'draft' AND (NEW.addition IS DISTINCT FROM OLD.addition OR NEW.reason IS DISTINCT FROM OLD.reason) THEN
        RAISE EXCEPTION 'budget_addenda: content is frozen after submit' USING ERRCODE = '42501';
      END IF;
      RETURN NEW;
    END
    $fn$;
    CREATE TRIGGER budget_addenda_guard BEFORE INSERT OR UPDATE ON budget_addenda FOR EACH ROW EXECUTE FUNCTION pk_budget_addenda_guard();
    CREATE TRIGGER budget_addenda_protect BEFORE UPDATE ON budget_addenda FOR EACH ROW EXECUTE FUNCTION pk_protect_columns('uuid', 'doc_no', 'project_id', 'created_by_id');
    CREATE TRIGGER budget_addenda_no_delete BEFORE DELETE ON budget_addenda FOR EACH ROW EXECUTE FUNCTION pk_reject_mutation();
    CREATE TRIGGER budget_addenda_no_truncate BEFORE TRUNCATE ON budget_addenda FOR EACH STATEMENT EXECUTE FUNCTION pk_reject_mutation();

    DO $pk$
    DECLARE
      app_role text := regexp_replace(current_user, '_owner$', '_app');
    BEGIN
      EXECUTE format('REVOKE DELETE, TRUNCATE ON budget_addenda FROM %I', app_role);
    END
    $pk$;
  `)

  // 3. default rule (constants of this file only → literals in a DO block)
  await db.execute(
    sql.raw(`
    DO $pk$
    DECLARE
      rid integer;
    BEGIN
      SELECT id INTO rid FROM approval_rules WHERE name = ${lit(ADDENDUM_DEFAULT_RULE_NAME)} ORDER BY id LIMIT 1;
      IF FOUND THEN
        -- re-run after a down (which only deactivates the row): activate it again, audited
        UPDATE approval_rules SET active = true, updated_at = now() WHERE id = rid AND active IS NOT TRUE;
        IF FOUND THEN
          INSERT INTO audit_logs (event_id, tx_id, doc_type, doc_id, action, field, old_value, new_value, reason, source)
          VALUES (gen_random_uuid()::text, txid_current(), 'approval_rule', rid::text, 'reactivate', 'active', jsonb_build_object('v', false), jsonb_build_object('v', true), ${lit(REASON)}, 'system');
        END IF;
        RETURN;
      END IF;
      INSERT INTO approval_rules (name, doc_type, request_type, min_amount, priority, acknowledge, acknowledge_by, acknowledge_role, sign_diajukan, sign_dibuat, active)
      VALUES (${lit(ADDENDUM_DEFAULT_RULE_NAME)}, 'budget_addendum', 'any', 0, 100, 'required', 'role', 'pk-owner', 'none', 'none', true)
      RETURNING id INTO rid;
      INSERT INTO approval_rules_steps (_order, _parent_id, id, level, approver_role)
      VALUES (1, rid, substr(md5(random()::text || clock_timestamp()::text), 1, 24), 1, 'pk-finance');
      INSERT INTO audit_logs (event_id, tx_id, doc_type, doc_id, action, field, new_value, reason, source)
      VALUES (gen_random_uuid()::text, txid_current(), 'approval_rule', rid::text, 'create', 'name', jsonb_build_object('v', ${lit(ADDENDUM_DEFAULT_RULE_NAME)}::text), ${lit(REASON)}, 'system');
    END
    $pk$;`),
  )
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  // Addendum decision rows are append-only (trigger); they only exist for addenda, which this down
  // drops → removed with the trigger disabled for this statement only (owner role).
  await db.execute(sql`
    ALTER TABLE approvals DISABLE TRIGGER approvals_no_update;
    DELETE FROM approvals WHERE doc_type = 'budget_addendum';
    ALTER TABLE approvals ENABLE TRIGGER approvals_no_update;
    ALTER TABLE approvals DROP CONSTRAINT IF EXISTS approvals_owner_doc;
    DROP INDEX IF EXISTS approvals_addendum_one_decision_per_level;
    DROP INDEX IF EXISTS approvals_addendum_one_position_per_person;
    CREATE OR REPLACE FUNCTION pk_approvals_before_insert() RETURNS trigger LANGUAGE plpgsql AS $fn$
    DECLARE
      creator integer;
    BEGIN
      NEW.decided_at := clock_timestamp();
      IF NEW.position IN ('diketahui', 'approval') THEN
        SELECT created_by_id INTO creator FROM expense_requests WHERE id = NEW.request_id;
        IF NEW.actor_id IS NULL OR NEW.actor_id = creator OR EXISTS (
             SELECT 1 FROM expense_requests_rels r JOIN users u ON u.employee_id = r.employees_id
             WHERE r.parent_id = NEW.request_id AND r.path = 'requesters' AND u.id = NEW.actor_id) THEN
          RAISE EXCEPTION 'approvals: requester/creator cannot hold a decision position (G1)' USING ERRCODE = '42501';
        END IF;
      END IF;
      RETURN NEW;
    END
    $fn$;
  `)
  // The default addendum rule row is kept (inactive): approval_rules has no DELETE path (G4).
  await db.execute(sql.raw(`UPDATE approval_rules SET active = false WHERE name = ${lit(ADDENDUM_DEFAULT_RULE_NAME)};`))
  await db.execute(sql`
   ALTER TABLE "budget_addenda" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "budget_addenda" CASCADE;
  ALTER TABLE "approvals" DROP CONSTRAINT IF EXISTS "approvals_addendum_id_budget_addenda_id_fk"; -- already dropped by DROP TABLE … CASCADE
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_budget_addenda_fk"; -- already dropped by DROP TABLE … CASCADE
  
  DROP INDEX "approvals_addendum_idx";
  DROP INDEX "payload_locked_documents_rels_budget_addenda_id_idx";
  ALTER TABLE "approvals" ALTER COLUMN "request_id" SET NOT NULL;
  ALTER TABLE "approvals" DROP COLUMN "addendum_id";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "budget_addenda_id";
  DROP TYPE "public"."enum_budget_addenda_status";
  DROP TYPE "public"."enum_budget_addenda_source";`)
  await db.execute(sql`DROP FUNCTION IF EXISTS pk_budget_addenda_guard();`)
}
