import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/**
 * E6 — absensi lengkap (plan fase1-golive E6; US-09/13/14/15, Q-30/33/40). Generated by
 * `payload migrate:create e6_attendance` (reviewed) + hand-written guards (second statement), run as
 * <prefix>_owner. ADDITIVE / staging-safe: new table `attendance_corrections`, nullable/defaulted
 * columns, two relaxed NOT NULLs on `attendances` (user_id: on-behalf of an employee without an
 * account; project_id: cost-center attendance), two enum values for the new job. No existing row is
 * rewritten (ADD COLUMN with a constant default does not fire the attendances no-update trigger).
 *
 * Guards:
 * - attendances: exactly one of project_id / cost_center_id; source `self` needs user_id, source `pm`
 *   needs recorded_by_id + a reason; one check-in/out per employee/cost center/local date (the
 *   project variant exists since f4b_attendance_security).
 * - attendance_corrections (T10): append-only for everyone (reject triggers + no UPDATE/DELETE/
 *   TRUNCATE for the app role), corrected_at = DB clock, reason ≥ 3 characters, and the row must
 *   match its attendance (employee, kind, local date, project/cost center).
 * - company_settings.selfie_retention_months within 1–120.
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_attendances_source" AS ENUM('self', 'pm');
  CREATE TYPE "public"."enum_attendance_corrections_kind" AS ENUM('check_in', 'check_out');
  ALTER TYPE "public"."enum_payload_jobs_log_task_slug" ADD VALUE IF NOT EXISTS 'selfieRetention';
  ALTER TYPE "public"."enum_payload_jobs_task_slug" ADD VALUE IF NOT EXISTS 'selfieRetention';
  CREATE TABLE "attendance_corrections" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"attendance_id" integer NOT NULL,
  	"employee_id" integer NOT NULL,
  	"project_id" integer,
  	"cost_center_id" integer,
  	"kind" "enum_attendance_corrections_kind" NOT NULL,
  	"local_date" varchar NOT NULL,
  	"old_time" timestamp(3) with time zone NOT NULL,
  	"new_time" timestamp(3) with time zone NOT NULL,
  	"reason" varchar NOT NULL,
  	"corrected_by_id" integer NOT NULL,
  	"corrected_at" timestamp(3) with time zone NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "attendances" ALTER COLUMN "user_id" DROP NOT NULL;
  ALTER TABLE "attendances" ALTER COLUMN "project_id" DROP NOT NULL;
  ALTER TABLE "employees" ADD COLUMN "work_schedule_id" integer;
  ALTER TABLE "work_schedules" ADD COLUMN "work_days_mon" boolean DEFAULT true;
  ALTER TABLE "work_schedules" ADD COLUMN "work_days_tue" boolean DEFAULT true;
  ALTER TABLE "work_schedules" ADD COLUMN "work_days_wed" boolean DEFAULT true;
  ALTER TABLE "work_schedules" ADD COLUMN "work_days_thu" boolean DEFAULT true;
  ALTER TABLE "work_schedules" ADD COLUMN "work_days_fri" boolean DEFAULT true;
  ALTER TABLE "work_schedules" ADD COLUMN "work_days_sat" boolean DEFAULT true;
  ALTER TABLE "work_schedules" ADD COLUMN "work_days_sun" boolean DEFAULT false;
  ALTER TABLE "cost_centers" ADD COLUMN "lat" numeric;
  ALTER TABLE "cost_centers" ADD COLUMN "lng" numeric;
  ALTER TABLE "cost_centers" ADD COLUMN "radius_m" numeric;
  ALTER TABLE "attendances" ADD COLUMN "cost_center_id" integer;
  ALTER TABLE "attendances" ADD COLUMN "source" "enum_attendances_source" DEFAULT 'self' NOT NULL;
  ALTER TABLE "attendances" ADD COLUMN "recorded_by_id" integer;
  ALTER TABLE "attendances" ADD COLUMN "on_behalf_reason" varchar;
  ALTER TABLE "attendances" ADD COLUMN "schedule" jsonb;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "attendance_corrections_id" integer;
  ALTER TABLE "company_settings" ADD COLUMN "default_work_schedule_id" integer;
  ALTER TABLE "company_settings" ADD COLUMN "selfie_retention_months" numeric DEFAULT 12 NOT NULL;
  ALTER TABLE "attendance_corrections" ADD CONSTRAINT "attendance_corrections_attendance_id_attendances_id_fk" FOREIGN KEY ("attendance_id") REFERENCES "public"."attendances"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "attendance_corrections" ADD CONSTRAINT "attendance_corrections_employee_id_employees_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employees"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "attendance_corrections" ADD CONSTRAINT "attendance_corrections_project_id_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "attendance_corrections" ADD CONSTRAINT "attendance_corrections_cost_center_id_cost_centers_id_fk" FOREIGN KEY ("cost_center_id") REFERENCES "public"."cost_centers"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "attendance_corrections" ADD CONSTRAINT "attendance_corrections_corrected_by_id_users_id_fk" FOREIGN KEY ("corrected_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "attendance_corrections_attendance_idx" ON "attendance_corrections" USING btree ("attendance_id");
  CREATE INDEX "attendance_corrections_employee_idx" ON "attendance_corrections" USING btree ("employee_id");
  CREATE INDEX "attendance_corrections_project_idx" ON "attendance_corrections" USING btree ("project_id");
  CREATE INDEX "attendance_corrections_cost_center_idx" ON "attendance_corrections" USING btree ("cost_center_id");
  CREATE INDEX "attendance_corrections_local_date_idx" ON "attendance_corrections" USING btree ("local_date");
  CREATE INDEX "attendance_corrections_corrected_by_idx" ON "attendance_corrections" USING btree ("corrected_by_id");
  CREATE INDEX "attendance_corrections_updated_at_idx" ON "attendance_corrections" USING btree ("updated_at");
  CREATE INDEX "attendance_corrections_created_at_idx" ON "attendance_corrections" USING btree ("created_at");
  ALTER TABLE "employees" ADD CONSTRAINT "employees_work_schedule_id_work_schedules_id_fk" FOREIGN KEY ("work_schedule_id") REFERENCES "public"."work_schedules"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "attendances" ADD CONSTRAINT "attendances_cost_center_id_cost_centers_id_fk" FOREIGN KEY ("cost_center_id") REFERENCES "public"."cost_centers"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "attendances" ADD CONSTRAINT "attendances_recorded_by_id_users_id_fk" FOREIGN KEY ("recorded_by_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_attendance_corrections_fk" FOREIGN KEY ("attendance_corrections_id") REFERENCES "public"."attendance_corrections"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "company_settings" ADD CONSTRAINT "company_settings_default_work_schedule_id_work_schedules_id_fk" FOREIGN KEY ("default_work_schedule_id") REFERENCES "public"."work_schedules"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "employees_work_schedule_idx" ON "employees" USING btree ("work_schedule_id");
  CREATE INDEX "attendances_cost_center_idx" ON "attendances" USING btree ("cost_center_id");
  CREATE INDEX "attendances_source_idx" ON "attendances" USING btree ("source");
  CREATE INDEX "attendances_recorded_by_idx" ON "attendances" USING btree ("recorded_by_id");
  CREATE INDEX "payload_locked_documents_rels_attendance_corrections_id_idx" ON "payload_locked_documents_rels" USING btree ("attendance_corrections_id");
  CREATE INDEX "company_settings_default_work_schedule_idx" ON "company_settings" USING btree ("default_work_schedule_id");`)

  await db.execute(sql`
    DO $pk$
    BEGIN
      IF current_user !~ '_owner$' THEN
        RAISE EXCEPTION 'migrations must run as the <prefix>_owner role (current_user=%)', current_user;
      END IF;
    END
    $pk$;

    ALTER TABLE attendances ADD CONSTRAINT attendances_one_location CHECK ((project_id IS NULL) <> (cost_center_id IS NULL));
    ALTER TABLE attendances ADD CONSTRAINT attendances_source_fields CHECK (
      (source = 'self' AND user_id IS NOT NULL AND recorded_by_id IS NULL)
      OR (source = 'pm' AND recorded_by_id IS NOT NULL AND length(btrim(coalesce(on_behalf_reason, ''))) >= 3)
    );
    CREATE UNIQUE INDEX attendances_one_per_day_cc ON attendances (employee_id, cost_center_id, local_date, kind) WHERE cost_center_id IS NOT NULL;

    ALTER TABLE attendance_corrections ADD CONSTRAINT attendance_corrections_reason CHECK (length(btrim(reason)) >= 3);
    CREATE OR REPLACE FUNCTION pk_attendance_correction_check() RETURNS trigger LANGUAGE plpgsql AS $fn$
    DECLARE
      a attendances%ROWTYPE;
    BEGIN
      NEW.corrected_at := clock_timestamp();
      SELECT * INTO a FROM attendances WHERE id = NEW.attendance_id;
      IF NOT FOUND OR a.employee_id IS DISTINCT FROM NEW.employee_id OR a.kind::text IS DISTINCT FROM NEW.kind::text
         OR a.local_date IS DISTINCT FROM NEW.local_date OR a.project_id IS DISTINCT FROM NEW.project_id
         OR a.cost_center_id IS DISTINCT FROM NEW.cost_center_id THEN
        RAISE EXCEPTION 'attendance_corrections: row does not match attendance %', NEW.attendance_id USING ERRCODE = '23514';
      END IF;
      RETURN NEW;
    END
    $fn$;
    CREATE TRIGGER attendance_corrections_check BEFORE INSERT ON attendance_corrections FOR EACH ROW EXECUTE FUNCTION pk_attendance_correction_check();
    CREATE TRIGGER attendance_corrections_no_update BEFORE UPDATE OR DELETE ON attendance_corrections FOR EACH ROW EXECUTE FUNCTION pk_reject_mutation();
    CREATE TRIGGER attendance_corrections_no_truncate BEFORE TRUNCATE ON attendance_corrections FOR EACH STATEMENT EXECUTE FUNCTION pk_reject_mutation();

    ALTER TABLE company_settings ADD CONSTRAINT company_settings_selfie_retention CHECK (selfie_retention_months BETWEEN 1 AND 120);

    DO $pk$
    DECLARE
      app_role text := regexp_replace(current_user, '_owner$', '_app');
    BEGIN
      EXECUTE format('REVOKE UPDATE, DELETE, TRUNCATE ON attendance_corrections FROM %I', app_role);
    END
    $pk$;
  `)
}

/**
 * Rollback (dry-run tested on the throwaway DB). Refused while "diabsenkan PM" rows without an account
 * or cost-center attendance exist (user_id / project_id become NOT NULL again): restore the
 * pre-migration dump instead (plan fase1-golive §11).
 */
export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP INDEX IF EXISTS attendances_one_per_day_cc;
  ALTER TABLE attendances DROP CONSTRAINT IF EXISTS attendances_source_fields;
  ALTER TABLE attendances DROP CONSTRAINT IF EXISTS attendances_one_location;
  ALTER TABLE company_settings DROP CONSTRAINT IF EXISTS company_settings_selfie_retention;
  ALTER TABLE "attendance_corrections" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "attendance_corrections" CASCADE;
  ALTER TABLE "employees" DROP CONSTRAINT "employees_work_schedule_id_work_schedules_id_fk";
  
  ALTER TABLE "attendances" DROP CONSTRAINT "attendances_cost_center_id_cost_centers_id_fk";
  
  ALTER TABLE "attendances" DROP CONSTRAINT "attendances_recorded_by_id_users_id_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_attendance_corrections_fk"; -- already dropped by DROP TABLE … CASCADE
  
  ALTER TABLE "company_settings" DROP CONSTRAINT "company_settings_default_work_schedule_id_work_schedules_id_fk";
  
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug" SET DATA TYPE text;
  DROP TYPE "public"."enum_payload_jobs_log_task_slug";
  CREATE TYPE "public"."enum_payload_jobs_log_task_slug" AS ENUM('inline', 'auditDailyAnchor', 'sendEmail', 'reimburseAutoClose');
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "task_slug" SET DATA TYPE "public"."enum_payload_jobs_log_task_slug" USING "task_slug"::"public"."enum_payload_jobs_log_task_slug";
  ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug" SET DATA TYPE text;
  DROP TYPE "public"."enum_payload_jobs_task_slug";
  CREATE TYPE "public"."enum_payload_jobs_task_slug" AS ENUM('inline', 'auditDailyAnchor', 'sendEmail', 'reimburseAutoClose');
  ALTER TABLE "payload_jobs" ALTER COLUMN "task_slug" SET DATA TYPE "public"."enum_payload_jobs_task_slug" USING "task_slug"::"public"."enum_payload_jobs_task_slug";
  DROP INDEX "employees_work_schedule_idx";
  DROP INDEX "attendances_cost_center_idx";
  DROP INDEX "attendances_source_idx";
  DROP INDEX "attendances_recorded_by_idx";
  DROP INDEX "payload_locked_documents_rels_attendance_corrections_id_idx";
  DROP INDEX "company_settings_default_work_schedule_idx";
  ALTER TABLE "attendances" ALTER COLUMN "user_id" SET NOT NULL;
  ALTER TABLE "attendances" ALTER COLUMN "project_id" SET NOT NULL;
  ALTER TABLE "employees" DROP COLUMN "work_schedule_id";
  ALTER TABLE "work_schedules" DROP COLUMN "work_days_mon";
  ALTER TABLE "work_schedules" DROP COLUMN "work_days_tue";
  ALTER TABLE "work_schedules" DROP COLUMN "work_days_wed";
  ALTER TABLE "work_schedules" DROP COLUMN "work_days_thu";
  ALTER TABLE "work_schedules" DROP COLUMN "work_days_fri";
  ALTER TABLE "work_schedules" DROP COLUMN "work_days_sat";
  ALTER TABLE "work_schedules" DROP COLUMN "work_days_sun";
  ALTER TABLE "cost_centers" DROP COLUMN "lat";
  ALTER TABLE "cost_centers" DROP COLUMN "lng";
  ALTER TABLE "cost_centers" DROP COLUMN "radius_m";
  ALTER TABLE "attendances" DROP COLUMN "cost_center_id";
  ALTER TABLE "attendances" DROP COLUMN "source";
  ALTER TABLE "attendances" DROP COLUMN "recorded_by_id";
  ALTER TABLE "attendances" DROP COLUMN "on_behalf_reason";
  ALTER TABLE "attendances" DROP COLUMN "schedule";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "attendance_corrections_id";
  ALTER TABLE "company_settings" DROP COLUMN "default_work_schedule_id";
  ALTER TABLE "company_settings" DROP COLUMN "selfie_retention_months";
  DROP TYPE "public"."enum_attendances_source";
  DROP TYPE "public"."enum_attendance_corrections_kind";
  DROP FUNCTION IF EXISTS pk_attendance_correction_check();`)
}
