import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres'

/**
 * E1 — approval flow Direktur → Finance, PM monitors only (ADR 0013, GATE 1 fase1-golive
 * 2026-09-26). Generated by `payload migrate:create e1_approval_direktur_finance` (reviewed) +
 * hand-written data part. ADDITIVE / staging-safe:
 *
 * 1. New `audit_logs.action` value `approval_skipped` (G1-2: a decision position skipped because its
 *    only holders are requester/creator) — `ADD VALUE IF NOT EXISTS`, same pattern as F2e.
 * 2. `approval_rules` column defaults for new rules: acknowledge `required`, acknowledge_by `role`,
 *    acknowledge_role `pk-owner` (label "Direktur"). No enum value is removed (`scope_manager` and
 *    every role stay readable for pre-E1 rules/snapshots).
 * 3. Data: the two SEEDED rules (matched by their pre-E1 names) become "Diketahui" = Direktur
 *    (`acknowledge_by = role`, `acknowledge_role = pk-owner`) → Finance level 1 (`pk-finance`), and are
 *    renamed to the names the seed now uses (so a later seed run finds them instead of adding new
 *    ones). Every changed field gets an `audit_logs` row (source `system`, reason "ADR 0013 — …"),
 *    like an audited admin edit. Other rules are NOT touched; an active rule that still uses PM
 *    "Diketahui" (scope_manager) makes matching submissions return 409 until an Admin fixes it
 *    (RAISE NOTICE with the count).
 *
 * Requests already submitted keep their snapshot (`expense_requests.approval_snapshot` is not
 * touched; US-34, AC-8): in-flight requests finish on the old flow.
 */
const RULES = [
  { oldName: 'Default — Owner (semua nominal)', newName: 'Default — Direktur lalu Finance (semua nominal)', oldLevels: 1 },
  {
    oldName: 'Contoh — di atas Rp 10 juta: 2 approver (Q-31, nonaktif)',
    newName: 'Contoh — di atas Rp 10 juta: Direktur lalu Finance (Q-31, nonaktif)',
    oldLevels: 2,
  },
] as const

const REASON = 'ADR 0013 — keputusan user 2026-09-25 (migrasi E1: Diketahui = Direktur, lalu Finance)'
const REASON_DOWN = 'rollback migrasi E1 (ADR 0013)'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  ALTER TYPE "public"."enum_audit_logs_action" ADD VALUE IF NOT EXISTS 'approval_skipped';
  ALTER TABLE "approval_rules" ALTER COLUMN "acknowledge" SET DEFAULT 'required';
  ALTER TABLE "approval_rules" ALTER COLUMN "acknowledge_by" SET DEFAULT 'role';
  ALTER TABLE "approval_rules" ALTER COLUMN "acknowledge_role" SET DEFAULT 'pk-owner';`)
  for (const r of RULES) {
    await rewriteRule(db, { fromName: r.oldName, toName: r.newName, ackBy: 'role', ackRole: 'pk-owner', steps: ['pk-finance'], reason: REASON })
  }
  await db.execute(sql`
    DO $pk$
    DECLARE n integer;
    BEGIN
      SELECT count(*) INTO n FROM approval_rules WHERE active AND acknowledge <> 'none' AND acknowledge_by = 'scope_manager';
      IF n > 0 THEN
        RAISE NOTICE 'E1/ADR 0013: % active approval rule(s) still use PM "Diketahui" (scope_manager); matching submissions return 409 until an Admin changes them', n;
      END IF;
    END
    $pk$;`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  // Enum value: hand-written no-op instead of the generated DROP/CREATE TYPE (Postgres cannot drop
  // enum values, and audit_logs is append-only, ADR 0006 — rows using `approval_skipped` can be neither
  // changed nor removed). The extra value is harmless without E1.
  await db.execute(sql`
  ALTER TABLE "approval_rules" ALTER COLUMN "acknowledge" SET DEFAULT 'optional';
  ALTER TABLE "approval_rules" ALTER COLUMN "acknowledge_by" SET DEFAULT 'scope_manager';
  ALTER TABLE "approval_rules" ALTER COLUMN "acknowledge_role" DROP DEFAULT;`)
  for (const r of RULES) {
    await rewriteRule(db, {
      fromName: r.newName,
      toName: r.oldName,
      ackBy: 'scope_manager',
      ackRole: null,
      steps: Array.from({ length: r.oldLevels }, () => 'pk-owner' as const),
      reason: REASON_DOWN,
    })
  }
}

type Db = MigrateUpArgs['db']

/** SQL literal of a constant of THIS file (never user input): quotes doubled, NULL for null. */
const lit = (v: string | null): string => (v === null ? 'NULL' : `'${v.replace(/'/g, "''")}'`)

/**
 * Rewrites one rule (found by name) and its steps; one audit row per changed field. No-op when the
 * rule does not exist (fresh database: the seed creates the new rules after the migrations).
 * A DO block cannot take bind parameters, hence the literals (constants above only).
 */
async function rewriteRule(
  db: Db,
  o: { fromName: string; toName: string; ackBy: 'role' | 'scope_manager'; ackRole: 'pk-owner' | null; steps: ReadonlyArray<'pk-finance' | 'pk-owner'>; reason: string },
): Promise<void> {
  const newSteps = JSON.stringify(o.steps.map((role, i) => ({ level: i + 1, approverRole: role, approverUser: null })))
  await db.execute(
    sql.raw(`
    DO $pk$
    DECLARE
      old record;
      old_steps jsonb;
      new_steps jsonb := ${lit(newSteps)}::jsonb;
      tx numeric := txid_current();
      ev text := gen_random_uuid()::text;
      s jsonb;
      i integer := 0;
    BEGIN
      SELECT id, name, acknowledge::text AS acknowledge, acknowledge_by::text AS acknowledge_by,
             acknowledge_role::text AS acknowledge_role, acknowledge_user_id
        INTO old FROM approval_rules WHERE name = ${lit(o.fromName)} ORDER BY id LIMIT 1;
      IF NOT FOUND THEN
        RETURN;
      END IF;
      SELECT coalesce(jsonb_agg(jsonb_build_object('level', level::int, 'approverRole', approver_role::text, 'approverUser', approver_user_id) ORDER BY _order), '[]'::jsonb)
        INTO old_steps FROM approval_rules_steps WHERE _parent_id = old.id;

      UPDATE approval_rules
         SET name = ${lit(o.toName)}, acknowledge = 'required',
             acknowledge_by = ${lit(o.ackBy)}::enum_approval_rules_acknowledge_by,
             acknowledge_role = ${lit(o.ackRole)}::enum_approval_rules_acknowledge_role,
             acknowledge_user_id = NULL, updated_at = now()
       WHERE id = old.id;
      DELETE FROM approval_rules_steps WHERE _parent_id = old.id;
      FOR s IN SELECT value FROM jsonb_array_elements(new_steps) LOOP
        i := i + 1;
        INSERT INTO approval_rules_steps (_order, _parent_id, id, level, approver_role)
        VALUES (i, old.id, substr(md5(random()::text || clock_timestamp()::text || i::text), 1, 24),
                (s->>'level')::numeric, (s->>'approverRole')::enum_approval_rules_steps_approver_role);
      END LOOP;

      INSERT INTO audit_logs (event_id, tx_id, doc_type, doc_id, action, field, old_value, new_value, reason, source)
      SELECT ev, tx, 'approval_rule', old.id::text, 'update', f.field, f.old_v, f.new_v, ${lit(o.reason)}, 'system'
        FROM (VALUES
          ('name', to_jsonb(old.name::text), to_jsonb(${lit(o.toName)}::text)),
          ('acknowledge', to_jsonb(old.acknowledge), to_jsonb('required'::text)),
          ('acknowledgeBy', to_jsonb(old.acknowledge_by), to_jsonb(${lit(o.ackBy)}::text)),
          ('acknowledgeRole', to_jsonb(old.acknowledge_role), to_jsonb(${lit(o.ackRole)}::text)),
          ('acknowledgeUser', to_jsonb(old.acknowledge_user_id), NULL::jsonb),
          ('steps', old_steps, new_steps)
        ) AS f(field, old_v, new_v)
       WHERE f.old_v IS DISTINCT FROM f.new_v;
    END
    $pk$;`),
  )
}
