arb-dir: lib/l10n
template-arb-file: app_id.arb
output-dir: lib/l10n/gen
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [id]
nullable-getter: false
