/// Fictional E4 / E6 API bodies (openapi v1 shapes). Names, codes and ids are invented.
Map<String, dynamic> progressReportJson({int id = 501, bool editable = true}) => {
  'id': id,
  'uuid': null,
  'docNo': 'LP/2609/0007',
  'project': {'id': 7, 'code': 'P-07', 'name': 'Gudang Contoh'},
  'stage': {'id': 31, 'name': 'Struktur', 'weightPct': 30},
  'reportDate': '2026-09-26',
  'pctBefore': 40,
  'pctAfter': 55.5,
  'projectPctBefore': 20,
  'projectPctAfter': 24.65,
  'work': 'Pengecoran kolom lantai 2',
  'issues': 'Hujan sore, pengecoran tertunda 1 jam',
  'reporter': {'id': 5, 'name': 'Doni Pratama'},
  'photos': [
    {'id': 901, 'width': 1600, 'height': 1200, 'filesize': 210000, 'url': '/x', 'thumbUrl': '/x?variant=thumb'},
    {'id': 902, 'width': 1600, 'height': 1200, 'filesize': 190000, 'url': '/y', 'thumbUrl': '/y?variant=thumb'},
  ],
  'offline': true,
  'timeTrust': 'estimated',
  'source': 'apk',
  'flags': ['OFFLINE'],
  'receivedAt': '2026-09-26T02:15:03Z',
  'editableUntil': '2026-09-27T02:15:03Z',
  'editable': editable,
  'rev': 1,
  'clientUuid': '0192f6d0-aaaa-7bbb-8ccc-00000000e501',
  'createdAt': '2026-09-26T02:15:03Z',
};

Map<String, dynamic> stageSetJson({bool complete = true}) => {
  'projectId': 7,
  'weightSum': complete ? 100 : 80,
  'complete': complete,
  'progressPct': 20,
  'stages': [
    {'id': 32, 'name': 'Struktur', 'weightPct': 30, 'sequence': 2, 'progressPct': 40, 'active': true},
    {'id': 30, 'name': 'Persiapan', 'weightPct': 20, 'sequence': 1, 'progressPct': 100, 'active': true},
    {'id': 33, 'name': 'Lama', 'weightPct': 0, 'sequence': 3, 'progressPct': 0, 'active': false},
  ],
};

Map<String, dynamic> projectProgressJson() => {
  'asOf': '2026-09-26T02:00:00Z',
  'warnGapPct': 10,
  'badGapPct': 20,
  'projects': [
    {
      'id': 7,
      'code': 'P-07',
      'name': 'Gudang Contoh',
      'status': 'berjalan',
      'budget': 1500000000,
      'committed': 780000000,
      'budgetPct': 52,
      'budgetTone': 'ok',
      'progressPct': 24.5,
      'weightSum': 100,
      'stagesComplete': true,
      'gap': 27.5,
      'tone': 'bad',
      'toneLabel': 'Merah',
      'lastReportDate': '2026-09-26',
      'reportCount': 4,
    },
    {
      'id': 8,
      'code': 'P-08',
      'name': 'Jalan Contoh',
      'status': 'berjalan',
      'budget': null,
      'committed': 0,
      'budgetPct': null,
      'budgetTone': 'none',
      'progressPct': 0,
      'weightSum': 60,
      'stagesComplete': false,
      'gap': null,
      'tone': 'none',
      'toneLabel': '',
      'lastReportDate': null,
      'reportCount': 0,
    },
  ],
};

Map<String, dynamic> _loc(String type, int id, String code, String name) => {
  'type': type,
  'id': id,
  'code': code,
  'name': name,
};

Map<String, dynamic> recapJson() => {
  'employee': {'id': 44, 'code': 'E44', 'name': 'Budi Contoh'},
  'month': '2026-09',
  'from': '2026-09-01',
  'to': '2026-09-03',
  'timezone': 'Asia/Makassar',
  'schedule': {
    'id': 1,
    'name': 'Kantor',
    'start': '08:00',
    'end': '17:00',
    'toleranceMin': 10,
    'workDays': [1, 2, 3, 4, 5],
  },
  'days': [
    {
      'date': '2026-09-01',
      'weekday': 2,
      'kind': 'workday',
      'holidayName': null,
      'status': 'selesai',
      'checkIn': '2026-09-01T00:22:00Z',
      'checkOut': '2026-09-01T09:05:00Z',
      'checkInLocal': '08:22',
      'checkOutLocal': '17:05',
      'workMinutes': 523,
      'lateMinutes': 12,
      'earlyLeaveMinutes': 0,
      'onBehalf': false,
      'onBehalfBy': <String>[],
      'corrected': false,
      'flags': <String>[],
      'locations': [
        {
          'location': _loc('project', 7, 'P-07', 'Gudang Contoh'),
          'checkIn': {'id': 9001, 'time': '2026-09-01T00:22:00Z', 'source': 'self', 'corrected': false},
          'checkOut': {'id': 9002, 'time': '2026-09-01T09:05:00Z', 'source': 'self', 'corrected': false},
        },
      ],
    },
    {
      'date': '2026-09-02',
      'weekday': 3,
      'kind': 'workday',
      'holidayName': null,
      'status': 'tidak_hadir',
      'checkIn': null,
      'checkOut': null,
      'checkInLocal': null,
      'checkOutLocal': null,
      'workMinutes': null,
      'lateMinutes': 0,
      'earlyLeaveMinutes': 0,
      'onBehalf': false,
      'onBehalfBy': <String>[],
      'corrected': false,
      'flags': <String>[],
      'locations': <Object>[],
    },
    {
      'date': '2026-09-03',
      'weekday': 4,
      'kind': 'workday',
      'holidayName': null,
      'status': 'hadir',
      'checkIn': '2026-09-03T23:58:00Z',
      'checkOut': null,
      'checkInLocal': '07:58',
      'checkOutLocal': null,
      'workMinutes': null,
      'lateMinutes': 0,
      'earlyLeaveMinutes': 0,
      'onBehalf': true,
      'onBehalfBy': ['Doni Pratama'],
      'corrected': true,
      'flags': ['OFFLINE'],
      'locations': [
        {
          'location': _loc('cost_center', 3, 'CC-3', 'Ops Palangka'),
          'checkIn': {'id': 9003, 'time': '2026-09-03T23:58:00Z', 'source': 'pm', 'corrected': true},
          'checkOut': null,
        },
      ],
    },
  ],
  'summary': {
    'presentDays': 2,
    'workingDays': 3,
    'absentDays': 1,
    'lateDays': 1,
    'lateMinutes': 12,
    'earlyLeaveDays': 0,
    'earlyLeaveMinutes': 0,
    'workMinutes': 523,
    'holidayWorkDays': 0,
    'offDayWorkDays': 0,
    'incompleteDays': 0,
    'onBehalfDays': 1,
    'correctedDays': 1,
  },
};

Map<String, dynamic> _member(int id, String name, String status, {Map<String, dynamic>? checkIn}) => {
  'employee': {'id': id, 'code': 'E$id', 'name': name},
  'assigned': [_loc('project', 7, 'P-07', 'Gudang Contoh')],
  'status': status,
  'checkIn': checkIn?['time'],
  'checkOut': null,
  'checkInLocal': checkIn == null ? null : '07:58',
  'checkOutLocal': null,
  'lateMinutes': 0,
  'onBehalf': false,
  'corrected': false,
  'locations': [
    if (checkIn != null)
      {'location': _loc('project', 7, 'P-07', 'Gudang Contoh'), 'checkIn': checkIn, 'checkOut': null},
  ],
};

Map<String, dynamic> teamTodayJson() => {
  'date': '2026-09-26',
  'timezone': 'Asia/Makassar',
  'holidayName': null,
  'scope': 'team',
  'counts': {'total': 3, 'belum_absen': 1, 'hadir': 1, 'selesai': 1},
  'members': [
    _member(44, 'Budi Contoh', 'belum_absen'),
    _member(
      45,
      'Citra Contoh',
      'hadir',
      checkIn: {'id': 9101, 'time': '2026-09-25T23:58:00Z', 'source': 'self', 'corrected': false},
    ),
    {
      ..._member(
        46,
        'Dedi Contoh',
        'selesai',
        checkIn: {'id': 9102, 'time': '2026-09-25T23:40:00Z', 'source': 'pm', 'corrected': false},
      ),
      'checkOutLocal': '16:30',
      'onBehalf': true,
    },
  ],
};

/// E5 addendum (fictional). [step] only on inbox items.
Map<String, dynamic> addendumJson({
  int id = 61,
  String status = 'pending_ack',
  String? step = 'acknowledge',
  List<String> actions = const ['acknowledge', 'reject'],
}) => {
  'id': id,
  'uuid': null,
  'docNo': 'ADD/2609/0003',
  'status': status,
  'statusLabel': status == 'pending_ack' ? 'Menunggu Direktur' : 'Draft',
  'stepLabel': status == 'pending_ack' ? 'Direktur' : null,
  'project': {'id': 7, 'code': 'P-07', 'name': 'Gudang Contoh', 'budget': 1500000000},
  'addition': 250000000,
  'reason': 'Tambahan pondasi karena tanah lunak',
  'budgetAtSubmit': 1500000000,
  'oldBudget': null,
  'newBudget': null,
  'createdBy': {'id': 5, 'name': 'Doni Pratama'},
  'submittedAt': '2026-09-26T03:00:00Z',
  'decidedAt': null,
  'rejectReason': null,
  'cancelReason': null,
  'currentLevel': null,
  'source': 'apk',
  'createdAt': '2026-09-26T02:50:00Z',
  'step': ?step,
  'budget': {
    'current': 1500000000,
    'committed': 780000000,
    'afterAddition': 1750000000,
    'committedPctBefore': 52,
    'committedPctAfter': 44.57,
  },
  'allowedActions': actions,
  'approvalRule': null,
  'decisions': [
    if (status != 'draft' && status != 'pending_ack')
      {
        'id': 1,
        'position': 'diketahui',
        'level': 0,
        'actor': {'id': 2, 'name': 'Direktur Contoh'},
        'decision': 'acknowledged',
        'reason': null,
        'decidedAt': '2026-09-26T04:00:00Z',
        'budgetPctBefore': 52,
        'budgetPctAfter': 44.57,
        'signatureSource': 'profile',
      },
  ],
};
