/// Fictional `/api/v1` payloads shaped after packages/api-contract/openapi.json.
Map<String, dynamic> detailJson({
  String status = 'pending_approval',
  List<String> allowed = const ['approve', 'reject'],
  int? currentLevel = 1,
  List<Map<String, dynamic>>? approvals,
}) => {
  'id': 42,
  'docNo': '228/PB-DRMS/20/IX/2026',
  'type': 'reimburse',
  'typeLabel': 'Reimburse',
  'status': status,
  'statusLabel': 'Menunggu Approval',
  'title': 'Service Tronton',
  'projectId': null,
  'costCenterId': 7,
  'grandTotal': 1447500,
  'approvedAmount': null,
  'requestDate': '2026-09-20',
  'neededDate': '2026-09-22',
  'createdById': 3,
  'updatedAt': '2026-09-21T05:10:02Z',
  'openWarningFlags': 1,
  'uuid': 'u-1',
  'project': null,
  'costCenter': {'id': 7, 'code': 'OPS-PB', 'name': 'Ops Palangka Banjar'},
  'periodFrom': null,
  'periodTo': null,
  'notes': null,
  'requesters': [
    {'id': 11, 'code': 'E11', 'name': 'Budi'},
    {'id': 12, 'code': 'E12', 'name': 'Doni'},
  ],
  'createdBy': {'id': 3, 'name': 'Citra'},
  'bankAccountId': 21,
  'bank': {'bankName': 'Mandiri', 'accountNo': '•••0123', 'accountHolder': 'Doni Pratama'},
  'lines': [
    {
      'id': 'l1',
      'no': 1,
      'description': 'BBM',
      'qty': 1,
      'uom': {'id': 3, 'name': 'bulan'},
      'unitPrice': null,
      'unitPriceDisplay': 600000,
      'total': 600000,
      'notes': null,
      'category': {'id': 1, 'name': 'BBM'},
      'vehicle': {'id': 5, 'plateNo': 'DA1234XY', 'plateDisplay': 'DA 1234 XY', 'type': 'Hilux'},
    },
    {
      'id': 'l2',
      'no': 2,
      'description': 'Penginapan',
      'qty': 2,
      'uom': {'id': 4, 'name': 'kamar'},
      'unitPrice': 339000,
      'unitPriceDisplay': 339000,
      'total': 677000,
      'notes': null,
      'category': {'id': 2, 'name': 'Penginapan'},
      'vehicle': null,
    },
  ],
  'transferredTotal': 0,
  'approvalCycle': 1,
  'currentLevel': currentLevel,
  'approvalRule': {
    'id': 1,
    'name': 'Default',
    'acknowledge': 'required',
    'acknowledgerUserId': 9,
    'acknowledgeDelegatedTo': null,
    'acknowledgeDelegationReason': null,
    'steps': [
      {'level': 1, 'approverRole': 'pk-owner', 'approverUserId': null},
    ],
    'signDiajukan': 'required',
    'signDibuat': 'required',
  },
  'approvals':
      approvals ??
      [
        _appr(1, 'diajukan', 0, 'Budi', 'signed'),
        _appr(2, 'dibuat', 0, 'Citra', 'signed'),
        _appr(3, 'diketahui', 0, 'Eko', 'acknowledged'),
      ],
  'receipts': [
    {
      'id': 501,
      'lineId': 'l1',
      'lineNo': 1,
      'receiptNo': '7654321',
      'vendorName': 'SPBU',
      'receiptDate': '2026-09-21',
      'amount': 600000,
      'imageId': 901,
      'status': 'pending',
    },
  ],
  'flags': [
    {
      'id': 1,
      'kind': 'uom_suspicious',
      'kindLabel': 'Satuan tidak wajar',
      'level': 'warning',
      'status': 'open',
      'lineId': 'l1',
      'lineNo': 1,
      'receiptId': null,
      'relatedRequestId': null,
      'message': 'Satuan bulan',
      'reviewNote': null,
    },
  ],
  'transfers': [],
  'verifiedReceiptsTotal': null,
  'settlement': null,
  'budget': {'basis': 'project', 'pctBefore': 70.5, 'pctAfter': 88.25},
  'allowedActions': allowed,
  'resubmitOfId': null,
  'resubmitOf': null,
  'submittedAt': '2026-09-20T02:00:00Z',
  'cancelReason': null,
  'rejectReason': null,
  'clientUuid': '0192f6d0-aaaa-7bbb-8ccc-000000000100',
  'createdAt': '2026-09-20T01:00:00Z',
};

Map<String, dynamic> _appr(int id, String pos, int level, String name, String decision) => {
  'id': id,
  'cycle': 1,
  'position': pos,
  'level': level,
  'actorId': id,
  'employeeId': null,
  'actorName': name,
  'onBehalf': false,
  'decision': decision,
  'reason': null,
  'decidedAt': '2026-09-20T02:0$id:00Z',
  'budgetPctBefore': null,
  'budgetPctAfter': null,
  'openFlags': null,
  'signatureId': null,
  'signatureSha256': null,
  'signatureSource': null,
};

Map<String, dynamic> inboxJson() => {
  'budgetWarnPct': 85,
  'items': [
    {
      'id': 42,
      'docNo': '228/PB-DRMS/20/IX/2026',
      'type': 'reimburse',
      'typeLabel': 'Reimburse',
      'status': 'pending_approval',
      'statusLabel': 'Menunggu Approval',
      'title': 'Service Tronton',
      'scope': 'OPS-PB Ops Palangka Banjar',
      'requesters': 'Budi, Doni',
      'grandTotal': 1447500,
      'approvedAmount': null,
      'neededDate': '2026-09-22',
      'requestDate': '2026-09-20',
      'step': 'approve',
      'level': 1,
      'budget': {'basis': 'project', 'pctBefore': 70.5, 'pctAfter': 88.25, 'overWarn': true},
      'flags': {'warning': 1, 'info': 2},
    },
  ],
};

Map<String, dynamic> meJson({List<String> roles = const ['pk-staff']}) => {
  'id': 5,
  'email': 'doni@example.test',
  'name': 'Doni Pratama',
  'roles': roles,
  'employee': {'id': 12, 'code': 'E12', 'name': 'Doni Pratama'},
  'authMethod': 'mobileBearer',
  'device': null,
  'settings': {
    'companyName': 'PT Contoh',
    'shortCode': 'DRMS',
    'timezone': 'Asia/Makassar',
    'minAppVersion': null,
    'offlineMaxAgeDays': 30,
    'defaultGeofenceRadiusM': 100,
    'receiptRoundingTolerance': 1000,
    'receiptMaxAgeDays': 30,
    'imageTargets': {
      'receiptsMaxPx': 2000,
      'selfiesMaxPx': 1080,
      'transferProofsMaxPx': 2000,
      'progressPhotosMaxPx': 2000,
      'jpegQuality': 82,
    },
  },
  'serverTime': '2026-09-21T04:05:11Z',
};
