/* GENERATED by scripts/gen-openapi.mjs — do not edit. */
export const openapiDocument = {
  "openapi": "3.1.0",
  "info": {
    "title": "ProyekKas API v1",
    "version": "0.1.0",
    "description": "Versioned contract for the Android APK and admin custom views (architecture §6). Errors: RFC 9457."
  },
  "servers": [
    {
      "url": "/api/v1"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Keycloak access token of client proyekkas-mobile (realm drms). Requires header X-Device-Id of a registered active device."
      },
      "session": {
        "type": "apiKey",
        "in": "cookie",
        "name": "__Host-pk_session",
        "description": "Admin web session (OIDC login via /auth/login)."
      }
    },
    "schemas": {
      "Health": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": [
              "ok"
            ]
          }
        },
        "required": [
          "status"
        ]
      },
      "Ready": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": [
              "ok",
              "degraded"
            ]
          },
          "checks": {
            "type": "object",
            "properties": {
              "db": {
                "type": "boolean"
              },
              "media": {
                "type": "boolean"
              }
            },
            "required": [
              "db",
              "media"
            ]
          }
        },
        "required": [
          "status",
          "checks"
        ]
      },
      "Me": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "email": {
            "type": "string"
          },
          "name": {
            "type": [
              "string",
              "null"
            ]
          },
          "roles": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Role"
            }
          },
          "employee": {
            "type": [
              "object",
              "null"
            ],
            "properties": {
              "id": {
                "type": "integer"
              },
              "code": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "code",
              "name"
            ]
          },
          "authMethod": {
            "type": "string",
            "enum": [
              "oidcSession",
              "mobileBearer"
            ]
          },
          "device": {
            "type": [
              "object",
              "null"
            ],
            "properties": {
              "id": {
                "type": "integer"
              },
              "deviceId": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "deviceId"
            ]
          },
          "settings": {
            "type": "object",
            "properties": {
              "companyName": {
                "type": "string"
              },
              "shortCode": {
                "type": "string"
              },
              "timezone": {
                "type": "string"
              },
              "minAppVersion": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "offlineMaxAgeDays": {
                "type": "integer"
              },
              "defaultGeofenceRadiusM": {
                "type": "integer"
              },
              "receiptRoundingTolerance": {
                "type": "integer"
              },
              "receiptMaxAgeDays": {
                "type": "integer"
              },
              "imageTargets": {
                "$ref": "#/components/schemas/ImageTargets"
              }
            },
            "required": [
              "companyName",
              "shortCode",
              "timezone",
              "minAppVersion",
              "offlineMaxAgeDays",
              "defaultGeofenceRadiusM",
              "receiptRoundingTolerance",
              "receiptMaxAgeDays",
              "imageTargets"
            ]
          },
          "serverTime": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "email",
          "name",
          "roles",
          "employee",
          "authMethod",
          "device",
          "settings",
          "serverTime"
        ]
      },
      "Role": {
        "type": "string",
        "enum": [
          "pk-staff",
          "pk-pm",
          "pk-finance",
          "pk-owner",
          "pk-admin"
        ]
      },
      "ImageTargets": {
        "type": "object",
        "properties": {
          "receiptsMaxPx": {
            "type": "integer"
          },
          "selfiesMaxPx": {
            "type": "integer"
          },
          "transferProofsMaxPx": {
            "type": "integer"
          },
          "progressPhotosMaxPx": {
            "type": "integer"
          },
          "jpegQuality": {
            "type": "integer"
          }
        },
        "required": [
          "receiptsMaxPx",
          "selfiesMaxPx",
          "transferProofsMaxPx",
          "progressPhotosMaxPx",
          "jpegQuality"
        ]
      },
      "Problem": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "status": {
            "type": "integer"
          },
          "detail": {
            "type": "string"
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "path": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": [
                "path",
                "message"
              ]
            }
          },
          "minAppVersion": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "title",
          "status"
        ],
        "description": "RFC 9457 problem details"
      },
      "Masters": {
        "type": "object",
        "properties": {
          "serverTime": {
            "type": "string"
          },
          "types": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "properties": {
                "items": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MasterItem"
                  }
                },
                "hasMore": {
                  "type": "boolean"
                }
              },
              "required": [
                "items",
                "hasMore"
              ]
            }
          }
        },
        "required": [
          "serverTime",
          "types"
        ]
      },
      "MasterItem": {
        "type": "object",
        "additionalProperties": {},
        "description": "Whitelisted fields per type (id, updatedAt, active, …)"
      },
      "Device": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "deviceId": {
            "type": "string"
          },
          "status": {
            "type": "string",
            "enum": [
              "active",
              "revoked",
              "lost"
            ]
          },
          "model": {
            "type": [
              "string",
              "null"
            ]
          },
          "appVersion": {
            "type": [
              "string",
              "null"
            ]
          },
          "registeredAt": {
            "type": [
              "string",
              "null"
            ]
          },
          "lastSeenAt": {
            "type": [
              "string",
              "null"
            ]
          },
          "revokedAt": {
            "type": [
              "string",
              "null"
            ]
          }
        },
        "required": [
          "id",
          "deviceId",
          "status",
          "model",
          "appVersion",
          "registeredAt",
          "lastSeenAt",
          "revokedAt"
        ]
      },
      "DeviceRegister": {
        "type": "object",
        "properties": {
          "deviceId": {
            "type": "string",
            "format": "uuid",
            "description": "Install id generated by the APK (UUID); must equal X-Device-Id."
          },
          "platform": {
            "type": "string",
            "enum": [
              "android"
            ]
          },
          "model": {
            "type": "string",
            "maxLength": 128
          },
          "appVersion": {
            "type": "string",
            "pattern": "^[0-9A-Za-z.+-]{1,32}$"
          },
          "fcmToken": {
            "type": "string",
            "maxLength": 4096
          }
        },
        "required": [
          "deviceId",
          "platform"
        ],
        "additionalProperties": false
      },
      "DeviceRevoke": {
        "type": "object",
        "properties": {
          "reason": {
            "type": "string",
            "minLength": 3,
            "maxLength": 500
          }
        },
        "required": [
          "reason"
        ],
        "additionalProperties": false
      }
    },
    "parameters": {}
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "Liveness",
        "responses": {
          "200": {
            "description": "Process up",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Health"
                }
              }
            }
          }
        }
      }
    },
    "/health/ready": {
      "get": {
        "summary": "Readiness (DB + media volume)",
        "responses": {
          "200": {
            "description": "Ready",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Ready"
                }
              }
            }
          },
          "503": {
            "description": "Degraded",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Ready"
                }
              }
            }
          }
        }
      }
    },
    "/me": {
      "get": {
        "summary": "Current user, effective roles, employee link and settings subset",
        "security": [
          {
            "bearer": []
          },
          {
            "session": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid",
              "description": "Registered install id (APK)."
            },
            "required": true,
            "description": "Registered install id (APK).",
            "name": "X-Device-Id",
            "in": "header"
          },
          {
            "schema": {
              "type": "string",
              "description": "APK version; below company minimum → 426."
            },
            "required": false,
            "description": "APK version; below company minimum → 426.",
            "name": "X-App-Version",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "Profile",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Me"
                }
              }
            }
          },
          "401": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "426": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          }
        }
      }
    },
    "/masters": {
      "get": {
        "summary": "Master data for the APK (access-filtered, delta sync)",
        "security": [
          {
            "bearer": []
          },
          {
            "session": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "pattern": "^[a-z-]+(,[a-z-]+)*$",
              "description": "Comma separated subset of: projects, project-stages, cost-centers, expense-categories, uoms, vehicles, employees, banks, bank-accounts, work-schedules, holidays, team-assignments. Default: all."
            },
            "required": false,
            "description": "Comma separated subset of: projects, project-stages, cost-centers, expense-categories, uoms, vehicles, employees, banks, bank-accounts, work-schedules, holidays, team-assignments. Default: all.",
            "name": "types",
            "in": "query"
          },
          {
            "schema": {
              "type": "string",
              "format": "date-time",
              "description": "Only records updated after this instant (delta sync)."
            },
            "required": false,
            "description": "Only records updated after this instant (delta sync).",
            "name": "since",
            "in": "query"
          },
          {
            "schema": {
              "type": "string",
              "format": "uuid",
              "description": "Registered install id (APK)."
            },
            "required": true,
            "description": "Registered install id (APK).",
            "name": "X-Device-Id",
            "in": "header"
          },
          {
            "schema": {
              "type": "string",
              "description": "APK version; below company minimum → 426."
            },
            "required": false,
            "description": "APK version; below company minimum → 426.",
            "name": "X-App-Version",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "Masters",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Masters"
                }
              }
            }
          },
          "400": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "401": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "426": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          }
        }
      }
    },
    "/devices/register": {
      "post": {
        "summary": "Register (or refresh) this APK install; bearer only",
        "security": [
          {
            "bearer": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "format": "uuid",
              "description": "Registered install id (APK)."
            },
            "required": true,
            "description": "Registered install id (APK).",
            "name": "X-Device-Id",
            "in": "header"
          },
          {
            "schema": {
              "type": "string",
              "description": "APK version; below company minimum → 426."
            },
            "required": false,
            "description": "APK version; below company minimum → 426.",
            "name": "X-App-Version",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeviceRegister"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Refreshed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Device"
                }
              }
            }
          },
          "201": {
            "description": "Registered",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Device"
                }
              }
            }
          },
          "400": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "401": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "403": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "409": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "426": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "429": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          }
        }
      }
    },
    "/devices/{id}/revoke": {
      "post": {
        "summary": "Revoke a device (own device, or any as Admin/Owner) — ends its Keycloak session",
        "security": [
          {
            "bearer": []
          },
          {
            "session": []
          }
        ],
        "parameters": [
          {
            "schema": {
              "type": "string",
              "description": "Device record id or deviceId (UUID)"
            },
            "required": true,
            "description": "Device record id or deviceId (UUID)",
            "name": "id",
            "in": "path"
          },
          {
            "schema": {
              "type": "string",
              "format": "uuid",
              "description": "Registered install id (APK)."
            },
            "required": true,
            "description": "Registered install id (APK).",
            "name": "X-Device-Id",
            "in": "header"
          },
          {
            "schema": {
              "type": "string",
              "description": "APK version; below company minimum → 426."
            },
            "required": false,
            "description": "APK version; below company minimum → 426.",
            "name": "X-App-Version",
            "in": "header"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeviceRevoke"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Revoked",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Device"
                }
              }
            }
          },
          "400": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "401": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "404": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "426": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          },
          "429": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          }
        }
      }
    },
    "/openapi.json": {
      "get": {
        "summary": "This document (authentication required outside development)",
        "security": [
          {
            "bearer": []
          },
          {
            "session": []
          }
        ],
        "responses": {
          "200": {
            "description": "OpenAPI 3.1 document"
          },
          "401": {
            "description": "Problem",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/Problem"
                }
              }
            }
          }
        }
      }
    }
  },
  "webhooks": {}
} as const
