import { z } from 'zod'

/**
 * /api/v1 contract (zod → OpenAPI 3.1 via @asteasolutions/zod-to-openapi, architecture §6.4).
 * Schema names come from zod `.meta({ id })` (supported since zod-to-openapi v8 / zod 4, README).
 */
export const Problem = z
  .object({
    type: z.string(),
    title: z.string(),
    status: z.number().int(),
    detail: z.string().optional(),
    errors: z.array(z.object({ path: z.string(), message: z.string() })).optional(),
    minAppVersion: z.string().optional(),
  })
  .meta({ id: 'Problem', description: 'RFC 9457 problem details' })

export const Health = z.object({ status: z.literal('ok') }).meta({ id: 'Health' })

export const Ready = z
  .object({
    status: z.enum(['ok', 'degraded']),
    checks: z.object({ db: z.boolean(), media: z.boolean() }),
  })
  .meta({ id: 'Ready' })

export const RoleEnum = z.enum(['pk-staff', 'pk-pm', 'pk-finance', 'pk-owner', 'pk-admin']).meta({ id: 'Role' })

export const ImageTargets = z
  .object({
    receiptsMaxPx: z.number().int(),
    selfiesMaxPx: z.number().int(),
    transferProofsMaxPx: z.number().int(),
    progressPhotosMaxPx: z.number().int(),
    jpegQuality: z.number().int(),
  })
  .meta({ id: 'ImageTargets' })

export const Me = z
  .object({
    id: z.number().int(),
    email: z.string(),
    name: z.string().nullable(),
    roles: z.array(RoleEnum),
    employee: z.object({ id: z.number().int(), code: z.string(), name: z.string() }).nullable(),
    authMethod: z.enum(['oidcSession', 'mobileBearer']),
    device: z.object({ id: z.number().int(), deviceId: z.string() }).nullable(),
    settings: z.object({
      companyName: z.string(),
      shortCode: z.string(),
      timezone: z.string(),
      minAppVersion: z.string().nullable(),
      offlineMaxAgeDays: z.number().int(),
      defaultGeofenceRadiusM: z.number().int(),
      receiptRoundingTolerance: z.number().int(),
      receiptMaxAgeDays: z.number().int(),
      imageTargets: ImageTargets,
    }),
    serverTime: z.string(),
  })
  .meta({ id: 'Me' })

export const MASTER_TYPES = [
  'projects',
  'project-stages',
  'cost-centers',
  'expense-categories',
  'uoms',
  'vehicles',
  'employees',
  'banks',
  'bank-accounts',
  'work-schedules',
  'holidays',
  'team-assignments',
] as const
export type MasterType = (typeof MASTER_TYPES)[number]

export const MastersQuery = z
  .object({
    types: z
      .string()
      .regex(/^[a-z-]+(,[a-z-]+)*$/)
      .optional()
      .meta({ description: `Comma separated subset of: ${MASTER_TYPES.join(', ')}. Default: all.` }),
    since: z.iso.datetime({ offset: true }).optional().meta({ description: 'Only records updated after this instant (delta sync).' }),
  })
  .meta({ id: 'MastersQuery' })

const MasterItem = z.record(z.string(), z.unknown()).meta({ id: 'MasterItem', description: 'Whitelisted fields per type (id, updatedAt, active, …)' })

export const Masters = z
  .object({
    serverTime: z.string(),
    types: z.record(z.string(), z.object({ items: z.array(MasterItem), hasMore: z.boolean() })),
  })
  .meta({ id: 'Masters' })

export const DeviceRegister = z
  .object({
    deviceId: z.uuid().meta({ description: 'Install id generated by the APK (UUID); must equal X-Device-Id.' }),
    platform: z.literal('android'),
    model: z.string().max(128).optional(),
    appVersion: z.string().regex(/^[0-9A-Za-z.+-]{1,32}$/).optional(),
    fcmToken: z.string().min(1).max(4096).nullable().optional().meta({ description: 'FCM token (ADR 0011); null clears it, omitted keeps it. Push is not enabled yet (GET /app/config features.pushEnabled).' }),
  })
  .strict()
  .meta({ id: 'DeviceRegister' })

export const Device = z
  .object({
    id: z.number().int(),
    deviceId: z.string(),
    status: z.enum(['active', 'revoked', 'lost']),
    model: z.string().nullable(),
    appVersion: z.string().nullable(),
    registeredAt: z.string().nullable(),
    lastSeenAt: z.string().nullable(),
    revokedAt: z.string().nullable(),
  })
  .meta({ id: 'Device' })

export const DeviceRevoke = z
  .object({ reason: z.string().trim().min(3).max(500) })
  .strict()
  .meta({ id: 'DeviceRevoke' })

export const TestEmailQueued = z
  .object({
    queued: z.literal(true),
    jobId: z.string().meta({ description: 'payload_jobs id of the sendEmail job (sent by the worker)' }),
  })
  .meta({ id: 'TestEmailQueued' })
